import {createHash} from 'node:crypto';
import {defineConfig} from 'vite';
import {copyFileSync,mkdirSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const source=fileURLToPath(new URL('./src/unified.css',import.meta.url));
const destination=fileURLToPath(new URL('../amplifier_web/static/unified.amplifier.css',import.meta.url));
// Native PAM login is authored beside, not generated by, the React app.
const loginPath=fileURLToPath(new URL('../amplifier_web/static/login.html',import.meta.url));
const loginPage=readFileSync(loginPath);
function sources(path){return readdirSync(path,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name,'en')).flatMap(row=>row.isDirectory()?sources(`${path}/${row.name}`):[`${path}/${row.name}`])}
const hash=createHash('sha256');for(const file of [...sources(fileURLToPath(new URL('./src',import.meta.url))),fileURLToPath(new URL('../amplifier_web/provider_sources.json',import.meta.url)),fileURLToPath(new URL('../amplifier_web/voice_options.json',import.meta.url)),fileURLToPath(import.meta.url),fileURLToPath(new URL('./package-lock.json',import.meta.url))])hash.update(readFileSync(file));
const version=readFileSync(fileURLToPath(new URL('../pyproject.toml',import.meta.url)),'utf8').match(/^version = "([^"]+)"/m)[1];
const buildIdentity={version,id:hash.digest('hex').slice(0,16)};
export default defineConfig({
 define:{__AMPLIFIER_BUILD__:JSON.stringify(buildIdentity)},

 base:'/',
 plugins:[{name:'bundle-shareable-skin',closeBundle(){
  writeFileSync(loginPath,loginPage);
  writeFileSync(fileURLToPath(new URL('../amplifier_web/static/build.json',import.meta.url)),JSON.stringify(buildIdentity)+'\n');
  copyFileSync(source,destination);
  const vendor=fileURLToPath(new URL('../amplifier_web/static/vendor',import.meta.url));mkdirSync(vendor,{recursive:true});
  copyFileSync(fileURLToPath(new URL('./node_modules/babylonjs/babylon.js',import.meta.url)),`${vendor}/babylon.js`);
  const licenses=fileURLToPath(new URL('../amplifier_web/static/licenses',import.meta.url));mkdirSync(licenses,{recursive:true});
  copyFileSync(fileURLToPath(new URL('./node_modules/babylonjs/license.md',import.meta.url)),`${licenses}/babylonjs.txt`);
  copyFileSync(fileURLToPath(new URL('./node_modules/babylonjs/NOTICE.md',import.meta.url)),`${licenses}/babylonjs-notice.txt`);
  for(const [name,file] of [['@modelcontextprotocol/ext-apps','mcp-apps'],['@modelcontextprotocol/client','mcp-client'],['@modelcontextprotocol/core','mcp-core'],['zod','zod']])copyFileSync(fileURLToPath(new URL(`./node_modules/${name}/LICENSE`,import.meta.url)),`${licenses}/${file}.txt`);
  for(const name of ['mermaid','dompurify','highlight.js'])copyFileSync(fileURLToPath(new URL(`./node_modules/${name}/LICENSE`,import.meta.url)),`${licenses}/${name}.txt`);
 }}],
 build:{outDir:'../amplifier_web/static',emptyOutDir:true,rollupOptions:{input:{app:fileURLToPath(new URL('./index.html',import.meta.url)),shellValidation:fileURLToPath(new URL('./shell-validation.html',import.meta.url))}}},
 server:{proxy:{'/api':'http://127.0.0.1:8765'}},
});
