import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
const {createRecallCapability}=await import(process.env.STARTUP_NODE_MODULE??'../src/index.js');const python=process.env.STARTUP_PYTHON;const family='recall',module='amplifier_unified_recall';
async function setup(t,kind){const dir=await mkdtemp(join(tmpdir(),family+'-startup-')),state=join(dir,'state'),config=join(dir,'config.json');await writeFile(config,JSON.stringify({dataDir:state}));const database=join(state,family==='recall'?'recall.sqlite3':'feedback.sqlite3');let uploads;
if(family==='feedback')uploads=(await import(process.env.STARTUP_RESOURCES_MODULE)).createResourcesCapability({directory:join(dir,'uploads'),inspectSession:async()=>{throw Error('No startup history callback')}});
const owner=createRecallCapability({owner:{command:python,args:['-I','-B','-m',module+'.server','--config',config]},...(uploads?{uploadOwner:uploads}: {})});t.after(async()=>{await owner.close();await rm(dir,{recursive:true,force:true})});return {dir,state,database,config,owner};}
for(const missing of ['memory_receipts', 'memory_commands'])test('startup table loss refuses schemas/readiness without replacing authority: '+missing,{skip:!python},async t=>{
const {database,config,owner}=await setup(t);const code="import asyncio,json,sqlite3,sys;from pathlib import Path;from "+module+".owner import Owner;cb=lambda *args:None;o=Owner(json.loads(Path(sys.argv[1]).read_text()),cb,cb);asyncio.run(o.close());db=sqlite3.connect(sys.argv[2]);db.execute('DROP TABLE '+sys.argv[3]);db.commit();db.close()";execFileSync(python,['-I','-B','-c',code,config,database,missing]);const before=await readFile(database);await assert.rejects(owner.actionSchemas(),/exited|closed/i);await assert.rejects(owner.actionSchemas(),/exited|closed/i);assert.deepEqual(await readFile(database),before);
const result=execFileSync(python,['-I','-B','-c',"import sqlite3,sys;db=sqlite3.connect(sys.argv[1]);print(db.execute('SELECT count(*) FROM sqlite_master WHERE name=?',(sys.argv[2],)).fetchone()[0]);db.close()",database,missing],{encoding:'utf8'}).trim();assert.equal(result,'0');});
test('startup zero-length SHM with absent main is preserved without owner readiness',{skip:!python},async t=>{const {state,database,owner}=await setup(t);await mkdir(state);await writeFile(database+'-shm','');await assert.rejects(owner.actionSchemas(),/exited|closed/i);await assert.rejects(readFile(database),{code:'ENOENT'});assert.equal((await readFile(database+'-shm')).length,0);});
