"""Upgrade old editable caches without rewriting their contents or receipts."""
import importlib.util
import json
from pathlib import Path
import shutil
import subprocess

import pytest

from amplifier_web import runtime_environment as environments, runtime_qualification, updates
from test_runtime_updates import environment, git


@pytest.fixture
def legacy_worker(environment):
    manager, baseline, _, _, _, _ = environment
    generation = '9' * 32
    receipt = environments.receipt_directory(manager.home, generation)
    receipt.mkdir(parents=True)
    shutil.copy2(baseline / 'pyproject.toml', receipt / 'runtime.toml')
    shutil.copy2(baseline / 'uv.lock', receipt / 'runtime.lock')
    (receipt / 'validated.json').write_text('{"hostVersion":"0.19.18"}')
    (manager.home / 'updates/active.json').write_text(json.dumps({'current': generation}))
    project = environments.prepare_project(manager.home, generation)
    remote = manager.home.parent / 'legacy-module-remote'
    remote.mkdir()
    git(remote, 'init', '-b', 'main')
    git(remote, 'config', 'user.name', 'Fixture')
    git(remote, 'config', 'user.email', 'fixture@example.invalid')
    module = remote / 'modules/hooks'
    module.mkdir(parents=True)
    (module / 'pyproject.toml').write_text('[project]\nname="amplifier-legacy-hooks"\nversion="0.1.0"\n'
        '[build-system]\nrequires=["setuptools"]\nbuild-backend="setuptools.build_meta"\n[tool.setuptools]\npackages=[]\n')
    (module / 'source.py').write_text('value = 1\n')
    bytecode = Path('modules/hooks/__pycache__/source.cpython-313.pyc')
    (remote / bytecode).parent.mkdir()
    (remote / bytecode).write_bytes(importlib.util.MAGIC_NUMBER + bytes(12) + b'old bytecode')
    git(remote, 'add', '.')
    git(remote, 'commit', '-m', 'Legacy bundle tracks generated bytecode')
    cache = receipt / 'shared-config/cache/legacy-module'
    cache.parent.mkdir(parents=True)
    git(cache.parent, 'clone', str(remote), str(cache))
    revision = git(cache, 'rev-parse', 'HEAD')
    (cache / '.amplifier_cache_meta.json').write_text(json.dumps({'git_url': remote.as_uri(), 'ref': 'main', 'commit': revision}))
    (cache / bytecode).write_bytes(importlib.util.MAGIC_NUMBER + bytes(12) + b'locally regenerated bytecode')
    metadata = project / '.venv/lib/python3.13/site-packages/amplifier_legacy_hooks-0.1.0.dist-info'
    metadata.mkdir(parents=True)
    (metadata / 'METADATA').write_text('Name: amplifier-legacy-hooks\nVersion: 0.1.0\n')
    (metadata / 'direct_url.json').write_text(json.dumps({'url': (cache / 'modules/hooks').as_uri(), 'dir_info': {'editable': True}}))
    return manager, project, receipt, cache, bytecode


def package(rows):
    return next(row for row in rows if row.get('package') == 'amplifier-legacy-hooks')


def snapshot(root):
    return {str(path.relative_to(root)): path.read_bytes() for path in root.rglob('*')
            if path.is_file() and '.git' not in path.parts}


async def test_019_generated_cache_can_stage_and_qualify_fresh_worker(legacy_worker):
    manager, current, receipt, cache, bytecode = legacy_worker
    before = snapshot(receipt)
    graph = runtime_qualification.installed_graph(current)
    assert graph[0]['cacheSource']['dirty']
    row = package(await environments.update_inventory(manager.home))
    assert row['eligible'] and not row.get('override')
    assert row['ref'] == 'main' and row['subdirectory'] == 'modules/hooks'
    # New policy does not normalize or change the recorded evidence API.
    assert runtime_qualification.installed_graph(current) == graph
    assert package(environments.inventory(manager.home))['override']
    generation = '8' * 32
    target = environments.receipt_directory(manager.home, generation)
    target.mkdir(parents=True)
    staged = await environments.stage(manager, generation, [{**row, 'latest': row['current']}], finalize=False)
    resolved = environments.locked_sources(staged)['amplifier-legacy-hooks']
    assert resolved.fragment == row['current']
    subprocess.run([shutil.which('uv'), 'sync', '--locked', '--project', str(staged)], check=True, capture_output=True)
    final = await runtime_qualification.freeze(manager, generation, staged)
    runtime_qualification.verify_recorded(final, target)
    assert snapshot(receipt) == before
    assert runtime_qualification.installed_graph(current) == graph
    assert updates.active_release(manager.home)['current'] == receipt.name
    # Revalidating the old generation neither refreshes it nor creates evidence.
    await environments.stage(manager, receipt.name, [])
    assert snapshot(receipt) == before
    assert not (receipt / 'runtime-installed.json').exists()


@pytest.mark.parametrize('change', ['source', 'staged-bytecode', 'staged-source', 'malformed-bytecode'])
async def test_changes_after_check_remain_protected(legacy_worker, change):
    manager, current, receipt, cache, bytecode = legacy_worker
    row = package(await environments.update_inventory(manager.home))
    assert row['eligible']
    if change in {'source', 'staged-source'}:
        (cache / 'modules/hooks/source.py').write_text('user_change = True\n')
        if change == 'staged-source':
            git(cache, 'add', 'modules/hooks/source.py')
    elif change == 'staged-bytecode':
        git(cache, 'add', str(bytecode))
    else:
        (cache / bytecode).write_bytes(b'not verified generated bytecode')
    before = snapshot(receipt)
    index = (cache / '.git/index').read_bytes()
    target = environments.receipt_directory(manager.home, '7' * 32)
    target.mkdir(parents=True)
    with pytest.raises(environments.ProtectedRuntimeSource) as caught:
        await environments.stage(manager, target.name, [{**row, 'latest': row['current']}])
    assert caught.value.diagnostic_facts['package'] == row['package']
    assert snapshot(receipt) == before and (cache / '.git/index').read_bytes() == index
    assert not (target / 'runtime.lock').exists()
    assert updates.active_release(manager.home)['current'] == receipt.name


async def test_recorded_graph_is_strict_and_pin_stays_pinned(legacy_worker):
    manager, current, receipt, cache, bytecode = legacy_worker
    meta = cache / '.amplifier_cache_meta.json'
    data = json.loads(meta.read_text())
    data['ref'] = data['commit']
    meta.write_text(json.dumps(data))
    row = package(await environments.update_inventory(manager.home))
    assert row['status'] == 'pinned' and not row['eligible']
    manifest = environments.augmented_manifest(environments.manifest_path().read_bytes(), [row])
    assert ('@' + data['commit']).encode() in manifest
    # A cache-backed override of an app-declared module retains its pin too.
    import tomllib
    declared = environments.manifest_path().read_bytes() + b'\namplifier-legacy-hooks={git="https://example.invalid/default",branch="main"}\n'
    policy = tomllib.loads(environments.augmented_manifest(declared, [row]).decode())
    assert policy['tool']['uv']['sources']['amplifier-legacy-hooks'] == {'git': data['git_url'], 'rev': data['commit'], 'subdirectory': 'modules/hooks'}
    evidence = receipt / 'runtime-installed.json'
    evidence.write_text(json.dumps(runtime_qualification.installed_graph(current)))
    frozen = evidence.read_bytes()
    runtime_qualification.verify_recorded(current, receipt)
    # Once evidence exists, even the exact same generated-only changes cannot
    # use legacy compatibility to disguise a recorded graph as clean.
    assert package(await environments.update_inventory(manager.home))['override']
    (cache / bytecode).write_bytes(importlib.util.MAGIC_NUMBER + bytes(12) + b'another generated value')
    with pytest.raises(ValueError, match='changed after qualification'):
        runtime_qualification.verify_recorded(current, receipt)
    assert evidence.read_bytes() == frozen


async def test_local_cache_metadata_cannot_enable_external_override(legacy_worker):
    manager, current, receipt, cache, bytecode = legacy_worker
    external = manager.home.parent / 'user-worktree'
    shutil.copytree(cache, external)
    metadata = next(current.glob('.venv/lib/python*/site-packages/*/direct_url.json'))
    metadata.write_text(json.dumps({'url': (external / 'modules/hooks').as_uri(), 'dir_info': {'editable': True}}))
    row = package(await environments.update_inventory(manager.home))
    assert row['override'] and not row['eligible']
    with pytest.raises(environments.ProtectedRuntimeSource):
        await environments.update_manifest(manager.home)


async def test_classification_race_rejects_mixed_source_evidence(legacy_worker, monkeypatch):
    manager, current, receipt, cache, bytecode = legacy_worker
    classify = updates.cache_changes
    async def changed(root):
        result = await classify(root)
        (cache / 'modules/hooks/source.py').write_text('changed_during_check = True\n')
        return result
    monkeypatch.setattr(updates, 'cache_changes', changed)
    with pytest.raises(environments.ProtectedRuntimeSource) as caught:
        await environments.update_inventory(manager.home)
    assert caught.value.diagnostic_facts['reason'] == 'runtime-source-changed'


async def test_symlinked_cache_parent_cannot_adopt_external_source(legacy_worker):
    manager, current, receipt, cache, bytecode = legacy_worker
    shared = receipt / 'shared-config'
    external = manager.home.parent / 'external-shared-config'
    shared.rename(external)
    shared.symlink_to(external, target_is_directory=True)
    row = package(await environments.update_inventory(manager.home))
    assert row['override'] and not row['eligible']
