import test from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import{mkdtemp,realpath,rm,readFile,unlink}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{pathToFileURL,fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const dist=process.env.DISTRIBUTION_OWNER_DIRECTORY??fileURLToPath(new URL('../dist',import.meta.url));const{Store}=await import(pathToFileURL(join(dist,'store.js'))),{ServiceStore}=await import(pathToFileURL(join(dist,'service-store.js'))),{createManualIngressGate}=await import(pathToFileURL(join(dist,'manual-ingress.js')));
const initial={schema:1,dataScope:'owned-scope',current:null,previous:null,catalog:null,lastCheck:0,lastCheckSucceeded:false,preferences:{autoCheck:false,autoInstall:false,intervalMs:60000}};
const op={id:'original',command:'install',args:{target:'inactive-fixture'},status:'running',phase:'restart',createdAt:1,updatedAt:1,admissionSettlement:{state:'pending',outcome:'unknown',updatedAt:1}};
const binding={installationId:'fixture',ownerId:'service',dataScope:'owned-scope'},command={commandId:'original',command:'stop',status:'running',createdAt:1,updatedAt:1,admissionSettlement:{state:'pending'}};
const hash=async p=>createHash('sha256').update(await readFile(p)).digest('hex');async function dir(t){const p=await realpath(await mkdtemp(join(tmpdir(),'sqlite-authority-')));t.after(()=>rm(p,{recursive:true,force:true}));return p}function change(path,sql){const db=new DatabaseSync(path);db.exec(sql);db.close()}
for(const table of ['owner','state','operations','events','release_notes','notice_reviews','preference_revision','preference_reset_reviews','preference_reset_commands'])test(`marked update authority refuses missing ${table} without recreating it`,async t=>{const p=await dir(t),file=join(p,'updates.sqlite3');let s=new Store(p,initial);s.accept(op);s.close();s=new Store(p,initial);assert.equal(s.read('original').status,'unknown');assert.equal(s.accept(op).fresh,false);s.close();change(file,'DROP TABLE '+table);const before=await hash(file);assert.throws(()=>new Store(p,initial),/updates_ledger_unconfirmed/);assert.equal(await hash(file),before);const db=new DatabaseSync(file,{readOnly:true});assert.equal(db.prepare('SELECT count(*) n FROM sqlite_master WHERE name=?').get(table).n,0);db.close()});
for(const table of ['owner','binding','commands'])test(`service authority refuses missing ${table} and preserves original evidence`,async t=>{const p=await dir(t),file=join(p,'service.sqlite3');let s=new ServiceStore(p,binding);s.accept(command,{command:'stop'});s.close();s=new ServiceStore(p,binding);assert.equal(s.read('original').status,'unknown');assert.equal(s.accept(command,{command:'stop'}).fresh,false);s.close();change(file,'DROP TABLE '+table);const before=await hash(file);assert.throws(()=>new ServiceStore(p,binding),/service_ledger_unconfirmed/);assert.equal(await hash(file),before)});
for(const [kind,table]of [['updates','state'],['updates','preference_revision'],['service','binding']])test(`${kind} refuses missing required ${table} singleton`,async t=>{const p=await dir(t),file=join(p,kind==='updates'?'updates.sqlite3':'service.sqlite3');const s=kind==='updates'?new Store(p,initial):new ServiceStore(p,binding);s.close();change(file,`DELETE FROM ${table} WHERE id=1`);const before=await hash(file);assert.throws(()=>kind==='updates'?new Store(p,initial):new ServiceStore(p,binding),new RegExp(kind+'_ledger_unconfirmed'));assert.equal(await hash(file),before)});
for(const table of ['held','releases'])test(`ingress refuses missing ${table} rather than reopening or reusing a fence`,async t=>{const p=await dir(t),options={directory:join(p,'gate'),id:'ingress'},c={fenceId:'original-fence',commandId:'original-command',purpose:'distribution-update',instanceId:'original-instance',dataScope:'owned-scope'};let gate=await createManualIngressGate(options);const lease=await gate.participant.acquire(c);await lease.release(table==='held'?'unknown':'unchanged',table==='held'?undefined:{kind:'admission-refused'});gate.close();gate=await createManualIngressGate(options);if(table==='held')assert.equal(gate.enter(),null);else await assert.rejects(gate.participant.acquire(c),/reused/);gate.close();const file=join(options.directory,'intake.sqlite3');change(file,'DROP TABLE '+table);const before=await hash(file);await assert.rejects(createManualIngressGate(options),/manual_ingress_ledger_unconfirmed/);assert.equal(await hash(file),before)});
test('existing ingress namespace refuses missing ledger even without sidecars',async t=>{const p=await dir(t),options={directory:join(p,'gate'),id:'ingress'};const gate=await createManualIngressGate(options);gate.close();const authority=await hash(join(options.directory,'authority.json')),key=await hash(join(options.directory,'key'));await unlink(join(options.directory,'intake.sqlite3'));await assert.rejects(createManualIngressGate(options),/manual_ingress_ledger_unconfirmed/);assert.equal(await hash(join(options.directory,'authority.json')),authority);assert.equal(await hash(join(options.directory,'key')),key)});
