import test from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import{mkdtemp,rm,realpath}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{pathToFileURL,fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const dist=process.env.DISTRIBUTION_OWNER_DIRECTORY??fileURLToPath(new URL('../dist',import.meta.url));const{Store}=await import(pathToFileURL(join(dist,'store.js'))),{ServiceStore}=await import(pathToFileURL(join(dist,'service-store.js')));
const initial={schema:1,dataScope:'scope',current:null,previous:null,catalog:null,lastCheck:0,lastCheckSucceeded:false,preferences:{autoCheck:false,autoInstall:false,intervalMs:60000}};
// Source lineage: d9bb3d80 (0.1 core), 515218cd (0.10 notes), cf398db1 (0.16 preferences).
const core='CREATE TABLE owner(id INTEGER PRIMARY KEY,pid INTEGER NOT NULL,token TEXT NOT NULL);CREATE TABLE state(id INTEGER PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE operations(id TEXT PRIMARY KEY,fingerprint TEXT NOT NULL,value TEXT NOT NULL);CREATE TABLE events(id INTEGER PRIMARY KEY AUTOINCREMENT,value TEXT NOT NULL);';
const notes='CREATE TABLE release_notes(id INTEGER PRIMARY KEY,value TEXT NOT NULL,revision TEXT NOT NULL,warning TEXT);CREATE TABLE notice_reviews(digest TEXT PRIMARY KEY,receipt_id TEXT NOT NULL,reviewed_at INTEGER NOT NULL);';
const preferences='CREATE TABLE preference_revision(id INTEGER PRIMARY KEY CHECK(id=1),value TEXT NOT NULL);CREATE TABLE preference_reset_reviews(id TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE preference_reset_commands(id TEXT PRIMARY KEY,fingerprint TEXT NOT NULL,value TEXT NOT NULL);';
async function seed(t,profile){const p=await mkdtemp(join(tmpdir(),'sqlite-lineage-'));t.after(()=>rm(p,{recursive:true,force:true}));const db=new DatabaseSync(join(p,'updates.sqlite3'));db.exec(core+(profile>=1?notes:'')+(profile>=2?preferences:''));db.prepare('INSERT INTO state VALUES(1,?)').run(JSON.stringify(initial));if(profile>=2)db.prepare('INSERT INTO preference_revision VALUES(1,?)').run('original-preference-revision');const op={id:'original',command:'install',args:{target:'inert'},status:'running',phase:'restart',createdAt:1,updatedAt:1,admissionSettlement:{state:'pending',outcome:'unknown'}};db.prepare('INSERT INTO operations VALUES(?,?,?)').run(op.id,createHash('sha256').update(JSON.stringify([op.command,op.args])).digest('hex'),JSON.stringify(op));db.close();return{p,op}}
for(const profile of [0,1,2])test(`complete unmarked historical profile ${profile} migrates atomically and retains unknown request`,async t=>{const{p,op}=await seed(t,profile);const s=new Store(p,initial);assert.equal(s.read('original').status,'unknown');assert.equal(s.read('original').admissionSettlement.state,'unknown');assert.equal(s.accept(op).fresh,false);if(profile===2)assert.equal(s.preferenceRevision(),'original-preference-revision');s.close();const db=new DatabaseSync(join(p,'updates.sqlite3'),{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get().user_version,1);assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").get().n,9);db.close()});
test('live legacy owner refuses migration without partially installing tables or marker',async t=>{const{p}=await seed(t,0);let db=new DatabaseSync(join(p,'updates.sqlite3'));db.prepare('INSERT INTO owner VALUES(1,?,?)').run(process.pid,'live-legacy');db.close();assert.throws(()=>new Store(p,initial),/owner_already_running/);db=new DatabaseSync(join(p,'updates.sqlite3'),{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get().user_version,0);assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE name='release_notes'").get().n,0);db.close()});
test('incomplete historical addon group refuses; standalone service uses its own profile',async t=>{const{p}=await seed(t,1);const db=new DatabaseSync(join(p,'updates.sqlite3'));db.exec('DROP TABLE notice_reviews');db.close();assert.throws(()=>new Store(p,initial),/updates_ledger_unconfirmed/);const service=new ServiceStore(join(p,'separate-service'),{installationId:'fixture',dataScope:'scope',ownerId:'service'});service.close()});
test('unknown profile version or altered column contract refuses',async t=>{for(const fault of ['PRAGMA user_version=99','ALTER TABLE state ADD COLUMN unrecognized TEXT']){const{p}=await seed(t,0);const db=new DatabaseSync(join(p,'updates.sqlite3'));db.exec(fault);db.close();assert.throws(()=>new Store(p,initial),/updates_ledger_unconfirmed/)}});

test('unmarked standalone Service retains its original unknown command during profile migration',async t=>{const p=await mkdtemp(join(tmpdir(),'service-lineage-'));t.after(()=>rm(p,{recursive:true,force:true}));const binding={installationId:'fixture',dataScope:'scope',ownerId:'service'};let s=new ServiceStore(p,binding);s.accept({commandId:'original',command:'stop',status:'running',createdAt:1,updatedAt:1},{command:'stop'});s.close();let db=new DatabaseSync(join(p,'service.sqlite3'));db.exec('PRAGMA user_version=0');db.close();s=new ServiceStore(p,binding);assert.equal(s.read('original').status,'unknown');s.close();db=new DatabaseSync(join(p,'service.sqlite3'),{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get().user_version,1);db.close()});
test('unmarked ingress retains unknown hold while migrating its separate profile',async t=>{const{createManualIngressGate}=await import(pathToFileURL(join(dist,'manual-ingress.js')));const p=await realpath(await mkdtemp(join(tmpdir(),'ingress-lineage-')));t.after(()=>rm(p,{recursive:true,force:true}));const options={directory:join(p,'gate'),id:'ingress'};let gate=await createManualIngressGate(options);const lease=await gate.participant.acquire({fenceId:'original',commandId:'original',purpose:'distribution-update',instanceId:'instance',dataScope:'scope'});await lease.release('unknown');gate.close();let db=new DatabaseSync(join(options.directory,'intake.sqlite3'));db.exec('DROP TABLE admission_attempts; PRAGMA user_version=0');db.close();gate=await createManualIngressGate(options);assert.equal(gate.enter(),null);assert.equal(gate.inspect().held.phase,'unknown');gate.close();db=new DatabaseSync(join(options.directory,'intake.sqlite3'),{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get().user_version,2);db.close()});
