import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
export class Peer{
 constructor(launcher,changed,idle){this.launcher=launcher;this.changed=changed;this.idle=idle;this.pending=new Map();this.next=0;this.calls=0;this.closed=false;}
 signal(fn){try{Promise.resolve(fn?.()).catch(()=>{})}catch{}}
 fail(message){this.closed=true;for(const entry of this.pending.values()){clearTimeout(entry.timer);entry.reject(Error(message))}this.pending.clear();if(this.held)this.held.state='unknown';}
 async start(){if(this.closed)throw Error('Diagnostics owner closed; no replay');if(!this.ready)this.ready=(async()=>{const child=this.child=spawn(this.launcher.command,this.launcher.args??[],{cwd:this.launcher.cwd,env:{...process.env,...this.launcher.env},stdio:'pipe'});child.stderr.on('data',()=>{});child.on('error',()=>this.fail('Diagnostics owner failed to start'));child.on('close',()=>this.fail('Diagnostics owner closed; uncertain sends not replayed'));let bytes=0;child.stdout.on('data',chunk=>{for(const byte of chunk){bytes=byte===10?0:bytes+1;if(bytes>131072){this.fail('Diagnostics frame exceeded128KiB');child.stdout.destroy();child.stdin.end();child.kill();}}});createInterface({input:child.stdout}).on('line',line=>{if(this.closed)return;let row;try{row=JSON.parse(line)}catch{this.fail('Malformed diagnostics frame');return;}if(row.method==='owner/changed'){this.signal(this.changed);return}if(row.method==='owner/idle'){this.signal(this.idle);return}const entry=this.pending.get(row.id);if(!entry)return;this.pending.delete(row.id);clearTimeout(entry.timer);row.error?entry.reject(Error(row.error.message)):entry.resolve(row.result);this.signal(this.idle);});const info=await this.send('initialize',{});if(info.protocolVersion!==1||!info.quiescence?.heldIntake||!info.quiescence?.durableRelease)throw Error('Diagnostics owner lacks required protocol/fence contract')})();return this.ready;}
 send(method,params){if(this.closed||!this.child)throw Error('Diagnostics owner unavailable');if(this.pending.size>=64)throw Error('Diagnostics request capacity reached');const id=++this.next,data=JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n';if(Buffer.byteLength(data)>131072)throw Error('Diagnostics frame exceeds128KiB');return new Promise((resolve,reject)=>{const entry={resolve,reject};entry.timer=setTimeout(()=>{entry.timedOut=true;reject(Error('Diagnostics reply timed out; inspect receipt, never replay'))},30000);entry.timer.unref();this.pending.set(id,entry);this.child.stdin.write(data,error=>{if(error)this.fail('Diagnostics transport lost; uncertain sends not replayed')});});}
 async request(method,args){if(this.held&&!(method==='snapshot'||method==='action'&&args.operation!=='diagnosticss.save'))return {accepted:false,executed:false,reason:'Diagnostics intake held'};this.calls++;try{await this.start();return await this.send(method,args)}finally{this.calls--;this.signal(this.idle)}}
 inspectQuiescence=async()=>{await this.start();return this.send('quiescence/inspect',{})};
 context(value){const result={};for(const key of ['fenceId','commandId','purpose','instanceId','dataScope']){if(typeof value[key]!=='string'||!value[key]||value[key].length>200)throw Error('Bounded exact diagnostics fence required');result[key]=value[key]}return result;}
 acquire=async input=>{const context=this.context(input);if(this.calls||this.pending.size)return null;if(this.held&&(this.held.state!=='held'||JSON.stringify(this.held.context)!==JSON.stringify(context)))throw Error('Diagnostics fence requires explicit reconciliation');this.held={context,state:'checking'};try{await this.start();const result=await this.send('quiescence/acquire',context);if(result.acquired!==true){if(result.executed===false){this.held=undefined;return null}throw Error('Diagnostics intake outcome unknown')}if(result.fenceId!==context.fenceId||result.intakeClosed!==true)throw Error('Exact diagnostics fence not confirmed');this.held.state='held';return {ownerId:'diagnosticss',fenceId:context.fenceId,release:(outcome,proof)=>this.release(context,outcome,proof)}}catch(error){this.held.state='unknown';throw error}};
 release=async(input,outcome,proof)=>{const context=this.context(input);if(this.calls||this.pending.size)throw Error('Diagnostics requests are still in flight');if(this.held&&JSON.stringify(this.held.context)!==JSON.stringify(context))throw Error('Diagnostics fence changed');this.held={context,state:'unknown'};await this.start();const result=await this.send('quiescence/release',{...context,outcome,proof});if(outcome==='unknown')return;if(result.released!==true||result.intakeClosed!==false)throw Error('Diagnostics intake release unconfirmed');this.held=undefined};
 get participant(){return {id:'diagnosticss',acquire:this.acquire,reconcileRelease:input=>this.release(input,input.outcome,input.proof)}}
 async close(){if(!this.child)return;this.child.stdin.end();if(this.child.exitCode===null&&this.child.signalCode===null)await new Promise(resolve=>this.child.once('close',resolve));}
}
