import {spawnSync} from 'node:child_process';import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {mkdtemp,mkdir,rm,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
const kind='history',moduleUrl=new URL(process.env['HISTORY_MODULE']||'../src/index.js',import.meta.url),ownerModule=await import(moduleUrl),{['HistoryQuiescence']:Gate}=await import(new URL('./quiescence.js',moduleUrl));
const c=(id='original')=>({fenceId:'fence-'+id,commandId:'command-'+id,purpose:'distribution-update',instanceId:'original-instance',dataScope:'owned-fixture'});
const proof=context=>({...context,kind:'distribution-admission-abort',verified:true,receiptId:'authenticated-supervisor-abort'}),request=context=>({...context,proof:proof(context)});
const file=kind==='history'?'history-quiescence.sqlite':'worktree-quiescence.sqlite';
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),kind+'-admission-abort-'));let gate=new Gate(dir);t.after(async()=>{gate.close();await rm(dir,{recursive:true,force:true})});return {dir,get gate(){return gate},get p(){return gate.participant('fixture-owner')},restart(){gate.close();gate=new Gate(dir)},replace(fn){gate.close();fn(join(dir,file));gate=new Gate(dir)}}}
function dbEdit(path,fn){const db=new DatabaseSync(path);try{return fn(db)}finally{db.close()}}
const released=c=>({verified:true,...c,outcome:'unchanged',receiptId:'old-exact-release'});
test('acquired attempt aborts after restart, original hold receipt stays intact and exact lost reply is passive',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);f.restart();assert.equal(f.gate.current().state,'unknown');const original=f.gate.db.prepare('SELECT value FROM receipts WHERE id=?').get(ctx.fenceId).value;const result=await f.p.abortAdmission(request(ctx));assert.equal(result.status,'released');assert.equal(f.gate.inspect().intakeClosed,false);assert.equal(f.gate.db.prepare('SELECT value FROM receipts WHERE id=?').get(ctx.fenceId).value,original);assert.deepEqual(Object.keys(result).sort(),['ownerId','fenceId','commandId','instanceId','dataScope','status','receiptId'].sort());f.restart();assert.deepEqual(await f.p.abortAdmission(request(ctx)),result);await assert.rejects(f.p.acquire(ctx),/already_settled/);await assert.rejects(f.p.reconcileRelease({...ctx,outcome:'unchanged',proof:released(ctx)}),/already_settled/);});
test('durable busy refusal cannot abort active work, then returns original not-acquired across restart',async t=>{const f=await fixture(t),ctx=c();let finish;const work=f.gate.effect(()=>new Promise(r=>finish=r));assert.equal(await f.p.acquire(ctx),null);await assert.rejects(f.p.abortAdmission(request(ctx)),/work_active/);finish();await work;f.restart();const result=await f.p.abortAdmission(request(ctx));assert.equal(result.status,'not-acquired');f.restart();assert.deepEqual(await f.p.abortAdmission(request(ctx)),result)});
test('unchanged partial-acquire unwind retains acquisition evidence; generic release proof is not abort authority',async t=>{const f=await fixture(t),ctx=c();const lease=await f.p.acquire(ctx);await lease.release('unchanged',{kind:'admission-refused'});await assert.rejects(f.p.abortAdmission({...ctx,proof:released(ctx)}),/proof_unconfirmed/);f.restart();assert.equal((await f.p.abortAdmission(request(ctx))).status,'released')});
test('proof and original binding changes refuse before clearing the hold; completed proof cannot change',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);for(const field of ['commandId','fenceId','instanceId','dataScope']){await assert.rejects(f.p.abortAdmission({...request(ctx),[field]:'changed'}));await assert.rejects(f.p.abortAdmission({...ctx,proof:{...proof(ctx),[field]:'changed'}}));assert.equal(f.gate.inspect().intakeClosed,true)}for(const patch of [{kind:'admission-refused'},{verified:1},{purpose:'recovery'},{extra:true}]){await assert.rejects(f.p.abortAdmission({...ctx,proof:{...proof(ctx),...patch}}));assert.equal(f.gate.inspect().intakeClosed,true)}const result=await f.p.abortAdmission(request(ctx));await assert.rejects(f.p.abortAdmission({...ctx,proof:{...proof(ctx),receiptId:'different-proof'}}),/proof_changed/);assert.deepEqual(await f.p.abortAdmission(request(ctx)),result)});
test('foreign hold is never cleared by original not-acquired evidence',async t=>{const f=await fixture(t),ctx=c(),foreign=c('foreign');let finish;const work=f.gate.effect(()=>new Promise(r=>finish=r));assert.equal(await f.p.acquire(ctx),null);finish();await work;await f.p.acquire(foreign);await assert.rejects(f.p.abortAdmission(request(ctx)),/hold_unconfirmed/);assert.equal(f.gate.current().fenceId,foreign.fenceId)});
for(const held of [false,true])test('legacy missing attempt remains unknown, held='+held,async t=>{const f=await fixture(t),ctx=c();if(held)await f.p.acquire(ctx);f.replace(path=>dbEdit(path,db=>db.exec('DROP TABLE admission_attempts;PRAGMA user_version=1')));await assert.rejects(f.p.abortAdmission(request(ctx)),/attempt_unconfirmed/);assert.equal(f.gate.inspect().intakeClosed,held);assert.equal(f.gate.db.prepare('SELECT count(*) n FROM admission_attempts').get().n,0)});
test('abort receipt and matching hold removal roll back together on failure',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);f.gate.db.exec("CREATE TRIGGER refuse_clear BEFORE DELETE ON fence BEGIN SELECT RAISE(ABORT,'fixture-clear-failed');END");await assert.rejects(f.p.abortAdmission(request(ctx)),/fixture-clear-failed/);assert.equal(f.gate.inspect().intakeClosed,true);assert.equal(JSON.parse(f.gate.db.prepare('SELECT body FROM admission_attempts').get().body).receipt,undefined);f.gate.db.exec('DROP TRIGGER refuse_clear');assert.equal((await f.p.abortAdmission(request(ctx))).status,'released')});
test('v2 loss of admission authority refuses before writable recovery',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);f.gate.close();const path=join(f.dir,file);dbEdit(path,db=>db.exec('DROP TABLE admission_attempts'));const before=await readFile(path);assert.throws(()=>new Gate(f.dir),/authority schema/);assert.deepEqual(await readFile(path),before)});
test('retained pending business work refuses abort without changing its receipt',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);f.gate.pendingWork=()=>true;await assert.rejects(f.p.abortAdmission(request(ctx)),/work_active/);assert.equal(f.gate.inspect().intakeClosed,true);f.gate.pendingWork=()=>false;assert.equal((await f.p.abortAdmission(request(ctx))).status,'released')});
if(kind==='worktree'){
 test('checking without confirmed worker exclusion never becomes acquired evidence',async t=>{const f=await fixture(t),ctx=c();f.gate.save({...ctx,ownerId:'fixture-owner',state:'checking'},'attempting');f.restart();await assert.rejects(f.p.abortAdmission(request(ctx)),/hold_unconfirmed/);assert.equal(f.gate.inspect().intakeClosed,true)});
 test('restarted worker lease and durable worker reservation both block abort',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);f.restart();const lock=new DatabaseSync(join(f.dir,'worktree-worker-lock.sqlite'));try{lock.exec('BEGIN EXCLUSIVE');await assert.rejects(f.p.abortAdmission(request(ctx)),/exclusion_unconfirmed/);assert.equal(f.gate.inspect().intakeClosed,true);lock.exec('ROLLBACK');f.gate.workers.prepare('INSERT INTO workers VALUES(?,?)').run('existing-worker','pending');await assert.rejects(f.p.abortAdmission(request(ctx)),/work_active/);f.gate.workers.prepare('DELETE FROM workers WHERE id=?').run('existing-worker');assert.equal((await f.p.abortAdmission(request(ctx))).status,'released')}finally{lock.close()}});
 test('worker lock busy acquisition retains definitive not-acquired record',async t=>{const f=await fixture(t),ctx=c();const lock=new DatabaseSync(join(f.dir,'worktree-worker-lock.sqlite'));try{lock.exec('BEGIN EXCLUSIVE');assert.equal(await f.p.acquire(ctx),null);assert.equal(f.gate.inspect().intakeClosed,false);await assert.rejects(f.p.abortAdmission(request(ctx)),/exclusion_unconfirmed/);lock.exec('ROLLBACK');f.restart();assert.equal((await f.p.abortAdmission(request(ctx))).status,'not-acquired')}finally{lock.close()}});
}
test('actual public owner preserves original unknown command and never replays it after abort',async t=>{
 const dir=await mkdtemp(join(tmpdir(),kind+'-public-abort-')),workspace=join(dir,'workspace');await mkdir(workspace);let calls=0;
 const options=kind==='history'?{directory:dir,engineId:'fixture',authorizeWorkspace:async p=>p,nativeAdmin:async(operation,args)=>{calls++;return {commandId:args.commandId,operation,status:'unknown',replayed:false}},adoptImportedSession:async()=>{throw Error('forbidden')},importAdoptionReceipt:async()=>null}:{directory:dir,inspectSession:async session=>({session,workingDirectory:workspace,executionDirectory:workspace,historyHome:workspace,executionRevision:0}),relocateSession:async()=>{calls++;throw Error('retained unconfirmed outcome')},gitWorker:{quiescenceCoverage:1,request:async()=>({repository:'fixture'}),close:async()=>{}}};
 const factory=()=>kind==='history'?ownerModule.createHistoryCapability(options):ownerModule.createWorktreeCapability(options);let owner=factory();t.after(async()=>{await owner.close();await rm(dir,{recursive:true,force:true})});
 const action=()=>owner.action({version:1,topic:kind==='history'?'history-import':'worktrees',channel:kind==='history'?'ahp-root://':'ahp-session:/fixture',operation:kind==='history'?'history.import.begin':'worktree.handoff',commandId:'original-business-command',args:kind==='history'?{workingDirectory:workspace,format:'json',bytes:2,sha256:createHash('sha256').update('[]').digest('hex')}:{id:null,expectedExecutionRevision:0}},{origin:'ui'});
 await action();await owner.idle?.();assert.equal(calls,1);
 const participant=()=>kind==='history'?owner.quiescenceParticipant:owner.quiescenceParticipant(),ctx=c(),path=join(dir,kind==='history'?'history-import.sqlite':'worktrees.sqlite');
 const commands=()=>{const db=new DatabaseSync(path,{readOnly:true});try{return db.prepare('SELECT * FROM commands').all()}finally{db.close()}};const original=commands();assert.equal(original.length,1);assert.equal(kind==='history'?original[0].status:original[0].phase,'unknown');
 await participant().acquire(ctx);await owner.close();owner=factory();assert.equal((await participant().abortAdmission(request(ctx))).status,'released');assert.deepEqual(commands(),original);await action();await owner.idle?.();assert.deepEqual(commands(),original);assert.equal(calls,1);
});

test('missing version2 journal in crash-left WAL refuses without changing main or WAL',async t=>{const f=await fixture(t),ctx=c();await f.p.acquire(ctx);f.gate.close();const path=join(f.dir,file),code="import {DatabaseSync} from 'node:sqlite';const db=new DatabaseSync(process.argv[1]);db.exec('PRAGMA journal_mode=WAL;PRAGMA wal_autocheckpoint=0;DROP TABLE admission_attempts');process.exit(0)";const child=spawnSync(process.execPath,['--input-type=module','-e',code,path],{encoding:'utf8'});assert.equal(child.status,0,child.stderr);const before=[await readFile(path),await readFile(path+'-wal')];assert.ok(before[1].length);assert.throws(()=>new Gate(f.dir),/authority schema/);assert.deepEqual(await readFile(path),before[0]);assert.deepEqual(await readFile(path+'-wal'),before[1])});
