import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {mkdtemp,mkdir,readFile,writeFile,rm,unlink,access} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
const kind='history',module=await import(process.env.HISTORY_MODULE||'../src/index.js');
const session='ahp-session:/startup-fixture',commandId='original-command',sha=x=>createHash('sha256').update(x).digest('hex');
const main=kind==='history'?'history-import.sqlite':'worktrees.sqlite',gate=kind==='history'?'history-quiescence.sqlite':'worktree-quiescence.sqlite';
const binding={fenceId:'original-fence',commandId:'fence-command',purpose:'distribution-update',instanceId:'original-instance',dataScope:'owned-fixture'};
async function fixture(t){const directory=await mkdtemp(join(tmpdir(),kind+'-startup-')),workspace=join(directory,'workspace');await mkdir(workspace);let calls=0,owner;
 const factory=()=>kind==='history'?module.createHistoryCapability({directory,engineId:'fixture',authorizeWorkspace:async p=>{assert.equal(p,workspace);return p},nativeAdmin:async(operation,args)=>{if(operation==='history.import.receipt')return null;assert.equal(operation,'history.import.begin');calls++;return {commandId:args.commandId,operation,status:'unknown',replayed:false}},adoptImportedSession:async()=>{throw Error('forbidden native adoption')},importAdoptionReceipt:async()=>{throw Error('forbidden native adoption')}}):module.createWorktreeCapability({directory,inspectSession:async s=>({session:s,workingDirectory:workspace,historyHome:workspace,executionDirectory:workspace,executionRevision:0}),relocateSession:async()=>{calls++;throw Error('inert unconfirmed boundary')},gitWorker:{quiescenceCoverage:1,request:async operation=>{assert.equal(operation,'inspect');return {repository:'fixture'}},close:async()=>{}}});
 const args=kind==='history'?{workingDirectory:workspace,format:'json',bytes:2,sha256:sha('[]')}:{id:null,expectedExecutionRevision:0};
 const action=(operation,input=args,id=commandId)=>owner.action({version:1,topic:kind==='history'?'history-import':'worktrees',channel:kind==='history'?'ahp-root://':session,operation,args:input,commandId:id},{origin:'ui'});
 t.after(async()=>{await owner?.close();await rm(directory,{recursive:true,force:true})});
 return {directory,workspace,factory,args,action,get owner(){return owner},set owner(v){owner=v},get calls(){return calls},async open(){owner=factory();return owner},async close(){await owner.close();owner=undefined},async original(){await action(kind==='history'?'history.import.begin':'worktree.handoff');await owner.idle?.();assert.equal(calls,1)}};
}
function readonly(path){const db=new DatabaseSync(path,{readOnly:true});try{return {version:Number(db.prepare('PRAGMA user_version').get().user_version),tables:db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(x=>x.name)}}finally{db.close()}}
async function bytes(path){const out={};for(const suffix of ['','-wal','-journal']){try{out[suffix]=sha(await readFile(path+suffix))}catch(e){if(e.code!=='ENOENT')throw e}}return out}
async function drop(path,table){assert.ok(readonly(path).tables.includes(table));const db=new DatabaseSync(path);try{db.exec('DROP TABLE '+table)}finally{db.close()}assert.ok(!readonly(path).tables.includes(table))}
test('new store and healthy restart preserve exact unknown command once',async t=>{const f=await fixture(t);await f.open();await f.original();await f.close();readonly(join(f.directory,main));await f.open();await f.action(kind==='history'?'history.import.begin':'worktree.handoff');await f.owner.idle?.();assert.equal(f.calls,1);if(kind==='history')assert.equal((await f.action('history.import.receipt',{commandId})).result.status,'unknown');else{assert.ok(f.owner.store.reserved(f.workspace));assert.ok(f.owner.store.unresolved(session))}});
for(const table of kind==='history'?['commands','workflows','revision']:['commands','records','topics'])test('existing main missing '+table+' refuses before writable open',async t=>{const f=await fixture(t);await f.open();await f.original();await f.close();const path=join(f.directory,main);await drop(path,table);const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash);assert.equal(f.calls,1);assert.throws(f.factory,/authority schema|unavailable/);});
for(const table of ['fence','receipts'])test('held existing gate missing '+table+' never opens intake',async t=>{const f=await fixture(t);await f.open();const participant=kind==='history'?f.owner.quiescenceParticipant:f.owner.quiescenceParticipant();await participant.acquire(binding);await f.close();await f.open();assert.equal((await f.owner.inspectQuiescence()).intakeClosed,true);await f.close();const path=join(f.directory,gate);await drop(path,table);const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash);assert.equal(f.calls,0)});
if(kind==='worktree')test('existing worker registry missing workers cannot look idle',async t=>{const f=await fixture(t);await f.open();await f.close();const path=join(f.directory,'worktree-workers.sqlite');await drop(path,'workers');const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash)});
for(const file of kind==='history'?[main,gate]:[main,gate,'worktree-workers.sqlite'])for(const suffix of ['-wal','-shm','-journal'])test('absent '+file+' with empty '+suffix+' evidence refuses fresh initialization',async t=>{const f=await fixture(t),path=join(f.directory,file);await writeFile(path+suffix,'');assert.throws(f.factory,/authority schema|unavailable/);await assert.rejects(access(path),{code:'ENOENT'});assert.equal((await readFile(path+suffix)).length,0)});
test('versioned profile refuses absent gate authority',async t=>{const f=await fixture(t);await f.open();await f.close();assert.equal(readonly(join(f.directory,main)).version,1);await unlink(join(f.directory,gate));assert.throws(f.factory,/authority schema|unavailable/)});
test('future schema version refuses without rewriting the store',async t=>{const f=await fixture(t);await f.open();await f.close();const path=join(f.directory,main);readonly(path);const db=new DatabaseSync(path);db.exec('PRAGMA user_version=2');db.close();const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash)});
test('known unversioned predecessor layout remains a valid profile upgrade',async t=>{const f=await fixture(t);await f.open();await f.original();await f.close();const path=join(f.directory,main);readonly(path);const db=new DatabaseSync(path);db.exec('PRAGMA user_version=0');db.close();if(kind==='worktree'){await unlink(join(f.directory,gate));await unlink(join(f.directory,'worktree-workers.sqlite'))}readonly(path);await f.open();await f.action(kind==='history'?'history.import.begin':'worktree.handoff');await f.owner.idle?.();assert.equal(f.calls,1);assert.equal(readonly(path).version,1)});
test('damaged committed WAL remains intact after refused reopen',async t=>{const f=await fixture(t);await f.open();await f.original();await f.close();const path=join(f.directory,main);readonly(path);const code="import {DatabaseSync} from 'node:sqlite';const db=new DatabaseSync(process.argv[1]);db.exec('PRAGMA journal_mode=WAL;PRAGMA wal_autocheckpoint=0;DROP TABLE commands');process.exit(0)";
 const child=spawnSync(process.execPath,['--input-type=module','-e',code,path],{encoding:'utf8'});assert.equal(child.status,0,child.stderr);const wal=await readFile(path+'-wal');assert.ok(wal.length>0);assert.ok(!readonly(path).tables.includes('commands'));const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash);assert.equal(f.calls,1)});

test('unversioned profile does not excuse missing paired authority',async t=>{const f=await fixture(t);await f.open();await f.close();const path=join(f.directory,main);readonly(path);const db=new DatabaseSync(path);db.exec('PRAGMA user_version=0');db.close();await unlink(join(f.directory,gate));assert.throws(f.factory,/authority schema|unavailable/)});

test('incompatible required command column refuses unchanged authority',async t=>{const f=await fixture(t);await f.open();await f.original();await f.close();const path=join(f.directory,main);readonly(path);const db=new DatabaseSync(path);db.exec('ALTER TABLE commands RENAME COLUMN signature TO lost_signature');db.close();const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash);assert.equal(f.calls,1)});
for(const statement of ['DELETE FROM revision','UPDATE revision SET value=-1'])test('invalid bounded revision singleton refuses: '+statement,async t=>{const f=await fixture(t);await f.open();await f.close();const path=join(f.directory,main);readonly(path);const db=new DatabaseSync(path);db.exec(statement);db.close();const before=await bytes(path);assert.throws(f.factory,/authority schema|unavailable/);for(const [suffix,hash] of Object.entries(before))assert.equal((await bytes(path))[suffix],hash);assert.equal(f.calls,0)});
