import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,chmod,rm,access} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import {createInterface} from 'node:readline';import {fileURLToPath} from 'node:url';
import {createWorktreeCapability} from '../src/index.js';
const python=process.env.WORKTREE_PYTHON||fileURLToPath(new URL('../.venv/bin/python',import.meta.url)),session='ahp-session:/gate';
const c=id=>({fenceId:id,commandId:'command-'+id,purpose:'recovery',instanceId:'original-host',dataScope:'owned-worktrees'}),proof=context=>({verified:true,...context,outcome:'unchanged',receiptId:'private-evidence'}),pause=()=>{let release;const promise=new Promise(r=>release=r);return {promise,release}};
async function until(fn){for(let n=0;n<1000;n++){if(await fn())return;await new Promise(r=>setTimeout(r,10))}throw Error('Fixture condition did not settle');}
async function fixture(options={}){const root=await mkdtemp(join(tmpdir(),'worktree-quiescence-')),directory=join(root,'owner'),source=join(root,'source');await mkdir(source);const git=(...args)=>execFileSync('git',['-c','core.hooksPath=/dev/null','-C',source,...args],{encoding:'utf8'});git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');await writeFile(join(source,'file'),'retained');git('add','.');git('commit','-qm','fixture');const config={directory,python,inspectSession:async id=>({session:id,historyHome:source,executionDirectory:source,workingDirectory:source,executionRevision:0}),...options};const owner=createWorktreeCapability(config);return {root,directory,source,config,owner,action:(op,args={})=>owner.action({channel:session,topic:'worktrees',operation:op,version:1,args,commandId:crypto.randomUUID()},{origin:'ui'}),close:async()=>{await owner.close();await rm(root,{recursive:true,force:true})}};}

test('returned handoff keeps real owner busy until native relocation settles; held fence leaves metadata receipts readable',async()=>{
 const entered=pause(),finish=pause();let notices=0;const f=await fixture({onMayBeIdle:()=>{notices++},relocateSession:async(_uri,args)=>{entered.release();await finish.promise;return {applied:true,executionDirectory:args.target,executionRevision:1,receipt:'native-receipt'}}});
 try{const pending=await f.action('worktree.handoff',{id:null,expectedExecutionRevision:0});assert.equal(pending.result.phase,'pending');await entered.promise;assert.equal(await f.owner.quiescenceParticipant().acquire(c('during-handoff')),null);finish.release();await f.owner.idle();await new Promise(r=>setTimeout(r,10));assert.ok(notices>0);
 const context=c('settled'),lease=await f.owner.quiescenceParticipant().acquire(context);assert.ok(lease);await assert.rejects(f.action('worktree.status',{id:pending.result.id}),/intake closed/);await assert.rejects(f.action('worktree.inspect'),/intake closed/);const rows=await f.action('worktree.list',{collection:'handoffs'});assert.equal(rows.result.items[0].phase,'applied');assert.equal((await f.owner.read({uri:'amplifier-capability://worktrees',scope:session})).topic,'worktrees');assert.throws(()=>createWorktreeCapability(f.config),/already has an owner/);await lease.release('unchanged',proof(context));
 }finally{finish.release();await f.close()}
});

test('held intake survives owner restart and never restarts Git merely to reconcile',async()=>{
 const f=await fixture();let owner=f.owner;try{const context=c('restart');await owner.quiescenceParticipant().acquire(context);await owner.close();owner=createWorktreeCapability(f.config);assert.equal(owner.inspectQuiescence().fence.state,'unknown');assert.equal(owner.inspectQuiescence().workerLifetimes,0);await assert.rejects(owner.quiescenceParticipant().acquire(context),/reconciliation/);await assert.rejects(owner.quiescenceParticipant().reconcileRelease({...context,outcome:'unchanged',proof:{...proof(context),commandId:'wrong'}}),/proof/);await owner.quiescenceParticipant().reconcileRelease({...context,outcome:'unchanged',proof:proof(context)});assert.equal(owner.inspectQuiescence().intakeClosed,false);}finally{await owner.close();await rm(f.root,{recursive:true,force:true})}
});

async function orphanFixture({killWorker=false}={}){
 const f=await fixture();await f.owner.close();const entered=join(f.root,'entered'),release=join(f.root,'release'),wrapper=join(f.root,'python-wrapper');
 await writeFile(wrapper,`#!${python}\nimport os,time,pathlib\nfrom amplifier_unified_worktrees import worker\noriginal=worker.run\ndef paused(request):\n pathlib.Path(${JSON.stringify(entered)}).write_text(str(os.getpid()))\n while not pathlib.Path(${JSON.stringify(release)}).exists():time.sleep(.01)\n return original(request)\nworker.run=paused\nworker.main()\n`);await chmod(wrapper,0o700);
 const module=new URL('../src/index.js',import.meta.url).href,script=`import {createWorktreeCapability} from ${JSON.stringify(module)};const owner=createWorktreeCapability({directory:process.argv[1],python:process.argv[3],inspectSession:async session=>({session,historyHome:process.argv[2],workingDirectory:process.argv[2],executionDirectory:process.argv[2]})});console.log('owned');await owner.action({channel:${JSON.stringify(session)},topic:'worktrees',version:1,operation:'worktree.inspect',args:{},commandId:'inspect'});await owner.close();`;
 const child=spawn(process.execPath,['--input-type=module','-e',script,f.directory,f.source,wrapper],{stdio:['ignore','pipe','pipe']});child.stderr.resume();const lines=createInterface({input:child.stdout});let owner,pid,notices=0;
 try{assert.equal((await once(lines,'line'))[0],'owned');await until(async()=>{try{pid=Number(await readFile(entered,'utf8'));return pid>0}catch{return false}});child.kill('SIGKILL');await once(child,'exit');lines.close();owner=createWorktreeCapability({...f.config,onMayBeIdle:()=>{notices++}});assert.equal(owner.inspectQuiescence().workerLifetimes,1);assert.equal(await owner.quiescenceParticipant().acquire(c('orphan-active')),null);
 if(killWorker){process.kill(pid,'SIGKILL');assert.equal(await owner.quiescenceParticipant().acquire(c('unexpected-worker-death')),null);assert.equal(owner.inspectQuiescence().workerLifetimes,1);}
 else{await writeFile(release,'continue exact existing work');await until(()=>owner.inspectQuiescence().workerLifetimes===0);await until(()=>notices>0);assert.ok(await owner.quiescenceParticipant().acquire(c('orphan-settled')));}
 }finally{await writeFile(release,'release');if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await once(child,'exit')}lines.close();if(pid){try{process.kill(pid,'SIGKILL')}catch{}}await owner?.close();await rm(f.root,{recursive:true,force:true})}
}
test('parent SIGKILL leaves actual worker counted; its own confirmed completion permits quiescence without replay',{timeout:20000},()=>orphanFixture());
test('unexpected worker death retains separate lifetime uncertainty instead of false idle',{timeout:20000},()=>orphanFixture({killWorker:true}));

test('a proven spawn failure releases only its worker lifetime reservation',async()=>{
 const f=await fixture({python:'/unavailable-owned-fixture-python'});try{await assert.rejects(f.action('worktree.inspect'),error=>error.executed===false);assert.equal(f.owner.inspectQuiescence().workerLifetimes,0);assert.ok(await f.owner.quiescenceParticipant().acquire(c('no-process')))}finally{await f.close()}
});
