import test from 'node:test';
import assert from 'node:assert/strict';
import React,{act as renderAct} from 'react';
import {create} from 'react-test-renderer';
import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom',optimizeDeps:{noDiscovery:true,include:[]}});
const {ChatPages}=await server.ssrLoadModule('/src/chat-pages.jsx');
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
test.after(()=>server.close());
test('chat info discards old locations and errors immediately and ignores late inspections',async()=>{
 const pending=new Map();
 const act=(name,args)=>name==='session.inspect'?new Promise((resolve,reject)=>pending.set(args.id,{resolve,reject})):Promise.resolve({accepted:true});
 const render=id=>React.createElement(ChatPages,{page:'session-details',state:{view:{}},session:{id,status:'idle',workspace:`/workspace/${id}`},act,open:()=>{}});
 let root;await renderAct(async()=>{root=create(render('a'))});
 await renderAct(async()=>pending.get('a').resolve({result:{historyDirectory:'/history/a',executionDirectory:'/execution/a'}}));
 assert.match(JSON.stringify(root.toJSON()),/\/history\/a/);
 await renderAct(async()=>root.update(render('b')));
 assert.doesNotMatch(JSON.stringify(root.toJSON()),/\/history\/a|\/execution\/a/);
 await renderAct(async()=>pending.get('b').reject(Error('B inspection failed')));
 assert.match(JSON.stringify(root.toJSON()),/B inspection failed/);
 await renderAct(async()=>root.update(render('c')));
 assert.doesNotMatch(JSON.stringify(root.toJSON()),/B inspection failed/);
 await renderAct(async()=>root.update(render('d')));
 await renderAct(async()=>pending.get('c').resolve({result:{historyDirectory:'/history/c'}}));
 assert.doesNotMatch(JSON.stringify(root.toJSON()),/\/history\/c/);
 await renderAct(async()=>pending.get('d').resolve({result:{historyDirectory:'/history/d'}}));
 assert.match(JSON.stringify(root.toJSON()),/\/history\/d/);
 await renderAct(async()=>root.unmount());
});
