import {openSettingsPage} from './browser-settings.mjs';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';

const origin='http://127.0.0.1:8989', headers={Authorization:'Bearer fixture-browser-control-token'};
const fixture=spawn(fileURLToPath(new URL('../../.venv/bin/python',import.meta.url)),[fileURLToPath(new URL('../../tests/fixtures/connectors_ui_server.py',import.meta.url))],{stdio:['ignore','ignore','pipe']});
let fixtureError='';fixture.stderr.on('data',chunk=>{fixtureError+=chunk.toString()});
let browser;
try {
  let started=false;
  for(let i=0;i<150;i++){try{if((await fetch(origin+'/api/health')).ok){started=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}
  assert.ok(started,fixtureError.slice(-1500));
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1350,height:950},extraHTTPHeaders:headers});
  const page=await context.newPage(), errors=[];page.on('pageerror',error=>errors.push(error.message));
  const info=()=>fetch(origin+'/fixture/info',{headers}).then(r=>r.json());
  await page.goto(origin);await page.waitForSelector('#amp-one');
  const state=()=>page.evaluate(()=>window.amplifier.getState());
  const action=(name,args)=>page.evaluate(([name,args])=>window.amplifier.dispatch(name,args),[name,args]);
  await action('view.update',{patch:{draft:'Unsent draft stays here'}});
  const selected=(await state()).selectedSessionId;
  await openSettingsPage(page,'smart-tools');
  await page.getByRole('button',{name:'Add MCP connection',exact:true}).click();
  await page.getByLabel('Display name',{exact:true}).fill('Local authorization fixture');
  await page.getByLabel('Connection type',{exact:true}).selectOption('streamable-http');
  await page.getByLabel('MCP endpoint',{exact:true}).fill((await info()).endpoint);
  await page.getByLabel('Authorization',{exact:true}).selectOption('oauth');
  await page.getByRole('button',{name:'Save connection',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers.length===1);
  assert.equal((await info()).registrations,0);
  assert.equal((await state()).smartTools.servers[0].connectionState,'disconnected');
  await page.getByRole('button',{name:'View connections',exact:true}).click();
  await page.getByRole('button',{name:/Local authorization fixture.*disconnected/}).click();
  await page.getByRole('button',{name:'Connect',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].connectionState==='auth-required');
  assert.equal((await info()).registrations,0,'Connect must not start interactive authorization');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  const authorize=page.getByRole('link',{name:'Review access and authorize',exact:true});
  await authorize.waitFor();
  const popupPromise=context.waitForEvent('page');await authorize.click();const consent=await popupPromise;
  await consent.getByRole('button',{name:'Approve fixture access',exact:true}).click();
  await consent.getByText('Authorization response received.',{exact:false}).waitFor();
  assert.equal(new URL(consent.url()).pathname,'/oauth/mcp/complete');assert.equal(new URL(consent.url()).search,'');
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].connectionState==='ready');
  await expect(page.getByText(/Account identity: Unknown/)).toBeVisible();
  await expect(page.getByText(/Granted access: records:read/)).toBeVisible();
  let server=(await state()).smartTools.servers[0];
  assert.ok(server.tools.every(t=>!t.inputSchema));assert.deepEqual(server.loadedSchemas,{});
  await page.getByRole('button',{name:/Read Record.*Read one fixture record/i}).click();
  await page.getByLabel('Key',{exact:false}).fill('browser-first');
  await page.getByRole('button',{name:'Run tool',exact:true}).click();
  await page.getByText('"key": "browser-first"',{exact:false}).waitFor();
  assert.equal((await info()).calls,1);
  server=(await state()).smartTools.servers[0];
  assert.deepEqual(Object.keys(server.loadedSchemas),['read_record']);
  const agent=async(action,args)=>{const response=await fetch(origin+'/fixture/agent',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({action,args})});assert.ok(response.ok);return response.json()};
  await agent('smartTools.discover',{id:server.id,query:'record'});
  await agent('smartTools.schemas',{id:server.id,names:['read_record'],catalogRevision:server.catalogRevision});
  await agent('smartTools.call',{id:server.id,name:'read_record',arguments:{key:'agent-second'},catalogRevision:server.catalogRevision});
  assert.equal((await info()).calls,2);
  await agent('smartTools.call',{id:server.id,name:'change_tools',arguments:{},catalogRevision:server.catalogRevision});
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].catalogState==='stale');
  await expect(page.getByRole('button',{name:'Run tool',exact:true})).toHaveCount(0);
  await agent('smartTools.call',{id:server.id,name:'read_record',arguments:{key:'stale-must-not-run'},catalogRevision:server.catalogRevision});
  assert.equal((await info()).calls,2);
  await page.getByRole('button',{name:'Back to Local authorization fixture',exact:true}).click();
  await page.getByRole('button',{name:'Refresh tool definitions',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].catalogState==='current');
  await page.getByRole('button',{name:'Disconnect',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].connectionState==='disconnected');
  await page.getByRole('button',{name:'Reconnect',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].connectionState==='ready');
  assert.equal((await info()).exchanges,1,'Reconnect must reuse the authorized account without new consent or replay');
  await page.reload();await page.waitForSelector('#amp-one');
  assert.equal((await state()).selectedSessionId,selected);
  assert.equal((await state()).view.draft,'Unsent draft stays here');
  assert.equal((await info()).calls,2);
  const artifacts=process.env.CONNECTOR_ARTIFACT_DIR;
  if(artifacts){await mkdir(artifacts,{recursive:true});await page.screenshot({path:artifacts+'/connector-lifecycle-desktop.png',fullPage:true});}
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  if(artifacts){await page.locator('.a-smart-source-summary').scrollIntoViewIfNeeded();await page.screenshot({path:artifacts+'/connector-lifecycle-mobile.png',fullPage:true});}
  await page.getByRole('button',{name:'Forget local sign-in',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].authorization.consent==='unknown');
  await agent('smartTools.authStart',{id:server.id,redirectOrigin:origin});await authorize.waitFor();
  await agent('smartTools.authStatus',{id:server.id});
  await page.getByRole('button',{name:'Cancel sign-in',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.servers[0].login.phase==='cancelled');
  assert.equal((await info()).exchanges,1);
  await fetch(origin+'/fixture/package',{method:'POST',headers});
  await page.getByRole('button',{name:'Back to Smart Tools',exact:true}).click();
  await page.getByRole('button',{name:/Fixture package.*installed/}).click();
  await page.getByRole('button',{name:'Uninstall package',exact:true}).click();
  await page.getByText(/Remove these connection registrations before uninstalling:/,{exact:false}).first().waitFor();
  assert.equal((await info()).packageExists,true);
  await page.getByRole('button',{name:'Back to Smart Tools',exact:true}).click();
  await page.getByRole('button',{name:/Package dependency.*disconnected/}).click();
  await page.getByRole('button',{name:'Remove connection',exact:true}).click();
  await page.getByRole('button',{name:/Fixture package.*installed/}).click();
  await page.getByRole('button',{name:'Uninstall package',exact:true}).click();
  await page.waitForFunction(()=>window.amplifier.getState().smartTools.installations.length===0);
  assert.equal((await info()).packageExists,false);
  assert.equal((await info()).externalWorkExists,true);
  assert.deepEqual(errors,[]);
  const evidence={passed:true,realMcpAndOAuth:true,realAccounts:false,userAndAgentCalls:2,consentExchanges:1,agentSignInUserCancel:true,staleCallRejected:true,configureInert:true,reloadNoReplay:true,draftAndSelectionPreserved:true,mobileOverflow:false,uninstallDependencyGuard:true,uninstallExternalWorkPreserved:true};
  if(artifacts)await writeFile(artifacts+'/connector-lifecycle-browser.json',JSON.stringify(evidence,null,2)+'\n');
  console.log(JSON.stringify(evidence));
} finally {await browser?.close();fixture.kill('SIGTERM');}
