import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
const fixture=spawn(fileURLToPath(new URL('../../.venv/bin/python',import.meta.url)),[fileURLToPath(new URL('../../tests/fixtures/operations_ui_server.py',import.meta.url))],{stdio:['ignore','pipe','inherit']});
let browser;
try{
 const ready=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Fixture timeout')),20000);fixture.stdout.on('data',chunk=>{output+=chunk;for(const line of output.split('\n'))try{const value=JSON.parse(line);if(value.url){clearTimeout(timer);resolve(value)}}catch{}});fixture.once('exit',code=>reject(Error('Fixture exit '+code)))});
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{Authorization:'Bearer fixture-browser-control-token'}});
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(ready.url);
 const panel=page.getByRole('region',{name:'Operations'});
 await page.getByRole('button',{name:'Operations',exact:true}).click();
 await panel.getByRole('button',{name:'Command · Running'}).click();
 await expect(panel.locator('pre')).toContainText('Build started');
 await page.request.post(ready.url+'/fixture/finish');
 await expect(panel.locator('strong')).toHaveText('Completed');
 await expect(panel.locator('pre')).toContainText('Build finished');
 await expect(panel.getByRole('button',{name:'Stop command'})).toHaveCount(0);
 assert.equal(await page.evaluate(()=>window.amplifier.getState().selectedSessionId),ready.sessionId);
 assert.equal(await page.evaluate(()=>window.amplifier.getState().view.draft),'Keep this unsent draft');
 await panel.getByRole('textbox',{name:'Command to start'}).fill("printf 'effect\n' >> effect.txt; printf 'input ready\n'; IFS= read -r value; printf 'got:%s\n' \"$value\"");
 await panel.getByRole('button',{name:'Start command',exact:true}).click();
 await expect(panel.locator('pre')).toContainText('input ready');
 await panel.getByRole('textbox',{name:'Command input'}).fill('browser input\n');
 await panel.getByRole('button',{name:'Send command input'}).click();
 await expect(panel.locator('pre')).toContainText('got:browser input');
 await expect(panel.locator('strong')).toHaveText('Completed');
 assert.equal((await (await page.request.get(ready.url+'/fixture/effects')).json()).count,1);
 assert.equal(await page.evaluate(()=>window.amplifier.getState().view.draft),'Keep this unsent draft');
 await page.screenshot({animations:'disabled',path:'/tmp/amplifier-operations-desktop.png'});
 await page.reload();
 await page.getByRole('button',{name:'Operations',exact:true}).click();
 await panel.getByRole('button',{name:'Command · Completed'}).last().click();
 await expect(panel.locator('pre')).toContainText('Build finished');
 await page.setViewportSize({width:390,height:844});
 assert.ok(await panel.evaluate(node=>node.scrollWidth<=node.clientWidth));
 await page.screenshot({animations:'disabled',path:'/tmp/amplifier-operations-mobile.png'});
 assert.deepEqual(errors,[]);
 console.log('Operations browser passed: durable evidence plus real approved-path process submission/stdin, one effect, completion, reload, draft/selection preserved and mobile bounds.');
}finally{await browser?.close();fixture.kill();}
