import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';

const fixture=spawn(fileURLToPath(new URL('../../.venv/bin/python',import.meta.url)),[fileURLToPath(new URL('../../tests/fixtures/questions_ui_server.py',import.meta.url))],{stdio:['ignore','pipe','inherit']});
let browser;
try{
 const ready=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Fixture timeout')),15000);fixture.stdout.on('data',chunk=>{output+=chunk;for(const line of output.split('\n'))try{const value=JSON.parse(line);if(value.url){clearTimeout(timer);resolve(value)}}catch{}});fixture.once('exit',code=>reject(Error('Fixture exit '+code)))});
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{Authorization:'Bearer fixture-browser-control-token'}});
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 const card=id=>page.locator(`[data-question-id="${id}"]`),composer=()=>page.getByRole('textbox',{name:'Message Amplifier',exact:true});
 const check=async()=>await (await page.request.get(ready.url+'/fixture/check')).json();
 await page.goto(ready.url);
 await expect(card(ready.required)).toBeVisible();
 await expect(card(ready.required).getByText('This step waits for your answer. Other work can continue.')).toBeVisible();
 assert.equal(await card(ready.required).getByRole('button',{name:'Skip question'}).count(),0);
 const draftSaved=page.waitForResponse(response=>response.url().endsWith('/api/actions')&&response.request().postDataJSON()?.action==='view.update'&&response.request().postDataJSON()?.args?.patch?.draft==='Keep this unsent message');
 await composer().fill('Keep this unsent message');await draftSaved;
 await page.reload();await expect(card(ready.required)).toBeVisible();
 await expect(composer()).toHaveValue('Keep this unsent message');
 assert.equal((await check()).sent.length,0,'Reconnect cannot submit an unanswered question');
 await card(ready.required).getByRole('radio',{name:/Full report/}).check();
 await page.screenshot({path:'/tmp/amplifier-durable-questions-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await card(ready.required).getByRole('button',{name:'Submit answer'}).scrollIntoViewIfNeeded();
 assert.ok(await card(ready.required).evaluate(element=>element.scrollWidth<=element.clientWidth));
 await page.screenshot({path:'/tmp/amplifier-durable-questions-choice-mobile.png'});
 await page.setViewportSize({width:1280,height:900});
 await card(ready.required).getByRole('button',{name:'Submit answer'}).click();
 await expect(page.locator('.a-question-history')).toBeVisible();
 await page.locator('.a-question-history summary').click();
 await expect(card(ready.required).getByText('Answer saved and delivered to Amplifier.')).toBeVisible();
 await expect(composer()).toHaveValue('Keep this unsent message');
 let state=await check();assert.equal(state.sent.length,1);assert.equal(state.sent[0].sessionId,ready.sessionId);
 const duplicate=await page.request.post(ready.url+'/api/actions',{data:{id:'second-device',action:'question.answer',args:{sessionId:ready.sessionId,id:ready.required,expectedRevision:1,optionId:'full'}}});
 assert.equal(duplicate.status(),409);assert.equal((await check()).sent.length,1);
 await card(ready.optional).getByRole('textbox',{name:'Your answer: What title would you like?'}).fill('Project findings');
 await card(ready.optional).getByRole('button',{name:'Submit answer'}).click();
 await expect(card(ready.optional).getByText('Answer saved and delivered to Amplifier.')).toBeVisible();
 await card(ready.skipped).getByRole('button',{name:'Skip question'}).click();
 await expect(card(ready.skipped).getByText('Question cancelled without an answer.')).toBeVisible();
 const voice=await (await page.request.post(ready.url+'/fixture/voice')).json();
 assert.equal(voice.answer.provenance.via,'call');assert.equal(voice.answer.provenance.voiceItemId,'fixture-answer');
 await expect(card(voice.id).getByText('Answer saved and delivered to Amplifier.')).toBeVisible();
 state=await check();assert.equal(state.sent.length,3);assert.equal(new Set(state.sent.map(row=>row.inputId)).size,3);
 await page.reload();await expect(composer()).toHaveValue('Keep this unsent message');
 await page.locator('.a-question-history summary').click();await expect(card(voice.id).getByText('Your answer: Plain language',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 await expect(card(voice.id)).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'/tmp/amplifier-durable-questions-mobile.png'});
 assert.deepEqual(errors,[]);
 console.log('Durable questions browser passed: reconnect, explicit required/optional UI, option and free-text answers, cancellation, duplicate rejection, preserved draft, shared voice provenance, mobile layout.');
}finally{await browser?.close();fixture.kill()}
