import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {openSettingsPage} from './browser-settings.mjs';
const fixture=spawn(fileURLToPath(new URL('../../.venv/bin/python',import.meta.url)),[fileURLToPath(new URL('../../tests/fixtures/schedules_ui_server.py',import.meta.url))],{stdio:['ignore','pipe','inherit']});
let browser;
try{
 const ready=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Fixture timeout')),15000);fixture.stdout.on('data',chunk=>{output+=chunk;for(const line of output.split('\n'))try{const row=JSON.parse(line);if(row.url){clearTimeout(timer);resolve(row)}}catch{}});fixture.once('exit',code=>reject(Error('Fixture exit '+code)))});
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{Authorization:'Bearer fixture-browser-control-token'}});
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 const post=async(path,data={})=>{const response=await page.request.post(ready.url+path,{data});assert.equal(response.status(),200,await response.text());return await response.json()};
 await page.goto(ready.url);await expect(page.locator('.a-settings-experience')).toBeVisible();await openSettingsPage(page,'runtime');await page.getByRole('button',{name:'Goals & modes',exact:true}).click();
 const panel=page.getByRole('region',{name:'Scheduled work'});
 await panel.getByLabel('Saved instructions').fill('Compare the report and tell me only about changes.');
 await panel.getByLabel('Repeat',{exact:true}).selectOption('interval');
 await panel.getByLabel('Timezone',{exact:true}).fill('UTC');
 const date=new Date((ready.now+120)*1000).toISOString();
 await panel.getByLabel('Start date',{exact:true}).fill(date.slice(0,10));await panel.getByLabel('Local time',{exact:true}).fill(date.slice(11,16));
 await panel.getByLabel('Repeat every (minutes)').fill('1');
 await panel.getByRole('button',{name:'Preview schedule'}).click();
 const preview=panel.locator('[data-part="schedule-preview"]');await expect(preview).toBeVisible();await expect(preview.getByRole('listitem')).toHaveCount(5);
 await preview.getByRole('button',{name:'Save and activate schedule'}).click();
 const card=panel.locator('[data-schedule-id]').first();await expect(card.getByRole('status')).toHaveText('Schedule active');
 await card.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/unified-schedules-desktop.png'});
 let result=await post('/fixture/tick');assert.equal(result.inputs.length,1);assert.equal(result.runs[0].phase,'accepted');
 result=await post('/fixture/finish');assert.equal(result.notifications.length,1);
 result=await post('/fixture/tick');assert.equal(result.inputs.length,2);
 result=await post('/fixture/finish');assert.equal(result.notifications.length,1);assert.equal(result.run.notificationDecision.notify,false);
 await card.getByText('Recent runs (2)',{exact:true}).click();await expect(card.getByText(/Stayed quiet/)).toBeVisible();
 await card.getByRole('button',{name:'Pause schedule'}).click();await expect(card.getByRole('status')).toHaveText('Schedule paused');
 await page.reload();await expect(page.locator('.a-settings-experience')).toBeVisible();await openSettingsPage(page,'runtime');await expect(card.getByRole('status')).toHaveText('Schedule paused');
 await card.getByRole('button',{name:'Review schedule'}).click();await panel.getByRole('button',{name:'Preview schedule'}).click();await preview.getByRole('button',{name:'Save and activate schedule'}).click();await expect(card.getByRole('status')).toHaveText('Schedule active');
 result=await post('/fixture/tick');assert.equal(result.inputs.length,3);
 result=await post('/fixture/restart');assert.equal(result.inputs.length,3);assert.equal(result.runs[0].phase,'unknown');
 await expect(card.getByRole('status')).toHaveText('Schedule needs review');await card.getByText('Recent runs (3)',{exact:true}).click();
 await card.getByLabel('Reconciliation evidence').fill('Inspected the original run; leave it abandoned without replay.');await card.getByRole('button',{name:'Mark run abandoned'}).click();
 await expect(card.getByText('abandoned',{exact:true})).toBeVisible();
 await card.getByRole('button',{name:'Cancel schedule'}).click();await expect(card.getByRole('status')).toHaveText('Schedule cancelled');
 await page.setViewportSize({width:390,height:844});await card.getByRole('status').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/unified-schedules-mobile.png'});
 assert.deepEqual(errors,[]);console.log('Schedules browser passed: concrete preview, activation, quiet compared monitor, pause/reload/review, restart unknown without replay, reconciliation, cancel, mobile.');
}finally{await browser?.close();fixture.kill()}
