import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const fixture=spawn(fileURLToPath(new URL('../../.venv/bin/python',import.meta.url)),[fileURLToPath(new URL('../../tests/fixtures/settings_ui_server.py',import.meta.url))],{stdio:'ignore'});
for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:8957/api/health')).ok)break}catch{}await new Promise(resolve=>setTimeout(resolve,100))}
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1100,height:900}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const state=()=>page.request.get('http://127.0.0.1:8957/api/state').then(r=>r.json());
try{
 await page.goto('http://127.0.0.1:8957/');
 await page.waitForSelector('#amp-one');
 await page.evaluate(()=>window.amplifier.dispatch('view.update',{patch:{panel:'settings',settingsSection:'setup',settingsExpanded:[]}}));
 await page.getByRole('button',{name:'Model providers Connections, credentials, models and provider options'}).click();
 await page.locator('.a-provider-choice').first().waitFor();
 assert.equal(await page.getByRole('button',{name:'Conversation defaults',exact:false}).count(),0);
 await page.locator('#filter-providers').fill('t*');
 assert.equal(await page.locator('.a-provider-choice').count(),2);
 assert.ok(await page.locator('.a-drag-handle').first().isDisabled());
 await page.getByRole('button',{name:'Clear filter providers',exact:true}).click();
 await page.getByRole('button',{name:'Discover models',exact:true}).click();
 await page.locator('select#provider-model').waitFor();
 await page.locator('#provider-model').selectOption(':custom:');
 await page.locator('input#provider-model').fill('my-custom-model');
 await page.getByRole('button',{name:'Choose from discovered models'}).click();
 assert.equal(await page.locator('#provider-model').inputValue(),'my-custom-model');
 await page.locator('#filter-models-one').fill('no-match*');
 assert.equal(await page.locator('#provider-model').inputValue(),'my-custom-model');
 await page.getByRole('button',{name:'Clear filter models',exact:true}).click();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await page.getByText('Provider check passed',{exact:true}).waitFor();
 assert.equal(await page.locator('.a-check-result.success').filter({hasText:'Provider check passed'}).count(),1);
 await page.locator('.a-drag-handle').first().dragTo(page.locator('.a-reorder-row').nth(2));
 await page.waitForFunction(()=>window.amplifier.getState().setup.providers[2]?.id==='one');
 assert.deepEqual((await state()).setup.providers.map(row=>row.id),['two','three','one']);
 await page.getByRole('button',{name:'Back to Setup',exact:true}).click();
 await page.getByRole('button',{name:'Model routing',exact:false}).click();
 await page.getByRole('button',{name:'Edit active profile',exact:true}).click();
 await page.locator('#routing-name').waitFor();
 assert.equal(await page.locator('#routing-name').inputValue(),'balanced');
 await page.getByLabel('general model 1',{exact:true}).fill('edited-model');
 await page.getByRole('button',{name:'Save active profile',exact:true}).click();
 await page.getByText('Routing profile saved and selected.').waitFor();
 assert.equal((await state()).setup.matrix.roles.general.candidates[0].model,'edited-model');
 await page.evaluate(()=>window.amplifier.dispatch('theme.apply',{name:'Existing skin',css:'#amp-one .a-overlay{padding:24px;border-radius:22px} @media(max-width:760px){#amp-one .a-settings-overlay .a-dialog.wide{width:100%;height:100dvh;border-radius:0}} #amp-one .a-dialog label{display:block;flex-direction:column} #amp-one .a-dialog{max-height:90dvh;border-radius:24px;padding:26px} #amp-one .a-dialog.wide{width:min(860px,100%)}'}));
 await page.getByRole('button',{name:'Maintenance',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Settings',exact:true}).locator('.a-attention-badge').innerText(),'1');
 assert.equal(await page.getByRole('button',{name:'Maintenance',exact:true}).locator('.a-attention-badge').innerText(),'1');
 await page.getByRole('button',{name:/Updates.*updates available/}).click();
 await page.locator('#available-updates-list li').first().waitFor();
 assert.equal(await page.locator('#available-updates-list li').count(),1);
 assert.match(await page.locator('#available-updates-list').innerText(),/×2/);
 assert.equal(await page.locator('#available-updates-list .a-check-result').count(),0);
 await page.getByRole('button',{name:'Mark reviewed',exact:true}).click();
 await page.waitForFunction(()=>window.amplifier.getState().attention.unread===0);
 assert.equal(await page.getByRole('button',{name:'Settings',exact:true}).locator('.a-attention-badge').count(),0);
 assert.equal(await page.getByRole('button',{name:'Maintenance',exact:true}).locator('.a-attention-badge').count(),0);
 assert.equal(await page.locator('#available-updates-list li').count(),1);
 await page.setViewportSize({width:680,height:844});
 const floating=await page.locator('.a-dialog').boundingBox();assert.ok(floating.x>0&&floating.y>0);assert.ok(floating.width<680);

 const aligned=await page.locator('.a-update-options label').first().evaluate(label=>{const input=label.querySelector('input'),a=input.getBoundingClientRect(),b=label.getBoundingClientRect();return {direction:getComputedStyle(label).flexDirection,width:a.width,delta:Math.abs(a.top+a.height/2-b.top-b.height/2)}});
 assert.equal(aligned.direction,'row');assert.equal(aligned.width,18);assert.ok(aligned.delta<3);
 await page.setViewportSize({width:390,height:844});
 const rect=await page.locator('.a-dialog').boundingBox();assert.equal(rect.x,0);assert.equal(rect.y,0);assert.equal(rect.width,390);assert.equal(rect.height,844);
 assert.equal(await page.locator('.a-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 await page.screenshot({animations:'disabled',path:'/tmp/amplifier-settings-mobile.png'});

 await page.getByRole('button',{name:'Show all 87 sources',exact:true}).click();
 await page.locator('#filter-update-sources').fill('*42*');
 assert.equal(await page.locator('#update-sources-list li').count(),1);
 assert.match(await page.locator('#update-sources-list li').innerText(),/fixture-source-42/);

 await page.getByRole('button',{name:'Back to Maintenance',exact:true}).click();
 await page.getByRole('button',{name:'File access',exact:true}).click();
 const spacing=await page.locator('#denied-folders').evaluate(el=>{const picker=el.closest('.a-path-field'),button=[...picker.parentElement.querySelectorAll('button')].find(b=>b.textContent==='Save permissions');return button.getBoundingClientRect().top-picker.getBoundingClientRect().bottom});
 assert.ok(spacing>=12);
 assert.equal(await page.getByText(/Provider keys live in the app/).count(),0);
 await page.getByRole('button',{name:'Capabilities',exact:true}).click();
 await page.getByRole('button',{name:'Loaded session modules',exact:false}).click();
 await page.locator('#filter-loaded-modules').fill('tool-*');
 assert.equal(await page.locator('.a-module-row').count(),1);
 await page.getByRole('button',{name:'tool-filesystem tools',exact:true}).click();
 await page.locator('#module-field-max_bytes').fill('4096');
 await page.getByRole('button',{name:'Apply to loaded session',exact:true}).click();
 await page.getByText('Changes are applied to the loaded session.',{exact:true}).waitFor();
 assert.equal((await state()).sessions[0].configuration.plan.tools[0].config.max_bytes,4096);
 await page.getByRole('checkbox',{name:'Enable tool-filesystem',exact:true}).uncheck();
 await page.getByRole('button',{name:'Apply to loaded session',exact:true}).click();
 await page.waitForFunction(()=>window.amplifier.getState().sessions[0].configuration.plan.tools[0].enabled===false);
 await page.screenshot({animations:'disabled',path:'/tmp/amplifier-settings-modules.png'});

 await page.getByRole('button',{name:'Back to Capabilities',exact:true}).click();
 await page.getByRole('button',{name:'Advanced module & source registries',exact:false}).click();
 const iconInline=await page.getByRole('button',{name:'Add module',exact:true}).evaluate(button=>{const icon=button.querySelector('svg').getBoundingClientRect(),range=document.createRange();range.selectNodeContents(button.lastChild);const label=range.getBoundingClientRect();return {direction:getComputedStyle(button).flexDirection,delta:Math.abs(icon.y+icon.height/2-label.y-label.height/2)}});
 assert.equal(iconInline.direction,'row');assert.ok(iconInline.delta<4);
 await page.getByRole('button',{name:'Back to Capabilities',exact:true}).click();
 await page.getByRole('button',{name:'Add capabilities',exact:false}).click();
 await page.locator('#bundle-source').fill('https://github.com/example/bundles');
 await page.getByRole('button',{name:'Browse',exact:true}).click();
 await page.locator('.a-candidate').first().waitFor();
 const radioInline=await page.locator('.a-candidate').first().evaluate(label=>{const radio=label.querySelector('input').getBoundingClientRect(),text=label.querySelector('strong').getBoundingClientRect();return {direction:getComputedStyle(label).flexDirection,width:radio.width,before:radio.right<=text.left,delta:Math.abs(radio.y-text.y)}});
 assert.equal(radioInline.direction,'row');assert.equal(radioInline.width,18);assert.ok(radioInline.before);assert.ok(radioInline.delta<8);
 await page.locator('#filter-bundle-discovery').fill('*dev*');
 assert.equal(await page.locator('.a-candidate').count(),1);
 await page.locator('.a-candidate input').check();
 await page.getByRole('button',{name:'Back to Capabilities',exact:true}).click();
 await page.getByRole('button',{name:'Add capabilities',exact:false}).click();
 assert.equal(await page.locator('#filter-bundle-discovery').inputValue(),'*dev*');
 assert.ok(await page.locator('.a-candidate input').isChecked());
 await page.screenshot({animations:'disabled',path:'/tmp/amplifier-settings-focused.png'});
 assert.equal(await page.locator('.a-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 await page.getByRole('button',{name:'Close panel',exact:true}).click();
 await page.evaluate(()=>window.amplifier.dispatch('view.update',{patch:{panel:'new-session'}}));
 await page.getByLabel('Registered root bundles',{exact:true}).selectOption('fixture-root');
 assert.equal(await page.locator('#setup-bundle').inputValue(),'fixture-root');
 await page.locator('.a-path-field').filter({has:page.locator('#setup-workspace')}).getByRole('button',{name:'Browse',exact:true}).click();
 const workspace=(await state()).settings.workspace;
 await page.locator('#setup-workspace-browse-path').fill(workspace+'/missing');
 await page.getByRole('button',{name:'Go',exact:true}).click();
 await page.getByText('This folder does not exist. Enter a different location.',{exact:true}).first().waitFor();
 await page.locator('#setup-workspace-browse-path').fill(workspace+'/project');
 await page.locator('#setup-workspace-browse-path').press('Enter');
 await page.waitForFunction(path=>window.amplifier.getState().locationListing.path===path,workspace+'/project');

 await page.getByRole('button',{name:'Use this folder',exact:true}).click();
 assert.match(await page.locator('#setup-workspace').inputValue(),/\/workspace\/project$/);
 await page.getByRole('button',{name:'Close panel',exact:true}).click();
 await page.evaluate(()=>window.amplifier.dispatch('view.update',{patch:{panel:'appearance'}}));
 const data=await page.evaluateHandle(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['#amp-one { --a-accent: purple; }'],'dropped.amplifier.css',{type:'text/css'}));return transfer});
 await page.locator('.a-file-drop').dispatchEvent('drop',{dataTransfer:data});
 await page.waitForFunction(()=>window.amplifier.getState().view.themeDraft?.includes('--a-accent: purple'));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({attentionTrail:true,reviewClearsBadges:true,compactGroupedUpdates:true,narrowerModalBreakpoint:true,typedFolderPath:true,registeredBundlePicker:true,actionSpacing:true,focusedPages:true,wildcardFilters:true,filterRetainsSelection:true,inlineBundleRadio:true,inlineAddModule:true,singleModelSelector:true,providerResult:true,providerDragOrder:true,activeRoutingEdit:true,inlineCheckbox:true,mobileFullscreen:true,noHorizontalOverflow:true,liveModuleConfig:true,liveModuleToggle:true,folderBrowser:true,fileDrop:true,browserErrors:errors.length}));
}catch(error){await page.screenshot({animations:'disabled',path:'/tmp/amplifier-settings-failure.png'});console.error(JSON.stringify({pageErrors:errors,locationListing:(await state()).locationListing,locationPicker:(await state()).view.locationPicker}));throw error}finally{await browser.close();fixture.kill('SIGTERM')}
