import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const fixture=spawn(fileURLToPath(new URL('../../.venv/bin/python',import.meta.url)),[fileURLToPath(new URL('../../tests/fixtures/settings_ui_server.py',import.meta.url))],{stdio:'ignore'});
for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:8957/api/health')).ok)break}catch{}await new Promise(resolve=>setTimeout(resolve,100))}
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1100,height:900}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const state=()=>page.request.get('http://127.0.0.1:8957/api/state').then(r=>r.json());
try{
 await page.goto('http://127.0.0.1:8957/');
 await page.waitForSelector('#amp-one');
 await page.evaluate(()=>window.amplifier.dispatch('view.update',{patch:{panel:'settings',settingsSection:'setup',settingsExpanded:[]}}));
 await page.getByRole('button',{name:'Model providers Connections, credentials, models and provider options'}).click();
 await page.locator('.a-provider-choice').first().waitFor();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await page.getByText('Provider check passed',{exact:true}).waitFor();
 assert.equal(await page.locator('.a-check-result.success').filter({hasText:'Provider check passed'}).count(),1);
 await page.locator('.a-drag-handle').first().dragTo(page.locator('.a-reorder-row').nth(2));
 await page.waitForFunction(()=>window.amplifier.getState().setup.providers[2]?.id==='one');
 assert.deepEqual((await state()).setup.providers.map(row=>row.id),['two','three','one']);
 await page.getByRole('button',{name:'Model routing',exact:false}).click();
 await page.getByRole('button',{name:'Edit active profile',exact:true}).click();
 await page.locator('#routing-name').waitFor();
 assert.equal(await page.locator('#routing-name').inputValue(),'balanced');
 await page.getByLabel('general model 1',{exact:true}).fill('edited-model');
 await page.getByRole('button',{name:'Save active profile',exact:true}).click();
 await page.getByText('Routing profile saved and selected.').waitFor();
 assert.equal((await state()).setup.matrix.roles.general.candidates[0].model,'edited-model');
 await page.evaluate(()=>window.amplifier.dispatch('theme.apply',{name:'Existing skin',css:'#amp-one .a-dialog label{display:block;flex-direction:column} #amp-one .a-dialog{max-height:90dvh;border-radius:24px;padding:26px} #amp-one .a-dialog.wide{width:min(860px,100%)}'}));
 await page.getByRole('button',{name:'Maintenance',exact:true}).click();
 await page.getByRole('button',{name:'Updates App, bundles and module updates'}).click();
 const aligned=await page.locator('.a-update-options label').first().evaluate(label=>{const input=label.querySelector('input'),a=input.getBoundingClientRect(),b=label.getBoundingClientRect();return {direction:getComputedStyle(label).flexDirection,width:a.width,delta:Math.abs(a.top+a.height/2-b.top-b.height/2)}});
 assert.equal(aligned.direction,'row');assert.equal(aligned.width,18);assert.ok(aligned.delta<3);
 await page.setViewportSize({width:390,height:844});
 const rect=await page.locator('.a-dialog').boundingBox();assert.equal(rect.x,0);assert.equal(rect.y,0);assert.equal(rect.width,390);assert.equal(rect.height,844);
 assert.equal(await page.locator('.a-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 await page.screenshot({path:'/tmp/amplifier-settings-mobile.png'});
 await page.getByRole('button',{name:'Capabilities',exact:true}).click();
 await page.getByRole('button',{name:'Loaded session modules',exact:false}).click();
 await page.getByRole('button',{name:'tool-filesystem tools',exact:true}).click();
 await page.locator('#module-field-max_bytes').fill('4096');
 await page.getByRole('button',{name:'Apply to loaded session',exact:true}).click();
 await page.getByText('Changes are applied to the loaded session.',{exact:true}).waitFor();
 assert.equal((await state()).sessions[0].configuration.plan.tools[0].config.max_bytes,4096);
 await page.getByRole('checkbox',{name:'Enable tool-filesystem',exact:true}).uncheck();
 await page.getByRole('button',{name:'Apply to loaded session',exact:true}).click();
 await page.waitForFunction(()=>window.amplifier.getState().sessions[0].configuration.plan.tools[0].enabled===false);
 await page.screenshot({path:'/tmp/amplifier-settings-modules.png'});
 await page.getByRole('button',{name:'Close panel',exact:true}).click();
 await page.evaluate(()=>window.amplifier.dispatch('view.update',{patch:{panel:'new-session'}}));
 await page.getByRole('button',{name:'Browse',exact:true}).click();
 await page.getByRole('button',{name:'project',exact:true}).click();
 await page.getByRole('button',{name:'Use this folder',exact:true}).click();
 assert.match(await page.locator('#setup-workspace').inputValue(),/\/workspace\/project$/);
 await page.getByRole('button',{name:'Close panel',exact:true}).click();
 await page.evaluate(()=>window.amplifier.dispatch('view.update',{patch:{panel:'appearance'}}));
 const data=await page.evaluateHandle(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['#amp-one { --a-accent: purple; }'],'dropped.amplifier.css',{type:'text/css'}));return transfer});
 await page.locator('.a-file-drop').dispatchEvent('drop',{dataTransfer:data});
 await page.waitForFunction(()=>window.amplifier.getState().view.themeDraft?.includes('--a-accent: purple'));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({providerResult:true,providerDragOrder:true,activeRoutingEdit:true,inlineCheckbox:true,mobileFullscreen:true,noHorizontalOverflow:true,liveModuleConfig:true,liveModuleToggle:true,folderBrowser:true,fileDrop:true,browserErrors:errors.length}));
}finally{await browser.close();fixture.kill('SIGTERM')}
