// Production assets only. External code is built AFTER the app is open.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {chromium,expect} from '@playwright/test';

const root=fileURLToPath(new URL('../../',import.meta.url));
const fixture=spawn(process.env.AMPLIFIER_TEST_PYTHON||root+'.venv/bin/python',['-u',root+'tests/fixtures/chat_library_server.py'],{stdio:['ignore','pipe','pipe'],env:{...process.env,AMPLIFIER_SHELL_PROOF:'1'}});
let log='';fixture.stderr.on('data',chunk=>log+=chunk);
const port=await new Promise((resolve,reject)=>{
 let output='';fixture.stdout.on('data',chunk=>{output+=chunk;const line=output.split('\n').find(row=>row.startsWith('{"port":'));if(line)resolve(JSON.parse(line).port)});
 fixture.once('exit',code=>reject(Error(`Fixture exited ${code}: ${log}`)));
});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050},extraHTTPHeaders:{Authorization:'Bearer fixture-browser-control-token'}});
const page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
const base=`http://127.0.0.1:${port}`;
const api=async(path,body)=>{
 const response=await context.request.fetch(base+path,{method:body===undefined?'GET':'POST',data:body});
 const data=await response.json();if(!response.ok())throw Error(data.error||JSON.stringify(data));return data;
};
const agent=async(action,args)=>api('/api/fixture/agent',{args:{action,args}});
const action=async(action,args)=>api('/api/actions',{action,args});
try{
 await page.goto(base);
 await page.locator('[data-shell-instance="chats"] .a-nav-chat').first().waitFor();
 const clientId=await page.evaluate(()=>window.amplifier.shellClientId);
 const inspect=()=>action('shell.inspect',{clientId}).then(r=>r.result);
 const original=(await inspect()).composition;
 const info=await api('/api/fixture/info');
 const beta=info.state.workspaces.find(row=>row.path===info.paths.two);
 assert.ok(beta);
 await action('conversation.send',{sessionId:info.initialSession,text:'Hold work during shell changes'});
 await page.waitForFunction(()=>window.amplifier.getState().sessions.find(row=>row.id===window.amplifier.getState().selectedSessionId)?.status==='working');
 const runningInfo=await api('/api/fixture/info');
 await action('canvas.show',{kind:'html',title:'Persistent viewer',content:'<!doctype html><html><body><h1>Persistent viewer</h1><input aria-label="Viewer note" value="Viewer state survives"/></body></html>'});
 await page.locator('.a-canvas-viewer iframe').waitFor();
 await page.getByRole('textbox',{name:'Message Amplifier'}).fill('Unsent draft survives shell changes');
 await page.waitForFunction(()=>window.amplifier.getState().view.draft==='Unsent draft survives shell changes');
 await page.evaluate(()=>{window.shellProof={root:document.getElementById('amp-one'),conversation:document.querySelector('[data-part="conversation"]'),viewer:document.querySelector('.a-canvas-viewer iframe'),session:window.amplifier.getState().selectedSessionId,time:performance.timeOrigin}});
 await import('../scripts/build-shell-example.mjs');
 const manifest=JSON.parse(await readFile(root+'examples/shell-navigator/dist/manifest.json','utf8'));
 const source=await readFile(root+'examples/shell-navigator/dist/module.mjs','utf8');
 const staged=await agent('shell.packages.stage',{manifest,source});
 const digest=staged.result.digest;
 const composition=structuredClone(original);
 composition.instances.unshift({id:'recent',package:digest,slot:'navigation',scope:{mode:'all'}});
 composition.instances.push({id:'beta-list',package:'builtin.chats',slot:'navigation',scope:{mode:'pinned',workspaceId:beta.id}});
 composition.presentation={scheme:'dark',layout:'work',density:'compact',accent:'#bdadff'};
 await assert.rejects(()=>action('shell.changes.prepare',{clientId,expectedRevision:0,composition}),/validation/);
 const validation=await agent('shell.packages.validate',{digest});
 assert.equal(validation.result.status,'passed',JSON.stringify(validation));
 // A replacement cannot discard a built-in module's unsaved form.
 await page.getByRole('button',{name:'New workspace',exact:true}).click();
 await page.locator('#nav-workspace-path').fill('/unsaved/module-form');
 await expect.poll(async()=>(await agent('shell.query',{clientId,instanceId:'workspaces'})).result.view.workspaceDraft?.path).toBe('/unsaved/module-form');
 const withoutEditor=structuredClone(original);withoutEditor.instances=withoutEditor.instances.filter(item=>item.id!=='workspaces');
 const removal=(await agent('shell.changes.prepare',{clientId,expectedRevision:0,composition:withoutEditor})).result.id;
 const deferred=await agent('shell.changes.apply',{clientId,changeId:removal,expectedRevision:0});
 assert.equal(deferred.result.status,'deferred');
 assert.equal(await page.locator('#nav-workspace-path').inputValue(),'/unsaved/module-form');
 await page.getByRole('button',{name:'Cancel navigation edit'}).click();
 await expect.poll(async()=>(await agent('shell.query',{clientId,instanceId:'workspaces'})).result.view.workspaceDraft?.mode).toBeUndefined();
 const prepared=await agent('shell.changes.prepare',{clientId,expectedRevision:0,composition});
 const changeId=prepared.result.id;
 await agent('shell.changes.preview',{clientId,changeId,expectedRevision:0});
 await page.getByRole('region',{name:'Recent navigator'}).waitFor();
 await page.waitForFunction(()=>document.getElementById('amp-one').style.colorScheme==='dark');
 const canvasBox=await page.locator('.a-canvas-panel').boundingBox(),chatBox=await page.locator('.a-conversation').boundingBox();
 assert.ok(canvasBox.x<chatBox.x,'work layout puts the canvas beside navigation without remounting');
 const separator=page.getByRole('separator',{name:'Resize canvas'});await separator.focus();await page.keyboard.press('ArrowRight');
 await expect.poll(async()=>(await page.locator('.a-canvas-panel').boundingBox()).width).toBeGreaterThan(canvasBox.width+15);
 assert.deepEqual((await inspect()).composition,original);
 await agent('shell.changes.apply',{clientId,changeId,expectedRevision:0});
 await expect.poll(async()=>(await inspect()).reported?.status).toBe('ready');
 assert.equal((await inspect()).revision,1);
 const recent=page.locator('[data-shell-instance="recent"]');
 await recent.getByRole('searchbox',{name:'Navigator search'}).fill('Beta');
 await page.waitForFunction(()=>window.amplifier.getShellState()?.snapshots?.recent?.chatNavigation.total===3);
 assert.equal(await page.locator('[data-shell-instance="beta-list"] .a-nav-chat').count(),3);
 assert.equal(await page.locator('[data-shell-instance="chats"] .a-nav-chat').count(),100);
 const second=await context.newPage();await second.goto(base);
 await second.locator('[data-shell-instance="chats"]').waitFor();
 assert.equal(await second.locator('[data-shell-instance]').count(),2);
 assert.notEqual(await second.evaluate(()=>window.amplifier.shellClientId),clientId);
 await second.close();
 await page.evaluate(()=>window.shellProof.navigator=document.querySelector('[aria-label="Navigator search"]'));
 const reordered=structuredClone(composition);reordered.instances.reverse();
 const next=(await agent('shell.changes.prepare',{clientId,expectedRevision:1,composition:reordered})).result.id;
 await agent('shell.changes.apply',{clientId,changeId:next,expectedRevision:1});
 await page.waitForFunction(()=>document.querySelector('[data-shell-instance="recent"]').style.order==='3');
 assert.equal(await page.evaluate(()=>window.shellProof.navigator===document.querySelector('[aria-label="Navigator search"]')),true);
 await assert.rejects(()=>action('shell.changes.apply',{clientId,changeId:next,expectedRevision:1}),/changed/);
 assert.deepEqual(await page.evaluate(()=>({root:window.shellProof.root===document.getElementById('amp-one'),conversation:window.shellProof.conversation===document.querySelector('[data-part="conversation"]'),viewer:window.shellProof.viewer===document.querySelector('.a-canvas-viewer iframe'),session:window.shellProof.session===window.amplifier.getState().selectedSessionId,time:window.shellProof.time===performance.timeOrigin})),{root:true,conversation:true,viewer:true,session:true,time:true});
 assert.equal(await page.getByRole('textbox',{name:'Message Amplifier'}).inputValue(),'Unsent draft survives shell changes');
 assert.deepEqual((await api('/api/fixture/info')).runtimeStarts,runningInfo.runtimeStarts);
 assert.deepEqual((await api('/api/fixture/info')).runtimeJobs,[info.initialSession]);
 assert.equal(await page.evaluate(()=>window.amplifier.getState().sessions.find(row=>row.id===window.amplifier.getState().selectedSessionId)?.status),'working');
 assert.equal((await api('/api/fixture/info')).generation,info.generation);
 await mkdir(root+'output/shell-proof',{recursive:true});
 await recent.scrollIntoViewIfNeeded();
 await page.screenshot({path:root+'output/shell-proof/hot-loaded.png',fullPage:true});
 const replaced=structuredClone(reordered);replaced.instances.find(item=>item.id==='chats').package=digest;
 const replacement=(await agent('shell.changes.prepare',{clientId,expectedRevision:2,composition:replaced})).result.id;
 await agent('shell.changes.apply',{clientId,changeId:replacement,expectedRevision:2});
 await page.locator('[data-shell-instance="chats"] [aria-label="Navigator search"]').waitFor();
 assert.equal(await page.locator('[data-shell-instance="beta-list"] .a-nav-chat').count(),3);
 const incompatible=(await agent('shell.packages.stage',{manifest:{...manifest,version:'2.0.0',stateSchema:'incompatible-v2'},source})).result.digest;
 assert.equal((await agent('shell.packages.validate',{digest:incompatible})).result.status,'passed');
 const incompatibleComposition=structuredClone(replaced);incompatibleComposition.instances.find(item=>item.id==='chats').package=incompatible;
 const incompatibleChange=(await agent('shell.changes.prepare',{clientId,expectedRevision:3,composition:incompatibleComposition})).result.id;
 assert.equal((await agent('shell.changes.apply',{clientId,changeId:incompatibleChange,expectedRevision:3})).result.status,'deferred');
 assert.equal((await inspect()).composition.instances.find(item=>item.id==='chats').package,digest);
 const privateImport=(await agent('shell.packages.stage',{manifest:{...manifest,id:'example.private-import'},source:'import app from "/src/main.jsx"; export default app;' })).result.digest;
 assert.equal((await agent('shell.packages.validate',{digest:privateImport})).result.status,'failed');
 const bad=(await agent('shell.packages.stage',{manifest:{...manifest,id:'example.broken'},source:'export default ()=>()=>{throw Error("Broken fixture")}' })).result.digest;
 const rejected=await agent('shell.packages.validate',{digest:bad});
 assert.equal(rejected.result.status,'failed');
 await agent('shell.changes.revert',{clientId,changeId,expectedRevision:3});
 await page.locator('[data-shell-instance="recent"]').waitFor({state:'detached'});
 assert.equal(await page.getByRole('textbox',{name:'Message Amplifier'}).inputValue(),'Unsent draft survives shell changes');
 assert.equal(await page.evaluate(()=>window.shellProof.viewer===document.querySelector('.a-canvas-viewer iframe')),true);
 assert.equal((await inspect()).revision,4);
 const persisted=await page.evaluate(()=>window.amplifier.getState().view.draft);
 // A module can pass the controlled fixture and still fail on live data.
 const liveOnly=(await agent('shell.packages.stage',{manifest:{...manifest,id:'example.live-failure'},source:'export default ({React})=>({host})=>{if(host.clientId!=="validation-client")throw Error("Live-only render failure");return React.createElement("p",null,"Fixture succeeds")}' })).result.digest;
 assert.equal((await agent('shell.packages.validate',{digest:liveOnly})).result.status,'passed');
 const broken=structuredClone(original);broken.instances.push({id:'broken',package:liveOnly,slot:'navigation'});
 const brokenChange=(await agent('shell.changes.prepare',{clientId,expectedRevision:4,composition:broken})).result.id;
 await agent('shell.changes.apply',{clientId,changeId:brokenChange,expectedRevision:4});
 await page.getByText('This component could not render.',{exact:false}).waitFor();
 await expect.poll(async()=>(await inspect()).reported?.instances?.broken).toBe('error');
 const observed=await inspect();assert.equal(observed.reported?.status,'incomplete',JSON.stringify({revision:observed.revision,reported:observed.reported,clientId}));
 // Recovery reload deliberately bypasses optional loading; ordinary changes above never reload.
 await page.goto(base+'/?shell=recovery');
 await page.getByText('Recovery mode: optional components are disabled.').waitFor();
 assert.equal(await page.locator('[data-shell-instance="broken"]').count(),0);
 await page.getByText('Shell controls',{exact:true}).click();
 await page.getByRole('button',{name:'Restore default shell',exact:true}).click();
 await page.waitForURL(base+'/');
 await page.locator('[data-shell-instance="chats"] .a-nav-chat').first().waitFor();
 assert.equal(await page.getByRole('textbox',{name:'Message Amplifier'}).inputValue(),persisted);
 await page.getByRole('button',{name:'Customize appearance'}).click();
 await page.locator('#scheme').selectOption('dark');
 await expect.poll(async()=>(await inspect()).composition.presentation.scheme).toBe('dark');
 await page.getByRole('button',{name:'Close panel'}).click();
 await action('view.update',{patch:{navPinned:false,navExpanded:true}});
 await page.locator('[data-shell-instance="chats"] .a-nav-chat-select').nth(1).click();
 await page.waitForFunction(()=>window.amplifier.getState().view.navExpanded===false);
 assert.deepEqual(errors,[]);
 console.log('PASS: production hot load; real host validation; agent preview/apply/revert; independent clients and scopes; stable chat, draft, viewer and page; failed/stale packages rejected.');
}catch(error){
 console.error(error);console.error(log.slice(-4000));throw error;
}finally{
 await browser.close();fixture.kill('SIGTERM');await once(fixture,'exit');
}
