import {validateServiceRelease} from './service-lifecycle.js';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
const schema=(properties={},required=[])=>({type:'object',additionalProperties:false,properties,required});
const bounded=(value,limit)=>{if(typeof value!=='string')return '';let result='',count=0;for(const char of value){if(count++===limit)break;result+=char}return result};
const string=max=>({type:'string',maxLength:max});
export const notificationActions={
 'notifications.get':{description:'Read shared remote notification settings. Private topic/token are never returned; desktop permission remains client-owned.',schema:schema()},
 'notifications.save':{description:'Save opt-in ntfy delivery at the exact shared settings revision. Blank private credentials preserve the previous value.',schema:schema({expectedRevision:{type:'integer',minimum:0},patch:schema({enabled:{type:'boolean'},server:string(2048),topic:string(128),token:string(8192),preview:{type:'boolean'},desktop:{type:'boolean'},clearTopic:{type:'boolean'},clearToken:{type:'boolean'}})},['expectedRevision','patch'])},
 'notifications.receipt':{description:'Read an exact redacted settings or send receipt after an uncertain response. Delivery is never replayed.',schema:schema({commandId:string(200)},['commandId'])},
};

const serviceFields=['installationId','dataScope','ownerId','instanceId','releaseDigest'];
function addServiceIdentity(result,value){if(result.purpose==='service-stop'){const identity=value.serviceIdentity;if(!identity||Array.isArray(identity)||Object.keys(identity).length!==serviceFields.length||serviceFields.some(key=>typeof identity[key]!=='string'||!identity[key]||identity[key].length>200||/[\x00-\x1f]/.test(identity[key]))||identity.instanceId!==result.instanceId||identity.dataScope!==result.dataScope)throw Error('Exact bounded service identity required');result.serviceIdentity=Object.fromEntries(serviceFields.map(key=>[key,identity[key]]));}else if(value.serviceIdentity!==undefined)throw Error('Service identity requires service-stop purpose');return result;}
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])])):value;
const signature=(context,outcome,proof)=>JSON.stringify(canonical({context,outcome,proof}));
class Peer{
 constructor(launcher,changed,idle){this.launcher=launcher;this.changed=changed;this.idle=idle;this.pending=new Map();this.next=0;this.calls=0;this.closed=false;this.releases=new Map();}
 signal(fn){try{Promise.resolve(fn?.()).catch(()=>{})}catch{}}
 fail(message){this.closed=true;for(const entry of this.pending.values()){clearTimeout(entry.timer);entry.reject(Error(message))}this.pending.clear();if(this.held)this.held.state='unknown';}
 async start(){if(this.closed)throw Error('Notification owner closed; no replay');if(!this.ready)this.ready=(async()=>{const child=this.child=spawn(this.launcher.command,this.launcher.args??[],{cwd:this.launcher.cwd,env:{...process.env,...this.launcher.env},stdio:'pipe'});child.stderr.on('data',()=>{});child.on('error',()=>this.fail('Notification owner failed to start'));child.on('close',()=>this.fail('Notification owner closed; uncertain sends not replayed'));let bytes=0;child.stdout.on('data',chunk=>{for(const byte of chunk){bytes=byte===10?0:bytes+1;if(bytes>131072)this.fail('Notification frame exceeded128KiB')}});createInterface({input:child.stdout}).on('line',line=>{if(this.closed)return;let row;try{row=JSON.parse(line)}catch{this.fail('Malformed notification frame');return;}if(row.method==='owner/changed'){this.signal(this.changed);return}if(row.method==='owner/idle'){this.signal(this.idle);return}const entry=this.pending.get(row.id);if(!entry)return;this.pending.delete(row.id);clearTimeout(entry.timer);row.error?entry.reject(Object.assign(Error(row.error.message),{knownRefusal:row.error.data?.knownRefusal===true})):entry.resolve(row.result);this.signal(this.idle);});const info=await this.send('initialize',{});if(info.protocolVersion!==1||!info.quiescence?.heldIntake||!info.quiescence?.durableRelease)throw Error('Notification owner lacks required protocol/fence contract');this.serviceSupported=info.quiescence?.serviceStop?.version===1})();return this.ready;}
 send(method,params){if(this.closed||!this.child)throw Error('Notification owner unavailable');if(this.pending.size>=64)throw Error('Notification request capacity reached');const id=++this.next,data=JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n';if(Buffer.byteLength(data)>131072)throw Error('Notification frame exceeds128KiB');return new Promise((resolve,reject)=>{const entry={resolve,reject};entry.timer=setTimeout(()=>{entry.timedOut=true;reject(Error('Notification reply timed out; inspect receipt, never replay'))},30000);entry.timer.unref();this.pending.set(id,entry);this.child.stdin.write(data,error=>{if(error)this.fail('Notification transport lost; uncertain sends not replayed')});});}
 async request(method,args){if(this.held&&!(method==='snapshot'||method==='action'&&args.operation!=='notifications.save'))return {accepted:false,executed:false,reason:'Notification intake held'};this.calls++;try{await this.start();return await this.send(method,args)}finally{this.calls--;this.signal(this.idle)}}
 inspectQuiescence=async()=>{await this.start();return this.send('quiescence/inspect',{})};
 context(value){const result={};for(const key of ['fenceId','commandId','purpose','instanceId','dataScope']){if(typeof value[key]!=='string'||!value[key]||value[key].length>200)throw Error('Bounded exact notification fence required');result[key]=value[key]}return addServiceIdentity(result,value);}
 acquire=async input=>{const context=this.context(input);await this.start();if(context.purpose==='service-stop'&&!this.serviceSupported)return null;if(this.calls||this.pending.size)return null;if(this.held&&(this.held.state!=='held'||JSON.stringify(this.held.context)!==JSON.stringify(context)))throw Error('Notification fence requires explicit reconciliation');this.held={context,state:'checking'};try{await this.start();const result=await this.send('quiescence/acquire',context);if(result.acquired!==true){if(result.executed===false){this.held=undefined;return null}throw Error('Notification intake outcome unknown')}if(result.fenceId!==context.fenceId||result.intakeClosed!==true)throw Error('Exact notification fence not confirmed');this.held.state='held';return {ownerId:'notifications',fenceId:context.fenceId,release:(outcome,proof)=>this.release(context,outcome,proof,true)}}catch(error){if(this.held)this.held.state='unknown';throw error}};
 release=async(input,outcome,proof,liveRollback=false)=>{const context=this.context(input),identity=signature(context,outcome,proof),priorRelease=this.releases.get(context.fenceId);if(priorRelease){if(priorRelease!==identity)throw Error('Exact retained Notifications release proof required');return}if(this.calls||this.pending.size)throw Error('Notifications requests are still in flight');if(this.held&&signature(this.held.context)!==signature(context))throw Error('Notifications fence changed');const rollback=liveRollback&&this.held?.state==='held'&&outcome==='unchanged'&&proof?.kind==='admission-refused'&&Object.keys(proof).length===1;if(context.purpose==='service-stop'&&outcome!=='unknown'&&!rollback)validateServiceRelease(context,outcome,proof);const before=this.held;await this.start();if(context.purpose==='service-stop'&&!this.serviceSupported)throw Error('Owner does not support service-stop');this.held={context,state:'unknown'};let result;try{result=await this.send('quiescence/release',{...context,outcome,proof})}catch(error){if(error.knownRefusal)this.held=before;throw error}if(outcome==='unknown')return;if(result.released!==true||result.intakeClosed!==false)throw Error('Notifications intake release unconfirmed');this.held=undefined;this.releases.set(context.fenceId,identity);if(this.releases.size>64)this.releases.delete(this.releases.keys().next().value)};

 get participant(){return {id:'notifications',serviceStop:{version:1},acquire:this.acquire,reconcileRelease:input=>this.release(input,input.outcome,input.proof)}}
 async close(){if(!this.child)return;this.child.stdin.end();if(this.child.exitCode===null&&this.child.signalCode===null)await new Promise(resolve=>this.child.once('close',resolve));}
}

export function createNotificationsCapability(options){
 let revision=0,closed=false;const connection=new Peer(options.owner,()=>options.onInvalidate?.('notifications','host'),()=>options.onMayBeIdle?.());
 const manifest={version:1,topics:{notifications:{uri:'amplifier-capability://notifications/settings',version:1,scope:'host',watch:true}},actions:Object.fromEntries(Object.keys(notificationActions).map(operation=>[operation,{topic:'notifications',operation,method:'x-amplifier/capabilityAction'}]))};
 const snapshot=async()=>({topic:'notifications',scope:'host',revision:++revision,data:{notificationSettings:await connection.request('snapshot',{})}});
 const completion=async({session,eventId,text,kind})=>{if(closed)return {accepted:false,executed:false,reason:'Notifications owner closed'};try{const settings=await connection.request('snapshot',{});if(!settings.enabled)return {accepted:false,disabled:true,executed:false};const selected=await options.inspectSession(session);if(selected.session!==session&&selected.uri!==session)throw Error('Selected notification session differs');return await connection.request('completion',{session,eventId,title:bounded(selected.title,200)||'Amplifier',text:bounded(text,1000),kind})}catch{return {accepted:false,status:'unknown',reason:'Notification admission unconfirmed; no retry'}}};
 return {
  manifest,actionSchemas:async()=>notificationActions,quiescenceAccess:{'notifications.get':'read','notifications.receipt':'read'},quiescenceParticipant:connection.participant,inspectQuiescence:connection.inspectQuiescence,
  read:async({topic,scope,uri})=>{const url=new URL(uri);url.search='';url.hash='';if(topic!=='notifications'||!['host','ahp-root://'].includes(scope)||url.href!==manifest.topics.notifications.uri)throw Error('Host-scoped notification topic required');return snapshot()},
  action:async(request,context)=>{const caller=typeof context?.session==='string'?context.session:context?.session?.uri;if(request.version!==1||request.topic!=='notifications'||!notificationActions[request.operation]||typeof request.channel!=='string'||!['host','ahp-root://',caller].includes(request.channel))throw Error('Unadvertised notification action or scope');const result=await connection.request('action',{operation:request.operation,args:request.args??{},commandId:request.commandId});const accepted=result.status!=='rejected'&&result.accepted!==false;return {accepted,result,updates:request.operation==='notifications.save'?[await snapshot()]:[],invalidate:request.operation==='notifications.save'?['notifications']:[]}},
  turnSettled:async event=>{try{if(event.status!=='completed'||event.inputOrigin==='scheduled')return {accepted:false,executed:false};const settings=await connection.request('snapshot',{});if(!settings.enabled)return {accepted:false,disabled:true,executed:false};let text='';if(settings.preview){const result=await options.waitForTurn(event.session,event.commandId,1);if(!result.completed||result.workContinues)return {accepted:false,executed:false};text=result.text??''}return completion({session:event.session,eventId:event.commandId,text,kind:'response'})}catch{return {accepted:false,status:'unknown',reason:'Notification result unavailable; no retry'}}},
  notifyAttention:args=>completion({...args,kind:'schedule-attention'}),
  close:async()=>{closed=true;await connection.close()},
 };
}
