import React,{useState,useEffect} from 'react';
const display=metric=>metric?.value==null?'Unknown':metric.value.toLocaleString(undefined,{maximumFractionDigits:6});
export function CapacityControls({session,act}){
 const [value,setValue]=useState(null),[quota,setQuota]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[draftRevision,setDraftRevision]=useState(0);
 const [draft,setDraft]=useState({enabled:false,maxTotalTokens:'',maxCostUsd:'',warningFraction:.8,unknownPolicy:'pause',includeEstimatedCost:false});
 const apply=(result,reset=true)=>{setValue(result);if(!reset)return;const b=result.budget;setDraftRevision(b.revision);setDraft({enabled:!!b.enabled,maxTotalTokens:b.maxTotalTokens??'',maxCostUsd:b.maxCostUsd??'',warningFraction:b.warningFraction??.8,unknownPolicy:b.unknownPolicy??'pause',includeEstimatedCost:!!b.includeEstimatedCost})};
 const run=async(action,args={})=>{setBusy(true);setError('');try{const response=await act(action,{sessionId:session.id,...args});if(response?.result){if(action==='capacity.quota')setQuota(response.result);else apply(response.result)}else if(response?.error)setError(response.error)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const edit=patch=>setDraft(old=>({...old,...patch}));
 const evidenceKey=(session.execution?.nodes||[]).filter(row=>row.kind==='llm').map(row=>`${row.id}:${row.revision||0}:${row.phase}`).join('|');
 useEffect(()=>{if(!value)return;let cancelled=false;act('capacity.read',{sessionId:session.id}).then(response=>{if(!cancelled&&response?.result)apply(response.result,false)}).catch(()=>{});return()=>{cancelled=true}},[evidenceKey]);
 const metrics=value?.usage?.metrics||{},invalid=(!draft.maxTotalTokens&&!draft.maxCostUsd&&draft.enabled)||(draft.maxTotalTokens!==''&&(!Number.isInteger(Number(draft.maxTotalTokens))||Number(draft.maxTotalTokens)<=0))||(draft.maxCostUsd!==''&&!(Number(draft.maxCostUsd)>0));
 return <section className="a-settings-section" aria-label="Task usage and budget" data-part="capacity-controls"><h3>Task usage & budget</h3><p>Track this conversation and its observed workers. Existing calls may finish and exceed a limit; new model calls wait when the budget is reached.</p><button className="a-soft" disabled={busy} data-action="capacity.read" onClick={()=>run('capacity.read')}>Inspect task usage</button>{error&&<p role="alert">{error}</p>}
 {value&&<><p role="status">Budget {value.admission.state} · {value.usage.calls} recorded model calls</p>{value.admission.reasons.map(reason=><p key={reason}>{reason}</p>)}{value.admission.warnings.map(warning=><p key={warning}>{warning}</p>)}<dl className="a-capability-counts"><div><dt>Total tokens including cache writes</dt><dd>{display(metrics.grossTotalTokens)} · {metrics.grossTotalTokens.status}</dd></div><div><dt>Cost (USD)</dt><dd>{display(metrics.costUsd)} · {metrics.costUsd.status}{metrics.costUsd.estimatedCalls>0?' · includes estimates':''}</dd></div></dl><p className="a-caption">{metrics.grossTotalTokens.unknownCalls} calls with unknown token totals · {metrics.costUsd.unknownCalls} calls with unknown cost · {value.admission.inFlightCalls} in flight. Totals cover observed calls; missing telemetry is not zero.</p>
 <details><summary>Model breakdown and receipts</summary>{value.usage.providers.map(row=><p key={row.provider+'|'+row.model}>{row.provider} / {row.model} · {row.calls} calls · {display(row.metrics.grossTotalTokens)} tokens · {display(row.metrics.costUsd)} USD</p>)}<p className="a-caption">Receipts {value.usage.offset+1}–{value.usage.offset+value.usage.receipts.length} of {value.usage.receiptCount}. Observed {new Date(value.observedAt*1000).toLocaleTimeString()}.</p><pre className="a-state-view">{JSON.stringify(value.usage.receipts,null,2)}</pre>{value.usage.nextOffset!=null&&<button className="a-soft" disabled={busy} data-action="capacity.read" onClick={()=>run('capacity.read',{offset:value.usage.nextOffset})}>Next receipts</button>}</details>
 <label className="a-inline-checkbox"><input type="checkbox" checked={draft.enabled} onChange={e=>edit({enabled:e.target.checked})}/>Enable cumulative task budget</label><div className="a-form-grid"><div><label htmlFor="capacity-tokens">Total token limit</label><input id="capacity-tokens" type="number" min="1" value={draft.maxTotalTokens} onChange={e=>edit({maxTotalTokens:e.target.value})}/></div><div><label htmlFor="capacity-cost">Cost limit (USD)</label><input id="capacity-cost" type="number" min="0.000001" step="any" value={draft.maxCostUsd} onChange={e=>edit({maxCostUsd:e.target.value})}/></div></div><label htmlFor="capacity-warning">Warn at percentage</label><input id="capacity-warning" type="number" min="1" max="100" value={Math.round(draft.warningFraction*100)} onChange={e=>edit({warningFraction:Number(e.target.value)/100})}/><label htmlFor="capacity-unknown">When settled usage is unknown</label><select id="capacity-unknown" value={draft.unknownPolicy} onChange={e=>edit({unknownPolicy:e.target.value})}><option value="pause">Pause future model calls</option><option value="allow">Allow calls with incomplete totals</option></select><label className="a-inline-checkbox"><input type="checkbox" checked={draft.includeEstimatedCost} onChange={e=>edit({includeEstimatedCost:e.target.checked})}/>Include attributed estimates in the cost limit</label>{draftRevision!==value.budget.revision&&<p role="alert">This budget changed. Inspect usage again before saving your changes.</p>}<button className="a-primary" disabled={draftRevision!==value.budget.revision||busy||invalid||!(draft.warningFraction>0&&draft.warningFraction<=1)} data-action="capacity.set" onClick={()=>run('capacity.set',{...draft,expectedRevision:draftRevision,maxTotalTokens:draft.maxTotalTokens===''?null:Number(draft.maxTotalTokens),maxCostUsd:draft.maxCostUsd===''?null:Number(draft.maxCostUsd)})}>Save budget</button><p className="a-caption">Saving updates the next admission check. It does not send a message or resume a separately paused task. Revision {value.budget.revision}.</p></>}
 <button className="a-soft" disabled={busy} data-action="capacity.quota" onClick={()=>run('capacity.quota')}>Inspect provider quota</button>{quota&&<div>{!quota.providers.length&&<p>No provider quota capability is available.</p>}{quota.providers.map(row=><div key={row.provider}><p>{row.provider}: {row.status}{row.status==='unsupported'?' · remaining capacity and reset time unknown':''}</p>{row.windows&&<pre className="a-state-view">{JSON.stringify(row.windows,null,2)}</pre>}</div>)}</div>}</section>;
}
