import {SettingsActions} from './settings-layout';
import {ActivityRegion} from './activity-region';
import React from 'react';
import {Activity,Plus,ArrowLeft,Trash2,Download,RefreshCw} from 'lucide-react';
import {ResultNotice,SettingsGroup} from './settings-ui';

const newDestination=()=>({id:crypto.randomUUID(),name:'Personal server',url:'',enabled:false,streams:['sessions','workers','tools','usage','updates'],workspace:'amplifier-unified',workspacePattern:'*',includePaths:false,authMode:'static',apiKeyEnv:'AMPLIFIER_CONTEXT_INTELLIGENCE_API_KEY',authResource:''});
export function DiagnosticsSettings({state,act}){
 const busy=action=>['queued','working','pending'].includes(state.actionStatus?.[action]?.phase);
 const info=state.diagnostics||{},draft=state.view?.diagnosticsDraft||{},cfg=draft.config||info.config,streams=info.streams||[];
 if(!cfg)return null;
 const change=patch=>act('view.update',{patch:{diagnosticsDraft:{...draft,...patch}}});
 const config=patch=>change({config:{...cfg,...patch}}),selected=cfg.destinations.find(d=>d.id===draft.destinationId);
 const update=patch=>config({destinations:cfg.destinations.map(d=>d.id===selected.id?{...d,...patch}:d)});
 const save=async()=>{const receipt=await act('diagnostics.configure',{config:cfg});if(receipt?.accepted)change({config:null})};
 const result=info.lastResult,delivery=selected&&info.destinations?.find(d=>d.id===selected.id),test=selected&&info.results?.[selected.id];
 const toggle=(current,id,on)=>on?[...current,id]:current.filter(x=>x!==id);
 const pickStreams=(values,onChange,local=false)=><div className="a-diagnostic-streams">{streams.map(s=><label className="a-inline-checkbox" key={s.id}><input type="checkbox" data-action="view.update" checked={values.includes(s.id)} disabled={!local&&!cfg.streams.includes(s.id)} onChange={e=>onChange(toggle(values,s.id,e.target.checked))}/><span>{s.label}</span></label>)}</div>;
 return <SettingsGroup id="diagnostics" title="Diagnostics & Context Intelligence" summary="Local capture, selected streams and your servers" state={state} act={act}>
 <p>Keep diagnostic records on this computer, or send selected streams to your own Context Intelligence servers. Each server has its own choices. App forwarding starts only after you save an enabled destination. Bundle exporters have their own settings.</p>
 {selected?<ActivityRegion name={'diagnostic-destination-'+selected.id} busy={test?.phase==='working'}><button className="a-link a-diagnostics-back" data-action="view.update" onClick={()=>change({destinationId:null})}><ArrowLeft/>All destinations</button>
 <div className="a-form-grid"><label>Name<input data-action="view.update" value={selected.name} onChange={e=>update({name:e.target.value})}/></label><label>Server URL<input type="url" placeholder="https://context.example.com" data-action="view.update" value={selected.url} onChange={e=>update({url:e.target.value})}/></label></div>
 <label className="a-inline-checkbox"><input type="checkbox" data-action="view.update" checked={selected.enabled} onChange={e=>update({enabled:e.target.checked})}/>Send new selected records to this server</label>
 <label>Authentication<select data-action="view.update" value={selected.authMode} onChange={e=>update({authMode:e.target.value})}><option value="static">API key from environment</option><option value="entra">Microsoft Entra</option></select></label>
 {selected.authMode==='static'?<><label>API key environment variable<input data-action="view.update" value={selected.apiKeyEnv} onChange={e=>update({apiKeyEnv:e.target.value})}/></label><button className="a-soft" data-action="diagnostics.environment" onClick={()=>act('diagnostics.environment',{name:selected.apiKeyEnv})}>Check variable</button>{result?.action==='diagnostics.environment'&&result.name===selected.apiKeyEnv&&<ResultNotice {...result}/>}</>:<label>Entra resource URI<input data-action="view.update" value={selected.authResource} placeholder="api://application-id" onChange={e=>update({authResource:e.target.value})}/></label>}
 <h4>Streams for this server</h4>{pickStreams(selected.streams,values=>update({streams:values}))}
 <p className="a-caption">Conversation text may contain private information. Redaction is best effort. Tool arguments, results, reasoning, file contents and canvas HTML are excluded from metadata streams.</p>
 <div className="a-form-grid"><label>Server workspace label<input data-action="view.update" value={selected.workspace} onChange={e=>update({workspace:e.target.value})}/></label><label>Capture from workspace paths<input data-action="view.update" value={selected.workspacePattern} placeholder="* or /Users/me/work/*" onChange={e=>update({workspacePattern:e.target.value})}/></label></div>
 <p className="a-caption">The label organizes records; it is not an access boundary on a shared server. Path filters use * and ? wildcards.</p>
 <label className="a-inline-checkbox"><input type="checkbox" data-action="view.update" checked={selected.includePaths} onChange={e=>update({includePaths:e.target.checked})}/>Include workspace folder paths in remote records</label>
 <div className="a-dialog-actions"><SettingsActions><button className="a-primary" data-action="diagnostics.configure" onClick={save}>Save destination</button></SettingsActions><button className="a-soft" data-operation-pending={test?.phase==='working'||undefined} aria-busy={test?.phase==='working'||undefined} data-action="diagnostics.test" disabled={!!draft.config||test?.phase==='working'} onClick={()=>act('diagnostics.test',{id:selected.id})}>Test connection</button><button className="a-soft" data-action="diagnostics.retry" disabled={!delivery?.counts?.failed} onClick={()=>act('diagnostics.retry',{id:selected.id})}><RefreshCw/>Retry failed deliveries</button></div>
 <p className="a-caption">Save before testing. A test sends one synthetic event to verify authentication and write access.</p>{!draft.config&&<ResultNotice {...test}/>}
 <p className="a-caption">{delivery?.counts?.accepted||0} accepted · {delivery?.counts?.duplicate||0} recognized retries · {delivery?.counts?.pending||0} queued · {delivery?.counts?.failed||0} failed · {delivery?.counts?.cancelled||0} cancelled</p>
 {delivery?.error&&<ResultNotice phase="error" message={`Delivery needs attention: ${delivery.error.type}${delivery.error.statusCode?' (HTTP '+delivery.error.statusCode+')':''}`}/>}
 <button className="a-soft a-danger" data-action="diagnostics.configure" onClick={async()=>{const receipt=await act('diagnostics.configure',{config:{...cfg,destinations:cfg.destinations.filter(d=>d.id!==selected.id)}});if(receipt?.accepted)change({config:null,destinationId:null})}}><Trash2/>Remove destination</button>
 </ActivityRegion>:<><label className="a-inline-checkbox"><input type="checkbox" data-action="view.update" checked={cfg.enabled} onChange={e=>config({enabled:e.target.checked})}/>Collect app diagnostics and enable selected forwarding</label>
 <p className="a-caption">Sessions use the community Context Intelligence hook and shared files. Configure raw session capture in the running mount plan. The choices below control this app’s metadata index and forwarding; they do not disable the hook.</p>
 <h4>Streams to index and make available for forwarding</h4>{pickStreams(cfg.streams,values=>config({streams:values,destinations:cfg.destinations.map(d=>({...d,streams:d.streams.filter(s=>values.includes(s))}))}),true)}
 <div className="a-form-grid"><label>Index days<input type="number" min="1" max="365" value={cfg.retentionDays} data-action="view.update" onChange={e=>config({retentionDays:Number(e.target.value)})}/></label><label>Maximum indexed records<input type="number" min="100" max="100000" value={cfg.maxRecords} data-action="view.update" onChange={e=>config({maxRecords:Number(e.target.value)})}/></label></div>
 <p className="a-caption">These limits apply to the local index and queued deliveries. Shared Context Intelligence events.jsonl files are preserved. Indexed: {info.local?.storageError&&info.local?.records==null?'unavailable':(info.local?.records??0)+' records'}.{info.local?.dropped||info.local?.outboxDropped||info.local?.expiredPending?` Dropped: ${info.local.dropped||0}; outbox limit: ${info.local.outboxDropped||0}; expired before delivery: ${info.local.expiredPending||0}.`:''}</p>
 {info.local?.configurationError&&<ResultNotice phase="error" message="The saved diagnostics configuration could not be read. Capture and forwarding are disabled; save reviewed settings to restore them."/>}
 {info.local?.storageError&&<ResultNotice phase="error" message="Local diagnostic storage needs attention. Conversations can continue."/>}
 <SettingsActions><button className="a-primary" data-action="diagnostics.configure" onClick={save}>Save capture settings</button></SettingsActions>
 <h4>Destinations</h4><div className="a-diagnostic-destinations">{cfg.destinations.map(d=>{const status=info.destinations?.find(row=>row.id===d.id);return <button className="a-settings-group-title" data-action="view.update" key={d.id} onClick={()=>change({destinationId:d.id})}><span><strong>{d.name}</strong><small>{d.enabled?'Sending selected streams':'Disabled'} · {d.streams.length} streams{status?.error?' · Needs attention':''}</small></span><Activity/></button>})}</div>
 <button className="a-soft" data-action="view.update" onClick={()=>{const d=newDestination();change({config:{...cfg,destinations:[...cfg.destinations,d]},destinationId:d.id})}}><Plus/>Add server</button>
 <p className="a-caption">Saving a changed destination cancels its old pending deliveries. Data already accepted or in flight cannot be recalled. Selecting another stream starts with new records; history is never uploaded automatically.</p>
 <ActivityRegion name="diagnostic-records" busy={busy('diagnostics.records')}><h4>Inspect local records</h4><div className="a-form-grid"><label>Stream filter<input data-action="view.update" value={draft.stream||'*'} onChange={e=>change({stream:e.target.value})} placeholder="* or updates"/></label><label>Session ID (optional)<input data-action="view.update" value={draft.sessionId||''} onChange={e=>change({sessionId:e.target.value})}/></label></div>
 <div className="a-dialog-actions"><button className="a-soft" data-action="diagnostics.records" onClick={()=>act('diagnostics.records',{stream:draft.stream||'*',...(draft.sessionId?{sessionId:draft.sessionId}:{})})}>Read records</button>{result?.action==='diagnostics.records'&&<><button className="a-soft" data-action="diagnostics.export" onClick={()=>act('diagnostics.export')}><Download/>Export this page</button>{result.nextBefore&&<button className="a-soft" data-action="diagnostics.records" onClick={()=>act('diagnostics.records',{stream:draft.stream||'*',...(draft.sessionId?{sessionId:draft.sessionId}:{}),before:result.nextBefore})}>Older records</button>}</>}</div>
 {result?.action==='diagnostics.records'&&<pre className="a-state-view">{JSON.stringify(result.items,null,2)}</pre>}</ActivityRegion>
 </>}
 {result?.action!=='diagnostics.records'&&result?.action!=='diagnostics.test'&&result?.action!=='diagnostics.environment'&&<ResultNotice phase={result?.phase||'ready'} message={result?.message}/>}
 </SettingsGroup>;
}
