import {DiagnosticsSettings} from './diagnostics';
import {SettingsGroup,FileDrop,PathField} from './settings-ui';
import React,{useState} from 'react';
import {transcriptFileArgs} from './history-import';
export function MaintenanceSettings({state,act}){
 const [topic,setTopic]=useState(''),[token,setToken]=useState('');
 const session=state.sessions?.find(s=>s.id===state.selectedSessionId),draft=state.view?.maintenanceDraft||{},prefs=state.permissions||{},notify=state.notificationSettings||{},busy=state.management?.phase==='working';
 const set=patch=>act('view.update',{patch:{maintenanceDraft:{...draft,...patch}}});
 const scope=draft.scope||'global',resetParts=draft.resetParts||[],resetPreview=state.maintenance?.resetPreview;
 const matchingPreview=resetPreview&&JSON.stringify([...resetParts].sort())===JSON.stringify([...(resetPreview.parts||[])].sort());
 const call=(name,args={})=>act(name,{...(session?{sessionId:session.id}:{}),...args});
 return <div data-part="maintenance">
 <DiagnosticsSettings state={state} act={act}/>
 <SettingsGroup id="history" title="Conversation history" state={state} act={act}><p>Your CLI projects and conversations appear automatically in the workspace sidebar. Open a chat there to continue the same conversation, or export its transcript here.</p>{session&&<button className="a-soft" data-action="history.export" onClick={()=>call('history.export',{format:'jsonl'})}>Export runtime transcript</button>}<div className="a-selection-card"><h4>Import a conversation file</h4><p>Load a Unified JSON export or CLI JSONL transcript as a new conversation.</p><div className="a-form-grid"><div><label htmlFor="history-import-title">Conversation title (optional)</label><input id="history-import-title" value={draft.importTitle||''} data-action="view.update" onChange={e=>set({importTitle:e.target.value})}/></div><div><label htmlFor="history-import-bundle">Bundle override (optional)</label><input id="history-import-bundle" value={draft.importBundle||''} data-action="view.update" onChange={e=>set({importBundle:e.target.value})} placeholder="Use the export’s bundle"/></div></div><label htmlFor="history-import-file">Choose JSON or JSONL (up to 1 MB)</label><FileDrop id="history-import-file" accept=".json,.jsonl,application/json,application/x-ndjson" disabled={busy} action="history.importFile" label="Choose a conversation" hint="Drop JSON or JSONL here · up to 1 MB" onFile={async file=>{const args=await transcriptFileArgs(file,{title:draft.importTitle,bundle:draft.importBundle});set({importError:''});await act('history.importFile',args)}}/>{draft.importError&&<p className="a-danger" role="alert">{draft.importError}</p>}<p className="a-caption">Original transcript entries are preserved. Imported jobs do not restart automatically.</p></div><label>Older than (days)<input type="number" min="1" value={draft.cleanupDays||30} data-action="view.update" onChange={e=>set({cleanupDays:Number(e.target.value)})}/></label><button className="a-soft" data-action="history.cleanup" onClick={()=>act('history.cleanup',{days:draft.cleanupDays||30})}>Preview cleanup</button>{state.cleanupPreview&&<><p>{state.cleanupPreview.sessions.length} inactive conversations eligible. Your selected conversation is kept.</p><label><input type="checkbox" data-action="view.update" checked={!!draft.purge} onChange={e=>set({purge:e.target.checked})}/>Also remove retained legacy app files (shared CLI history is kept)</label><button className="a-soft a-danger" data-action="history.cleanup" disabled={!state.cleanupPreview.sessions.length} onClick={()=>act('history.cleanup',{days:draft.cleanupDays||30,apply:true,purge:!!draft.purge})}>Clean up these conversations</button></>}</SettingsGroup>
 <SettingsGroup id="permissions" title="File access" state={state} act={act}><p>Choose which locations file tools may write to. Denied locations take precedence. Shell commands follow the policies in your bundle.</p><label>Save for<select value={scope} data-action="view.update" onChange={e=>set({scope:e.target.value})}><option value="global">All projects</option><option value="project">This project</option><option value="local">This computer’s project settings</option></select></label><button className="a-soft" data-action="permissions.get" disabled={!session} onClick={()=>call('permissions.get',{scope})}>Load permissions</button><label htmlFor="allowed-folders">Allowed folders (one per line)</label><PathField id="allowed-folders" multiline directory state={state} act={act} value={draft.allowed??(prefs.allowed||[]).join('\n')} onChange={allowed=>set({allowed})}/><label htmlFor="denied-folders">Denied folders (one per line)</label><PathField id="denied-folders" multiline directory state={state} act={act} value={draft.denied??(prefs.denied||[]).join('\n')} onChange={denied=>set({denied})}/><button className="a-primary" disabled={!session||busy} data-action="permissions.save" onClick={()=>call('permissions.save',{scope,allowed:(draft.allowed??(prefs.allowed||[]).join('\n')).split('\n').filter(Boolean),denied:(draft.denied??(prefs.denied||[]).join('\n')).split('\n').filter(Boolean)})}>Save permissions</button>{prefs.detail&&<p>{prefs.detail}</p>}</SettingsGroup>
 <SettingsGroup id="notifications" title="Notifications" state={state} act={act}><button className="a-soft" data-action="notifications.get" onClick={()=>act('notifications.get')}>Load notification settings</button><button className="a-soft" data-action="notification.request" onClick={()=>act('notification.request')}>Allow browser notifications</button><label className="a-inline-checkbox"><input type="checkbox" data-action="view.update" checked={draft.notifyDesktop??notify.desktop??true} onChange={e=>set({notifyDesktop:e.target.checked})}/>Show desktop notifications for text responses</label><p>Optional ntfy delivery can reach your other devices. Message previews are off by default.</p><label>Notification server<input data-action="view.update" value={draft.notifyServer??notify.server??'https://ntfy.sh'} onChange={e=>set({notifyServer:e.target.value})}/></label><label>Topic {notify.topicConfigured?'(saved; leave blank to keep)':''}<input type="password" autoComplete="off" data-action="notifications.save" value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>Access token {notify.tokenConfigured?'(saved; leave blank to keep)':''}<input type="password" autoComplete="off" data-action="notifications.save" value={token} onChange={e=>setToken(e.target.value)}/></label><label><input type="checkbox" data-action="view.update" checked={draft.notifyEnabled??notify.enabled??false} onChange={e=>set({notifyEnabled:e.target.checked})}/>Send push notifications</label><label><input type="checkbox" data-action="view.update" checked={draft.notifyPreview??notify.preview??false} onChange={e=>set({notifyPreview:e.target.checked})}/>Include a response preview</label><button className="a-primary" data-action="notifications.save" onClick={async()=>{await act('notifications.save',{patch:{desktop:draft.notifyDesktop??notify.desktop??true,server:draft.notifyServer??notify.server??'https://ntfy.sh',enabled:draft.notifyEnabled??notify.enabled??false,preview:draft.notifyPreview??notify.preview??false,...(topic?{topic}:{}),...(token?{token}:{})}});setTopic('');setToken('')}}>Save notifications</button></SettingsGroup>
 <SettingsGroup id="automation" title="Terminal and automation" state={state} act={act}><p>Run a task without opening the web app. It uses the same Amplifier host, saved configuration, and tool permissions.</p><pre className="a-state-view">{'amplifier-unified run "Summarize the changes in this workspace"\namplifier-unified run "Review this project" --output-format json\namplifier-unified continue --resume SESSION_ID "Continue the work"'}</pre><p className="a-caption">Use --bundle to choose a bundle and --provider / --model to select a model. JSON output is suitable for scripts; json-trace also includes execution events. Headless runs cannot answer an interactive approval prompt.</p></SettingsGroup>
 <SettingsGroup id="repair" title="Backup and repair" state={state} act={act}><p>Save a full private backup of your configuration, credentials, and conversations, or repair installed runtime dependencies. Repair waits until work is idle.</p><div className="a-dialog-actions"><button className="a-soft" data-action="maintenance.backup" disabled={busy} onClick={()=>act('maintenance.backup')}>Create full backup</button><button className="a-soft" data-action="maintenance.repair" disabled={busy} onClick={()=>act('maintenance.repair')}>Repair runtime</button></div><p className="a-caption">Backups contain credentials and are not encrypted. Keep them private.</p>{state.maintenance?.backup&&<p className="a-caption a-wrap">Saved backup: {state.maintenance.backup}</p>}{state.maintenance?.detail&&<p>{state.maintenance.detail}</p>}</SettingsGroup>
 <SettingsGroup id="reset" title="Advanced recovery" state={state} act={act}><p>Reset selected app data when ordinary repair is not enough. Your workspace files and original CLI data are kept.</p>{[['runtime','Rebuild installed runtime'],['cache','Clear downloaded bundle and module caches'],['settings','Reset app configuration and credentials'],['conversations','Remove saved conversations from the app']].map(([part,label])=><label className="a-inline-checkbox" key={part}><input type="checkbox" checked={resetParts.includes(part)} data-action="view.update" onChange={e=>set({resetParts:e.target.checked?[...resetParts,part]:resetParts.filter(value=>value!==part),resetConfirmation:''})}/>{label}</label>)}<button className="a-soft" disabled={busy||!resetParts.length} data-action="maintenance.reset" onClick={()=>act('maintenance.reset',{parts:resetParts})}>Preview selected reset</button>{matchingPreview&&<div className="a-selection-card"><p>These locations will be moved into a recovery folder:</p><ul className="a-catalog-list">{(resetPreview.paths||[]).map((path,index)=><li className="a-wrap" key={index}><code>{typeof path==='string'?path:JSON.stringify(path)}</code></li>)}</ul><label htmlFor="reset-confirmation">Type RESET to apply this selection</label><input id="reset-confirmation" value={draft.resetConfirmation||''} data-action="view.update" onChange={e=>set({resetConfirmation:e.target.value})}/><button className="a-soft a-danger" disabled={busy||draft.resetConfirmation!=='RESET'} data-action="maintenance.reset" onClick={()=>act('maintenance.reset',{parts:resetParts,apply:true,confirmation:draft.resetConfirmation})}>Apply selected reset</button></div>}{state.maintenance?.retained&&<p className="a-caption a-wrap">Original files retained at: {state.maintenance.retained}</p>}</SettingsGroup>
 </div>;
}
