import React,{useRef,useState,useEffect} from 'react';
import {SettingsActions} from './settings-layout';
import {ResultNotice} from './settings-ui';
export function NotificationSettings({state,act}){
 const notify=state.notificationSettings||{},draft=state.view?.maintenanceDraft||{};
 const [topic,setTopic]=useState(''),[token,setToken]=useState(''),[pending,setPending]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const edits=useRef({topic:0,token:0}),saving=useRef(false);
 const set=patch=>{act('view.update',{patch:{maintenanceDraft:{...draft,...patch}}})};
 const changeTopic=value=>{edits.current.topic++;setTopic(value)};
 const enabled=draft.notifyEnabled??notify.enabled??false,server=draft.notifyServer??notify.server??'https://ntfy.sh';
 const operation=state.actionStatus?.['notifications.save'];
 useEffect(()=>{if(!pending||operation?.commandId!==pending.id||['queued','working'].includes(operation.phase))return;saving.current=false;setPending(null);if(operation.phase==='error'){setError(operation.error||'Could not save. Your entries are kept.');return}if(operation.phase==='ready'){if(edits.current.topic===pending.version.topic)setTopic('');if(edits.current.token===pending.version.token)setToken('');setNotice('Notification preferences saved.')}},[operation?.commandId,operation?.phase,pending]);
 const save=async()=>{if(saving.current)return;saving.current=true;setError('');setNotice('');const version={...edits.current};try{const result=await act('notifications.save',{patch:{desktop:draft.notifyDesktop??notify.desktop??true,server,enabled,preview:draft.notifyPreview??notify.preview??false,...(topic?{topic}:{}),...(token?{token}:{})}});if(!result?.accepted||!result.operationId)throw Error(result?.error||'Could not save. Please retry.');setPending({id:result.operationId,version})}catch(e){saving.current=false;setError(e.message)}};
 return <div className="a-notification-settings"><p className="a-everyday-intro">Know when your response is ready, wherever you’re working.</p>
 <section className="a-notification-card"><label className="a-everyday-toggle"><span><strong>On this device</strong><small>Show a browser notification when a response is ready.</small></span><input type="checkbox" checked={draft.notifyDesktop??notify.desktop??true} data-action="view.update" onChange={e=>set({notifyDesktop:e.target.checked})}/></label><p className="a-caption">Your browser also needs permission.</p><button className="a-link" data-action="notification.request" onClick={()=>act('notification.request')}>Allow browser notifications</button></section>
 <section className="a-notification-card"><label className="a-everyday-toggle"><span><strong>On another device</strong><small>{notify.enabled&&notify.topicConfigured?'Connected through ntfy.':'Get notifications on your phone with ntfy.'}</small></span><input type="checkbox" data-action="view.update" checked={enabled} onChange={e=>set({notifyEnabled:e.target.checked})}/></label>
 <details className="a-everyday-disclosure" open={enabled||undefined}><summary>{notify.topicConfigured?'Manage phone notifications':'Set up phone notifications'}</summary><div className="a-notification-steps">
 <div><h4>1. Open ntfy on your phone</h4><p><a href="https://ntfy.sh" target="_blank" rel="noreferrer">Get the ntfy app</a>, then subscribe to a topic. A topic is the name of your notification channel.</p></div>
 <div><h4>2. Use the same topic here</h4><label htmlFor="notify-topic">Topic name {notify.topicConfigured&&'(saved)'}</label><div className="a-topic-entry"><input id="notify-topic" type="password" autoComplete="off" placeholder={notify.topicConfigured?'Leave blank to keep your saved topic':'Your topic name'} value={topic} data-private="true" data-action="notifications.save" onChange={e=>changeTopic(e.target.value)}/><button className="a-soft" onClick={()=>changeTopic('amplifier-'+crypto.randomUUID().replaceAll('-','').slice(0,20))}>Create a name</button></div>{topic&&<button className="a-link" onClick={async()=>{try{await navigator.clipboard.writeText(topic);setNotice('Topic copied. Subscribe to it in ntfy.')}catch{document.getElementById('notify-topic')?.select();setNotice('Select and copy the topic, then subscribe to it in ntfy.')}}}>Copy topic name</button>}<p className="a-caption">Use an unguessable name or a protected topic. Anyone with access to the topic can read its notifications.</p></div>
 <details className="a-everyday-disclosure"><summary>Server & account</summary><div><label htmlFor="notify-server">Notification server</label><input id="notify-server" type="url" data-action="view.update" value={server} onChange={e=>set({notifyServer:e.target.value})}/><p className="a-caption">Use the same server in the ntfy app. The default is ntfy.sh.</p><label htmlFor="notify-token">Access token (optional){notify.tokenConfigured?' · saved':''}</label><input id="notify-token" type="password" autoComplete="off" data-private="true" data-action="notifications.save" value={token} placeholder={notify.tokenConfigured?'Leave blank to keep saved token':''} onChange={e=>{edits.current.token++;setToken(e.target.value)}}/><p className="a-caption">For protected topics, create a token in your ntfy account. It stays private on this host.</p></div></details>
 <label className="a-inline-checkbox"><input type="checkbox" data-action="view.update" checked={draft.notifyPreview??notify.preview??false} onChange={e=>set({notifyPreview:e.target.checked})}/>Include a response preview</label><p className="a-caption">Off by default. Notifications say your response is ready without including its content.</p>
 </div></details></section>
 <SettingsActions><button className="a-primary" disabled={!!pending||(enabled&&!topic&&!notify.topicConfigured)} data-action="notifications.save" onClick={save}>{pending?'Saving…':'Save notifications'}</button></SettingsActions>{error&&<ResultNotice phase="error" message={error}/>}<ResultNotice phase="ready" message={notice}/>
 </div>;
}
