import React,{useRef,useState} from 'react';

export function OutputSettings({session,act}){
 const [rows,setRows]=useState([]),[next,setNext]=useState(null),[unlinked,setUnlinked]=useState(false),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [kind,setKind]=useState('file'),[title,setTitle]=useState(''),[location,setLocation]=useState(''),[version,setVersion]=useState(''),[writing,setWriting]=useState(''),[variant,setVariant]=useState('document'),[parent,setParent]=useState(null),[reviewMode,setReviewMode]=useState('unstaged'),[base,setBase]=useState(''),[reviewPath,setReviewPath]=useState(''),[comment,setComment]=useState(''),[line,setLine]=useState(''),[side,setSide]=useState('right'),[commentPath,setCommentPath]=useState('');
 const inFlight=useRef(false),sid=session?.id;
 async function run(action,args,apply){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{const result=await act(action,{sessionId:sid,...args});if(!result?.accepted)throw Error('The request was not accepted.');apply?.(result.result);return result.result}catch(e){setError(e.message)}finally{inFlight.current=false;setBusy(false)}}
 const list=(offset=0,show=unlinked)=>run('outputs.list',{includeUnlinked:show,offset},value=>{setRows(old=>offset?[...old,...value.items]:value.items);setNext(value.nextOffset)});
 const read=id=>run('outputs.read',{id},setSelected);
 const create=async(action,args)=>{const saved=await run(action,args,setSelected);if(saved)await list();return saved};
 const edit=async()=>{let value=await run('outputs.read',{id:selected.id});if(!value)return;let content=value.text||'';while(value.nextOffset!==null&&value.nextOffset!==undefined){value=await run('outputs.read',{id:selected.id,offset:value.nextOffset});if(!value)return;content+=value.text||''}setWriting(content);setVariant(selected.variant||'document');setTitle(selected.title);setParent(selected.id)};
 if(!sid)return <p>Choose a conversation to inspect its outputs.</p>;
 return <section aria-label="Output relationships">
  <h3>Outputs & review</h3><p>Keep exact saved versions, their origin and review notes with this conversation.</p>
  <label className="a-inline-checkbox"><input type="checkbox" checked={unlinked} disabled={busy} onChange={e=>{setUnlinked(e.target.checked);list(0,e.target.checked)}}/>Include unlinked outputs</label>
  <button type="button" className="a-soft" disabled={busy} data-action="outputs.list" onClick={()=>list()}>Inspect outputs</button>
  {rows.map(row=><div className="a-selection-card" key={row.id}><strong>{row.title}</strong><p>{row.kind} · version {row.version} · {row.linked?'linked':'unlinked'}</p><small>{row.versionEvidence==='snapshot'?'Saved exact content':row.externalVersion?'Version reference: '+row.externalVersion:'External reference; version unknown'}</small><div className="a-dialog-actions"><button type="button" className="a-soft" disabled={busy} data-action="outputs.read" onClick={()=>read(row.id)}>Read saved output</button><button type="button" className="a-soft" disabled={busy} data-action={row.linked?'outputs.unlink':'outputs.relink'} onClick={async()=>{if(await run(row.linked?'outputs.unlink':'outputs.relink',{id:row.id,expectedRevision:row.revision})){if(selected?.id===row.id)setSelected(null);await list()}}}>{row.linked?'Unlink':'Restore link'}</button></div></div>)}
  {next!==null&&<button type="button" disabled={busy} className="a-soft" onClick={()=>list(next)}>More outputs</button>}
  {selected&&<div className="a-selection-card" aria-label="Saved output detail"><h4>{selected.title}</h4><p>{selected.versionEvidence==='snapshot'?'Immutable saved content':'External reference only; remote contents were not fetched.'}</p>{selected.text!==undefined&&<pre className="a-state-view" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{selected.text}</pre>}{selected.nextOffset!==null&&selected.nextOffset!==undefined&&<button type="button" className="a-soft" disabled={busy} onClick={()=>run('outputs.read',{id:selected.id,offset:selected.nextOffset},value=>setSelected(old=>({...value,text:old.text+value.text})))}>Read more</button>}
   {selected.downloadUrl&&<a href={selected.downloadUrl} download>Download exact version</a>}{selected.url&&<a href={selected.url} target="_blank" rel="noopener noreferrer">Open external reference</a>}<p>Origin: {selected.origin.source}{selected.origin.messageId?' · message '+selected.origin.messageId:' · no originating message supplied'}</p>{selected.sha256&&<small style={{overflowWrap:'anywhere'}}>Content hash: {selected.sha256}</small>}
   {selected.parentId&&<button type="button" className="a-link" disabled={busy} onClick={()=>read(selected.parentId)}>Read prior version</button>}{selected.evidenceIds?.map(id=><button type="button" className="a-link" key={id} disabled={busy} onClick={()=>read(id)}>Read evidence {id}</button>)}
   {selected.kind==='writing'&&<button type="button" className="a-soft" disabled={busy} onClick={edit}>Edit as a new version</button>}
   <h4>Local review notes</h4>{selected.nextCommentOffset!==null&&selected.nextCommentOffset!==undefined&&<button type="button" className="a-soft" disabled={busy} onClick={()=>run('outputs.read',{id:selected.id,commentOffset:selected.nextCommentOffset},value=>setSelected(old=>({...old,comments:[...(old.comments||[]),...value.comments],nextCommentOffset:value.nextCommentOffset})))}>More review notes</button>}{selected.comments?.map(row=><p key={row.id}>{row.path&&`${row.path}:${row.line} (${row.side}) · `}{row.body}</p>)}
   <form onSubmit={async e=>{e.preventDefault();if(await run('outputs.comment',{id:selected.id,body:comment,...(line?{path:commentPath,side,line:Number(line)}:{})})){setComment('');await read(selected.id)}}}><label htmlFor="output-comment">Review note</label><textarea id="output-comment" disabled={busy} value={comment} onChange={e=>setComment(e.target.value)} maxLength={8000}/>{selected.kind==='git_review'&&<><label htmlFor="output-comment-path">Diff file (optional)</label><input id="output-comment-path" value={commentPath} disabled={busy} onChange={e=>setCommentPath(e.target.value)}/><label htmlFor="output-comment-line">Displayed line (optional)</label><input id="output-comment-line" type="number" min="1" value={line} disabled={busy} onChange={e=>setLine(e.target.value)}/><label htmlFor="output-comment-side">Diff side</label><select id="output-comment-side" disabled={busy} value={side} onChange={e=>setSide(e.target.value)}><option value="right">Updated</option><option value="left">Original</option></select></>}<button className="a-primary" disabled={busy||!comment.trim()} data-action="outputs.comment">Save local review note</button></form><p>Review notes stay here. They are not posted to a remote service.</p>
  </div>}
  <h4>Attach an output</h4><form onSubmit={e=>{e.preventDefault();create('outputs.attach',{kind,title,...(kind==='canvas'?{canvasId:location}:['file','dataset'].includes(kind)?{path:location}:{url:location,...(version?{version}:{})})})}}><label htmlFor="output-kind">Output type</label><select id="output-kind" value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}>{['file','dataset','canvas','pull_request','external_document'].map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select><label htmlFor="output-title">Output title</label><input id="output-title" value={title} disabled={busy} maxLength={200} onChange={e=>setTitle(e.target.value)}/><label htmlFor="output-location">{kind==='canvas'?'Saved canvas ID':['file','dataset'].includes(kind)?'File in this workspace':'External URL'}</label><input id="output-location" disabled={busy} value={location} onChange={e=>setLocation(e.target.value)}/>{['pull_request','external_document'].includes(kind)&&<><label htmlFor="output-version">Version reference (optional)</label><input id="output-version" disabled={busy} value={version} onChange={e=>setVersion(e.target.value)}/></>}<button className="a-primary" disabled={busy||!title.trim()||!location.trim()} data-action="outputs.attach">Attach output</button></form>
  <h4>Reusable writing</h4><form onSubmit={async e=>{e.preventDefault();if(await create('outputs.write',{title:title||'Writing',content:writing,variant,...(parent?{parentId:parent}:{})}))setParent(null)}}><label htmlFor="writing-variant">Writing type</label><select id="writing-variant" value={variant} disabled={busy} onChange={e=>setVariant(e.target.value)}>{['document','email','chat_message','social_post','standard'].map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select><label htmlFor="writing-content">Writing content</label><textarea id="writing-content" rows={6} value={writing} disabled={busy} maxLength={100000} onChange={e=>setWriting(e.target.value)}/><p>{parent?'Saving creates a new version; the prior version remains.':'Saving keeps a copy here; it does not send or publish.'}</p><button className="a-primary" disabled={busy||!writing.trim()} data-action="outputs.write">Save writing version</button>{parent&&<button type="button" className="a-soft" onClick={()=>setParent(null)}>Start separate output</button>}</form>
  <h4>Git review</h4><form onSubmit={e=>{e.preventDefault();create('outputs.review',{mode:reviewMode,...(reviewMode==='branch'?{base}:{}),...(reviewPath?{path:reviewPath}:{})})}}><label htmlFor="review-mode">Changes to inspect</label><select id="review-mode" value={reviewMode} disabled={busy} onChange={e=>setReviewMode(e.target.value)}><option value="unstaged">Unstaged tracked changes</option><option value="staged">Staged changes</option><option value="branch">Base revision to HEAD</option></select>{reviewMode==='branch'&&<><label htmlFor="review-base">Existing base revision</label><input id="review-base" value={base} disabled={busy} onChange={e=>setBase(e.target.value)}/></>}<label htmlFor="review-path">Relative file path (optional)</label><input id="review-path" value={reviewPath} disabled={busy} onChange={e=>setReviewPath(e.target.value)}/><button className="a-primary" disabled={busy||reviewMode==='branch'&&!base.trim()} data-action="outputs.review">Save review snapshot</button></form><p>Untracked files and binary contents are excluded. This only reads changes.</p>
  {error&&<p role="alert">{error}</p>}
 </section>;
}
