import React,{useState} from 'react';

export function PortabilityControls({state,session,act}){
 const [inspection,setInspection]=useState(null),[destination,setDestination]=useState(''),[carry,setCarry]=useState(false),[reviewed,setReviewed]=useState(false),[path,setPath]=useState(''),[repository,setRepository]=useState(''),[receiptPath,setReceiptPath]=useState(''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=state.portability?.receipts||session?.portability?.receipts||[];
 const run=async(action,args={})=>{setBusy(true);setError('');try{const result=await act(action,args);if(action==='portability.inspect')setInspection(result?.result);return result;}catch(e){setError(e.message||'Transfer could not finish. Inspect the saved receipt.');}finally{setBusy(false)}};
 const inspect=()=>run('portability.inspect',session?{sessionId:session.id}:{});
 const source=session?.worktreeInspection?.repository;
 return <section className="a-settings-section" aria-label="Move task between hosts" data-part="portability">
  <h3>Move task between hosts</h3><p>Stage a private transfer, verify the destination, then release this host. Your task keeps its saved history and outputs. Moving never sends a message or retries unfinished work.</p>
  <button className="a-soft" disabled={busy} data-action="portability.inspect" onClick={inspect}>Inspect hosts and transfers</button>
  {inspection&&<><p>This host: {inspection.host.label}</p>{!Object.keys(inspection.peers||{}).length&&<p role="status">No hosts are paired. Configure trusted host keys and upgrade Foundation on both hosts before transferring.</p>}</>}
  {session&&<details><summary>Export this task</summary><p>Inspect the repository above, then choose a paired destination.</p><label htmlFor="portability-destination">Destination</label><select id="portability-destination" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose a paired host</option>{Object.entries(inspection?.peers||{}).map(([id,peer])=><option key={id} value={id}>{peer.label||id}</option>)}</select>
   <label className="a-inline-checkbox"><input type="checkbox" checked={carry} onChange={e=>setCarry(e.target.checked)}/>Include staged, unstaged and untracked work</label>
   <p className="a-caption">Ignored files and local settings stay here. Export stops if a bound is exceeded or recognizable credentials are found. Review the selected history, outputs and files for private credentials before continuing.</p>
   <label className="a-inline-checkbox"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed this task’s transfer contents</label>
   <button className="a-primary" disabled={busy||!destination||!source||!reviewed||session.configurationBusy} data-action="portability.export" onClick={()=>run('portability.export',{sessionId:session.id,destination,sourceRevision:source.sourceRevision,expectedExecutionRevision:session.executionRevision||0,mode:carry?'carry_dirty':'clean',reviewedContent:true})}>Stage export and stop execution here</button>
  </details>}
  <details><summary>Import a staged task</summary><p>Copy the private signed package over your authenticated host connection. The destination repository must already contain its exact commit. A small provider check uses this host’s credentials.</p><label htmlFor="portability-package">Package path on this host</label><input id="portability-package" value={path} onChange={e=>setPath(e.target.value)}/><label htmlFor="portability-repository">Destination repository</label><input id="portability-repository" value={repository} onChange={e=>setRepository(e.target.value)}/><button className="a-soft" disabled={busy||!path||!repository} data-action="portability.stage" onClick={()=>run('portability.stage',{path,repository})}>Verify and stage import</button></details>
  {!!rows.length&&<><label htmlFor="portability-receipt">Signed receipt path copied from the other host</label><input id="portability-receipt" value={receiptPath} onChange={e=>setReceiptPath(e.target.value)}/><label htmlFor="portability-evidence">What did you verify?</label><input id="portability-evidence" value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Reason to cancel an unreleased export"/></>}
  {rows.map(row=><article className="a-selection-card" key={row.id} data-transfer-id={row.id}><p role="status">{row.direction==='outgoing'?'Export':'Import'} · {row.phase}</p><p className="a-state-view">Task {row.sessionId}</p>{row.package&&<p className="a-state-view">Package: {row.package}</p>}{row.receiptPath&&<p className="a-state-view">Receipt: {row.receiptPath}</p>}{row.detail&&<p>{row.detail}</p>}{(row.phase==='prepared'||row.phase==='releasing'||(row.phase==='unknown'&&row.previousPhase==='releasing'))&&<button className="a-primary" disabled={busy||!receiptPath} data-action="portability.release" onClick={()=>run('portability.release',{sessionId:row.sessionId,id:row.id,expectedRevision:row.revision,path:receiptPath})}>Release source ownership</button>}{row.direction==='incoming'&&['ready','active'].includes(row.phase)&&<button className="a-primary" disabled={busy||!receiptPath} data-action="portability.activate" onClick={()=>run('portability.activate',{sessionId:row.sessionId,id:row.id,expectedRevision:row.revision,path:receiptPath})}>{row.phase==='active'?'Verify activation receipt':'Activate on this host'}</button>}{row.phase==='unknown'&&<p>Inspect both hosts before any further action. Original data remains preserved; no work was replayed.</p>}</article>)}
  {rows.filter(row=>row.direction==='outgoing'&&(row.phase==='prepared'||(row.phase==='unknown'&&row.previousPhase==='preparing'))).map(row=><button key={'cancel-'+row.id} className="a-soft" disabled={busy||!evidence.trim()} data-action="portability.cancel" onClick={()=>run('portability.cancel',{sessionId:row.sessionId,id:row.id,expectedRevision:row.revision,evidence})}>Cancel unreleased export</button>)}
  {rows.filter(row=>row.direction==='incoming'&&['ready','unknown'].includes(row.phase)&&!row.releaseCertificate).map(row=><button key={'discard-'+row.id} className="a-soft" disabled={busy||!receiptPath} data-action="portability.discard" onClick={()=>run('portability.discard',{sessionId:row.sessionId,id:row.id,expectedRevision:row.revision,path:receiptPath})}>Retain source cancellation</button>)}
  {error&&<p role="alert">{error}</p>}
 </section>;
}
