import React,{useEffect,useRef,useState} from 'react';
import {Plus,RefreshCw,Trash2,Network} from 'lucide-react';
import {Collection,CollectionRow,OrderEditor} from './settings-collections';
import {useListFilter} from './list-filter.jsx';
import {ModelSelect} from './model-select';
import {ResultNotice} from './settings-ui';
import {updateRole,updateCandidate,blankRouting,providerConfig} from './setup-data';
const pretty=value=>JSON.stringify(value,null,2);
const busy=operation=>['queued','working','pending','running'].includes(operation?.phase);

export function RoutingSettings({state,act}){
 const shared=state.view?.routingEditor;
 const [draft,setDraft]=useState({name:'my-routing',scope:'global',matrix:null,newRole:'',...shared}),latest=useRef(draft);
 const [local,setLocal]=useState({});
 useEffect(()=>{if(shared){latest.current=shared;setDraft(shared);}},[shared]);
 const edit=patch=>{const next={...latest.current,...patch};latest.current=next;setDraft(next);act('view.update',{patch:{routingEditor:next}});};
 const setup=state.setup||{},providers=setup.providers||[],profiles=setup.matrices||[];
 const [shownProfiles,profileFilter]=useListFilter(state,act,'routing-profiles',profiles,row=>[row.name,row.description,row.source],'Filter routing profiles');
 const operation=action=>local[action]||state.actionStatus?.[action];
 const run=async(action,args={})=>{setLocal(current=>({...current,[action]:{phase:'pending'}}));try{const receipt=await act(action,args);setLocal(current=>({...current,[action]:receipt?null:{phase:'error',error:'Request could not be sent. Try again.'}}));return receipt;}catch(error){setLocal(current=>({...current,[action]:{phase:'error',error:error.message}}));}};
 useEffect(()=>{run('routing.list');},[]);
 const remember=()=>({...draft.profiles,...(draft.matrix?{[draft.profileKey||draft.name]:{matrix:draft.matrix,name:draft.name,role:draft.role,candidate:draft.candidate,rawText:draft.rawText,raw:draft.raw}}:{})});
 const choose=name=>{
  const saved=remember(),cached=saved[name];
  if(cached)edit({...cached,profileKey:name,requested:null,profiles:saved,order:null,error:'',detailOpen:false});
  else {edit({profileKey:name,requested:name,profiles:saved,order:null,error:''});run('routing.show',{name});}
 };
 useEffect(()=>{if(setup.matrix&&setup.matrix.name===latest.current.requested){const matrix=setup.matrix;edit({matrix,name:matrix.name,profileKey:matrix.name,requested:null,rawText:pretty(matrix),raw:false,role:Object.keys(matrix.roles||{})[0],candidate:0,detailOpen:false,error:''});}},[setup.matrix]);
 useEffect(()=>{if(!latest.current.matrix&&!latest.current.requested&&profiles.length)choose(setup.active||profiles[0].name);},[profiles]);
 const matrix=draft.matrix||blankRouting(draft.name),roles=Object.entries(matrix.roles||{}),role=matrix.roles?.[draft.role]?draft.role:roles[0]?.[0],definition=matrix.roles?.[role],candidates=definition?.candidates||[],index=Math.min(draft.candidate||0,Math.max(0,candidates.length-1)),candidate=candidates[index];
 const [shownRoles,roleFilter]=useListFilter(state,act,'routing-roles',roles,([key,value])=>[key,value.description,...(value.candidates||[]).flatMap(c=>[c.provider,c.model])],'Filter task roles');
 const change=next=>edit({matrix:next,rawText:pretty(next),error:''});
 const changeCandidate=patch=>change(updateCandidate(matrix,role,index,patch));
 const matches=candidate?providers.filter(p=>p.id===candidate.provider||p.module==='provider-'+candidate.provider||p.module===candidate.provider):[];
 const exact=matches.find(p=>p.id===candidate?.provider),suggestions=exact?[exact]:matches;
 const models=[...new Map(suggestions.flatMap(p=>(setup.modelCatalogs?.[p.id]||[]).map(model=>[typeof model==='string'?model:model.id,model])).filter(([id])=>id)).values()];
 const entry=exact?setup.providerCatalogs?.[exact.id]:undefined;
 useEffect(()=>{const saved=state.actionStatus?.['routing.save'];if(saved?.phase==='ready'&&saved.target?.name===latest.current.name)edit({profileKey:latest.current.name});},[state.actionStatus?.['routing.save']?.updatedAt]);
 const pending=busy(operation('routing.save'))||busy(operation('routing.use'));
 return <section className="a-settings-section" data-part="routing-settings">
  <div className="a-settings-row"><p>Choose models for each role. Routing uses the first resolvable choice.</p><button className="a-icon" aria-label="Refresh routing profiles" data-action="routing.list" disabled={busy(operation('routing.list'))} onClick={()=>run('routing.list')}><RefreshCw/></button></div>
  {profileFilter}<div className="a-routing-profile-picker"><div><label htmlFor="routing-profile">Routing profile</label><select id="routing-profile" value={draft.profileKey||''} data-action="routing.show" onChange={e=>choose(e.target.value)}><option value="" disabled>Choose a profile</option>{shownProfiles.map(profile=><option key={profile.name} value={profile.name}>{profile.name}{profile.active||setup.active===profile.name?' · active':''}</option>)}{draft.profileKey&&!shownProfiles.some(p=>p.name===draft.profileKey)&&<option value={draft.profileKey}>{draft.name} · draft</option>}</select></div><button className="a-soft" disabled={!profiles.some(profile=>profile.name===draft.profileKey)||setup.active===draft.profileKey||pending||!!draft.requested} data-action="routing.use" onClick={()=>run('routing.use',{name:draft.profileKey,scope:draft.scope})}>Use profile</button><button className="a-soft" data-action="view.update" onClick={()=>{const matrix=blankRouting();edit({profiles:remember(),matrix,name:matrix.name,profileKey:'new:'+Date.now(),requested:null,role:'general',candidate:0,rawText:pretty(matrix),order:null,detailOpen:false});}}><Plus/>New profile</button></div>
  {draft.requested&&<ResultNotice phase={operation('routing.show')?.phase==='error'?'error':'working'} message={operation('routing.show')?.error||'Opening '+draft.requested+'…'}/>}
  {draft.requested&&operation('routing.show')?.phase==='error'&&<button className="a-soft" data-action="routing.show" onClick={()=>run('routing.show',{name:draft.requested})}>Retry opening profile</button>}
  {['routing.list','routing.use'].map(action=>operation(action)?.phase==='error'&&<ResultNotice key={action} phase="error" message={operation(action).error}/>)}
  {draft.matrix&&<><p className="a-caption">{profiles.find(p=>p.name===draft.profileKey)?.description}</p><div className="a-form-grid"><div><label htmlFor="routing-name">Custom profile name</label><input id="routing-name" value={draft.name} data-action="view.update" onChange={e=>edit({name:e.target.value})}/></div><div><label htmlFor="routing-scope">Save for</label><select id="routing-scope" value={draft.scope} data-action="view.update" onChange={e=>edit({scope:e.target.value})}><option value="global">All workspaces</option><option value="project">This project</option><option value="local">This workspace</option></select></div></div>
  {draft.order?<OrderEditor title={role+' preference order'} description="Place your preferred choice first. Routing selects the first resolvable match; this is not a retry chain for failed API calls." items={candidates.map((c,i)=>({id:String(i),label:c.model||'Choose a model',description:c.provider||'Choose a provider'}))} ids={draft.order.ids} onChange={ids=>edit({order:{...draft.order,ids}})} onCancel={()=>edit({order:null})} onSave={()=>{const next=updateRole(matrix,role,{candidates:draft.order.ids.map(id=>candidates[Number(id)])});edit({order:null,matrix:next,rawText:pretty(next),candidate:0});}}/>:
   <Collection label="roles" detailOpen={!!draft.detailOpen} onBack={()=>edit({detailOpen:false})} list={<>{roleFilter}{shownRoles.map(([key,value])=><CollectionRow key={key} id={key} label={key} description={value.description||`${value.candidates?.length||0} choices`} selected={key===role} onSelect={()=>edit({role:key,candidate:0,detailOpen:true,candidateRaw:false})}/>)}</>}>
    {definition&&<><div className="a-settings-row"><h4>{role}</h4><button className="a-icon a-danger" aria-label={'Remove role '+role} disabled={['general','fast'].includes(role)} data-action="view.update" onClick={()=>{const next={...matrix,roles:{...matrix.roles}};delete next.roles[role];change(next);}}><Trash2/></button></div>
    <label htmlFor="routing-description">Role description</label><input id="routing-description" aria-label={role+' description'} value={definition.description||''} placeholder="Describe this role" data-action="view.update" onChange={e=>change(updateRole(matrix,role,{description:e.target.value}))}/>
    <div className="a-collection-toolbar"><span>{candidates.length} ordered choices</span><button className="a-soft" disabled={candidates.length<2} data-action="view.update" onClick={()=>edit({order:{ids:candidates.map((_,i)=>String(i))}})}>Preference order</button></div>
    <div className="a-routing-candidates">{candidates.map((c,i)=><CollectionRow key={i} id={String(i)} label={`${i+1}. ${c.model||'Choose a model'}`} description={c.provider||'Choose a provider'} selected={i===index} onSelect={()=>edit({candidate:i,candidateRaw:false})}/>)}</div>
    {candidate&&<div className="a-routing-selected"><div className="a-settings-row"><h4>Choice {index+1}</h4><button className="a-icon a-danger" aria-label={`Remove ${role} candidate ${index+1}`} data-action="view.update" onClick={()=>change(updateRole(matrix,role,{candidates:candidates.filter((_,i)=>i!==index)}))}><Trash2/></button></div>
     <label htmlFor="routing-candidate-provider">Provider or connection name</label><input id="routing-candidate-provider" aria-label={`${role} provider ${index+1}`} list="routing-provider-options" value={candidate.provider||''} placeholder="For example, anthropic or opus" data-action="view.update" onChange={e=>changeCandidate({provider:e.target.value})}/><datalist id="routing-provider-options">{[...new Set(providers.flatMap(p=>[p.id,p.module.replace(/^provider-/, '')]))].map(name=><option key={name} value={name}/>)}</datalist>
     <p className="a-caption">Use a provider family for a portable profile, or a connection name for a specific account and configuration.</p>
     <label htmlFor={`routing-${role}-${index}`}>Model ID or pattern</label><ModelSelect editable catalogKey={candidate.provider} id={`routing-${role}-${index}`} label={`${role} model ${index+1}`} value={candidate.model||''} entry={entry} models={models} state={state} act={act} placeholder="Model ID or pattern, e.g. claude-sonnet-*" onChange={model=>changeCandidate({model})}/>
     <p className="a-caption">Patterns are resolved by the routing module. Model lists are suggestions and do not limit what you can enter.{suggestions.length>0?' Suggestions from '+suggestions.map(p=>p.id).join(', ')+'.':''}</p>
     <button className="a-link" data-action="view.update" aria-expanded={!!draft.candidateRaw} onClick={()=>edit({candidateRaw:!draft.candidateRaw,candidateText:pretty(candidate)})}>Edit choice configuration</button>
     {draft.candidateRaw&&<><textarea aria-label="Choice configuration JSON" className="a-json-editor" value={draft.candidateText} data-action="view.update" onChange={e=>edit({candidateText:e.target.value})}/><button className="a-soft" data-action="view.update" onClick={()=>{try{const value=providerConfig(draft.candidateText);if(!value.provider||!value.model)throw new Error('Include a provider and model.');const next=[...candidates];next[index]=value;change(updateRole(matrix,role,{candidates:next}));}catch(error){edit({error:error.message});}}}>Apply choice configuration</button></>}
    </div>}
    <button className="a-link" data-action="view.update" onClick={()=>{const next=updateRole(matrix,role,{candidates:[...candidates,{provider:'',model:''}]});edit({matrix:next,rawText:pretty(next),candidate:candidates.length,candidateRaw:false});}}><Plus/>Add fallback model</button>
    </>}
   </Collection>}
  <div className="a-routing-add"><input aria-label="New routing role" list="routing-role-options" value={draft.newRole||''} placeholder="Add a role" data-action="view.update" onChange={e=>edit({newRole:e.target.value})}/><datalist id="routing-role-options">{(setup.roles||[]).map(key=><option value={key} key={key}/>)}</datalist><button className="a-soft" disabled={!draft.newRole?.trim()||!!matrix.roles?.[draft.newRole.trim()]} data-action="view.update" onClick={()=>{const name=draft.newRole.trim(),next=updateRole(matrix,name,{description:'',candidates:[{provider:'',model:''}]});edit({matrix:next,rawText:pretty(next),newRole:'',role:name,candidate:0,detailOpen:true});}}><Plus/>Add role</button></div>
  <button className="a-link" aria-expanded={!!draft.raw} data-action="view.update" onClick={()=>edit({raw:!draft.raw,rawText:pretty(matrix)})}>{draft.raw?'Hide':'Show'} full profile JSON</button>{draft.raw&&<><textarea aria-label="Routing matrix JSON" className="a-json-editor" spellCheck={false} value={draft.rawText} data-action="view.update" onChange={e=>edit({rawText:e.target.value})}/><button className="a-soft" data-action="view.update" onClick={()=>{try{const value=providerConfig(draft.rawText);if(!value.roles||typeof value.roles!=='object'||Array.isArray(value.roles))throw new Error('A profile needs a roles object.');change(value);}catch(error){edit({error:error.message});}}}>Update draft from JSON</button></>}
  {draft.error&&<p className="a-danger" role="alert">{draft.error}</p>}
  <div className="a-dialog-actions"><button className="a-primary" disabled={pending||!!draft.requested||!!draft.order||!draft.name.trim()||!roles.length||roles.some(([,value])=>!value.candidates?.length||value.candidates.some(c=>!c.provider||!c.model))} data-action="routing.save" onClick={()=>run('routing.save',{name:draft.name.trim(),matrix:{...matrix,name:draft.name.trim()},scope:draft.scope,activate:true})}><Network/>{setup.active===draft.name?'Save active profile':'Save and use profile'}</button></div><p className="a-caption">General and fast roles are required. Saving applies to future conversation preparation.</p>
  <ResultNotice phase={operation('routing.save')?.phase} message={operation('routing.save')?.error||(busy(operation('routing.save'))?'Saving routing profile…':operation('routing.save')?.phase==='ready'?'Routing profile saved and selected.':'')}/>
  </>}
 </section>;
}
