import {NativeProviderSettings} from './native-provider-settings';
import {CapacityControls} from './capacity';
import {ScheduleControls} from './schedules';
import {TaskContinuity} from './task-continuity';
import {WorktreeControls} from './worktrees';
import {PortabilityControls} from './portability';
import {ActivityRegion} from './activity-region';
import React,{useState,useEffect,useRef,useLayoutEffect} from 'react';
import {RefreshCw,Check,Play,Trash2,Target,SlidersHorizontal,Code2,BookOpen,Monitor} from 'lucide-react';
import {Markdown} from './markdown';
import {usageLabel} from './timeline-data';
import {ArtifactRuntime} from './artifact-runtime';
const pretty=value=>JSON.stringify(value,null,2);
const defaults={tab:'overview',goalCondition:'',goalMaxTurns:'',mode:'',maxIterations:'',contextTokens:'',tool:'',toolArgs:'{}',clearConfirm:false};
export function RuntimeSettings({state,session,act,computerControls}){
 const shared=state.view?.runtimeDraft,root=useRef(null);
 const [draft,setDraft]=useState({...defaults,...shared});
 useEffect(()=>{if(shared)setDraft(current=>({...current,...shared}))},[shared]);
 const edit=patch=>{setDraft(current=>({...current,...patch}));act('view.update',{patch:{runtimeDraft:patch}})};
 useLayoutEffect(()=>{if(!draft.section)return;const section=[...(root.current?.querySelectorAll('[data-runtime-section]')||[])].find(el=>el.dataset.runtimeSection===draft.section);section?.scrollIntoView({block:'nearest'});section?.focus({preventScroll:true})},[draft.section,draft.tab,draft.revealRevision]);
 const results=state.runtimeControl?.[session?.id]||{};
 const catalog=results['catalog.inspect']||{},modes=results['mode.list']||{},goalResult=results['goals.get']||results['goals.set']||{},budget=results['budget.get']||results['budget.set']||{},usage=results['usage.inspect'];
 const capabilities=catalog.capabilities||{},savedTask=results['task.get']?.task||session?.task;
 const management=state.management||{};
 const pending=['working','running','pending','queued'].includes(management.phase);
 const control=state.actionStatus?.['runtime.control'],operationPending=operation=>['queued','working'].includes(control?.phase)&&control?.target?.sessionId===session?.id&&control?.target?.operation===operation;
 const active=session&&['working','starting','running','stopping','busy'].includes(session.status);
 const run=(operation,args={})=>act('runtime.control',{sessionId:session.id,operation,args});
 const tools=catalog.tools||[],selectedTool=tools.find(tool=>tool.name===draft.tool),toolResult=results['tool.invoke'];
 const goalAvailable=!!capabilities.goals,modeAvailable=!!capabilities.modes;
 const currentUsage=usageLabel(usage?.usage);
 let parsedArgs={},argsError='';try{parsedArgs=JSON.parse(draft.toolArgs);if(!parsedArgs||typeof parsedArgs!=='object'||Array.isArray(parsedArgs))throw new Error('Tool arguments must be a JSON object.')}catch(error){argsError=error.message}
 const tabs=[['overview','Session',SlidersHorizontal],['direction','Goals & modes',Target],['limits','Limits & context',BookOpen],['tools','Tools & skills',Code2],['computer','Computer use',Monitor]];
 if(!session)return <PortabilityControls state={state} session={null} act={act}/>;
 return <div ref={root} className="a-runtime-settings" data-part="runtime-controls"><p>Inspect and control the active Amplifier session. Its bundle determines which capabilities are available.</p><nav className="a-settings-nav" aria-label="Session control sections">{tabs.map(([key,label,Icon])=><button key={key} className={draft.tab===key?'selected':''} data-action="view.update" onClick={()=>edit({tab:key,section:null})}><Icon/>{label}</button>)}</nav>
  <div data-runtime-section={draft.tab} tabIndex={-1}>
  {draft.tab==='computer'&&computerControls}
  {management.error&&<div className="a-alert" role="alert"><span>{management.error}</span></div>}{pending&&<p className="a-management-status" role="status"><RefreshCw className="a-progress-spinner"/>{management.detail||'Updating the session…'}</p>}
  {draft.tab==='overview'&&<><WorktreeControls session={session} act={act}/><ActivityRegion as="section" name="runtime-catalog.inspect" busy={operationPending('catalog.inspect')} className="a-settings-section"><h3>Session capabilities</h3><button className="a-soft" disabled={pending} data-action="runtime.control" onClick={()=>run('catalog.inspect')}><RefreshCw/>Inspect capabilities</button>{tools.length>0&&<div className="a-capability-counts"><span><strong>{tools.length}</strong> tools</span><span><strong>{Object.keys(catalog.agents||{}).length}</strong> agents</span><span><strong>{(catalog.skills||[]).length}</strong> skills</span></div>}{Object.keys(capabilities).length>0&&<div className="a-capability-tags">{Object.entries(capabilities).map(([name,value])=><span key={name} className={value?'available':'unavailable'}>{name} · {value?'available':'unavailable'}</span>)}</div>}</ActivityRegion><ActivityRegion as="section" name="runtime-usage.inspect" busy={operationPending('usage.inspect')} className="a-settings-section"><h3>Usage & context</h3><button className="a-soft" disabled={pending} data-action="runtime.control" onClick={()=>run('usage.inspect')}><RefreshCw/>Refresh usage</button>{usage&&<><p className="a-caption">{usage.calls??0} model calls · {usage.messages??0} messages · {usage.userTurns??0} user turns</p>{currentUsage&&<p title={currentUsage.title}>{currentUsage.text}</p>}<p className="a-caption">{usage.contextCharacters?.toLocaleString?.()??'Unknown'} context characters. Character counts are not token counts.</p></>}</ActivityRegion></>}
  {draft.tab==='direction'&&<><TaskContinuity state={state} session={session} act={act}/><ScheduleControls session={session} act={act}/>{!savedTask&&<ActivityRegion as="section" name="runtime-goals.get" busy={operationPending('goals.get')} className="a-settings-section"><h3>Goal</h3><p>Give the session an explicit condition to work toward and an optional turn limit.</p>{!goalAvailable&&<p className="a-caption">{Object.keys(capabilities).length?'This bundle does not expose a goal controller.':'Inspect session capabilities first to check goal support.'}</p>}<button className="a-soft" disabled={!goalAvailable||pending} data-action="runtime.control" onClick={()=>run('goals.get')}><RefreshCw/>Load current goal</button>{goalResult.goal&&<div className="a-selection-card"><p><strong>{goalResult.goal.condition}</strong></p><small>{goalResult.goal.turns_used??0} turns used{goalResult.goal.cap?` of ${goalResult.goal.cap}`:''}</small>{goalResult.goal.last_reason&&<p>{goalResult.goal.last_reason}</p>}</div>}<label htmlFor="runtime-goal">Goal condition</label><textarea id="runtime-goal" value={draft.goalCondition} data-action="view.update" onChange={e=>edit({goalCondition:e.target.value})} placeholder="The requested changes are implemented and the checks pass."/><label htmlFor="runtime-goal-turns">Maximum continuation turns (optional)</label><input id="runtime-goal-turns" type="number" min="1" value={draft.goalMaxTurns} data-action="view.update" onChange={e=>edit({goalMaxTurns:e.target.value})}/><div className="a-dialog-actions"><button className="a-primary" disabled={!goalAvailable||!draft.goalCondition.trim()||active||pending||(draft.goalMaxTurns!==''&&(!Number.isInteger(Number(draft.goalMaxTurns))||Number(draft.goalMaxTurns)<1))} data-action="runtime.control" onClick={()=>run('goals.set',{condition:draft.goalCondition.trim(),maxTurns:draft.goalMaxTurns?Number(draft.goalMaxTurns):null})}><Target/>Set goal</button><button className="a-soft" disabled={!goalAvailable||active||pending} data-action="runtime.control" onClick={()=>run('goals.clear')}>Clear goal</button></div></ActivityRegion>}
  <ActivityRegion as="section" name="runtime-mode.list" busy={operationPending('mode.list')} className="a-settings-section"><h3>Mode</h3><p>Use a mode supplied by your bundle to adjust how the session works.</p><button className="a-soft" disabled={!modeAvailable||pending} data-action="runtime.control" onClick={()=>run('mode.list')}><RefreshCw/>Load modes</button>{modes.active&&<p className="a-caption">Active: {typeof modes.active==='string'?modes.active:pretty(modes.active)}</p>}<label htmlFor="runtime-mode">Mode</label><select id="runtime-mode" value={draft.mode} data-action="view.update" onChange={e=>edit({mode:e.target.value})}><option value="">Choose a mode</option>{(modes.modes||[]).map(mode=><option value={mode.name} key={mode.name}>{mode.name}{mode.description?` — ${mode.description}`:''}</option>)}</select><div className="a-dialog-actions"><button className="a-primary" disabled={!modeAvailable||!draft.mode||active||pending} data-action="runtime.control" onClick={()=>run('mode.set',{name:draft.mode})}><Check/>Apply mode</button><button className="a-soft" disabled={!modeAvailable||active||pending} data-action="runtime.control" onClick={()=>run('mode.clear')}>Clear mode</button></div>{!modeAvailable&&<p className="a-caption">{Object.keys(capabilities).length?'This bundle does not expose modes.':'Inspect session capabilities first to check mode support.'}</p>}</ActivityRegion></>}
  {draft.tab==='limits'&&<><CapacityControls key={session.id} session={session} act={act}/><NativeProviderSettings results={results} run={run} busy={pending} active={active}/><ActivityRegion as="section" name="runtime-budget.get" busy={operationPending('budget.get')} className="a-settings-section"><h3>Session limits</h3><p>Adjust the active session’s model-turn and context limits.</p><button className="a-soft" disabled={pending} data-action="runtime.control" onClick={()=>run('budget.get')}><RefreshCw/>Load limits</button>{Object.keys(budget).length>0&&<p className="a-caption">Current: {budget.maxIterations===-1?'unlimited':budget.maxIterations??'unknown'} model turns · {budget.contextTokens??'unknown'} context tokens. {budget.contextNote||''}</p>}<div className="a-form-grid"><div><label htmlFor="runtime-max-iterations">Maximum model turns (−1 for unlimited)</label><input id="runtime-max-iterations" type="number" min="-1" data-action="view.update" value={draft.maxIterations} placeholder={String(budget.maxIterations??'')} onChange={e=>edit({maxIterations:e.target.value})}/></div><div><label htmlFor="runtime-context-tokens">Context token budget</label><input id="runtime-context-tokens" type="number" min="1" data-action="view.update" value={draft.contextTokens} placeholder={String(budget.contextTokens??'')} onChange={e=>edit({contextTokens:e.target.value})}/></div></div><div className="a-dialog-actions"><button className="a-primary" disabled={active||pending||(!draft.maxIterations&&!draft.contextTokens)||(draft.maxIterations!==''&&(!Number.isInteger(Number(draft.maxIterations))||(Number(draft.maxIterations)!==-1&&Number(draft.maxIterations)<1)))||(draft.contextTokens!==''&&(!Number.isInteger(Number(draft.contextTokens))||Number(draft.contextTokens)<1))} data-action="runtime.control" onClick={()=>run('budget.set',{...(draft.maxIterations!==''?{maxIterations:Number(draft.maxIterations)}:{}),...(draft.contextTokens!==''?{contextTokens:Number(draft.contextTokens)}:{})})}><Check/>Update limits</button></div></ActivityRegion><section className="a-settings-section"><h3>Clear model context</h3><p>Clear the model’s active context. The saved conversation remains in the app.</p><label className="a-inline-checkbox"><input type="checkbox" checked={draft.clearConfirm} data-action="view.update" onChange={e=>edit({clearConfirm:e.target.checked})}/>I want to clear the active model context.</label><button className="a-soft a-danger" disabled={!draft.clearConfirm||active||pending} data-action="runtime.control" onClick={()=>run('context.clear')}><Trash2/>Clear context</button></section></>}
  {draft.tab==='tools'&&<><ActivityRegion as="section" name="runtime-catalog.inspect" busy={operationPending('catalog.inspect')} className="a-settings-section"><div className="a-settings-row"><div><h3>Tools</h3><p>Inspect the actual tool schema, then invoke it through the session’s permission checks.</p></div><button className="a-icon" aria-label="Refresh tool catalog" disabled={pending} data-action="runtime.control" onClick={()=>run('catalog.inspect')}><RefreshCw/></button></div><label htmlFor="runtime-tool">Tool</label><select id="runtime-tool" data-action="view.update" value={draft.tool} onChange={e=>edit({tool:e.target.value,toolArgs:'{}'})}><option value="">Choose a tool</option>{tools.map(tool=><option key={tool.name} value={tool.name}>{tool.name}</option>)}</select>{selectedTool&&<><p>{selectedTool.description}</p><pre className="a-state-view">{pretty(selectedTool.inputSchema)}</pre><label htmlFor="runtime-tool-arguments">Arguments (JSON)</label><textarea id="runtime-tool-arguments" className="a-json-editor" spellCheck={false} value={draft.toolArgs} data-action="view.update" onChange={e=>edit({toolArgs:e.target.value})}/>{argsError&&<p className="a-danger">{argsError}</p>}<button className="a-primary" disabled={!!argsError||active||pending} data-action="runtime.control" onClick={()=>run('tool.invoke',{name:draft.tool,arguments:parsedArgs})}><Play/>Run tool</button></>}{toolResult&&<div className="a-tool-result"><h4>Tool result</h4>{toolResult.result?.error&&<p className="a-danger">{typeof toolResult.result.error==='string'?toolResult.result.error:pretty(toolResult.result.error)}</p>}<Markdown text={typeof toolResult.result?.output==='string'?toolResult.result.output:pretty(toolResult.result?.output??toolResult)}/></div>}</ActivityRegion><section className="a-settings-section"><h3>Skills</h3>{!(catalog.skills||[]).length?<p>Inspect capabilities to see skills available in this bundle.</p>:<ul className="a-catalog-list">{catalog.skills.map(skill=><li key={skill.name}><strong>{skill.name}</strong><p>{skill.description}</p></li>)}</ul>}<p className="a-caption">Ask Amplifier to use a skill in the conversation, or select its loading tool above to inspect the exact arguments.</p></section><section className="a-settings-section"><h3>Available agents</h3><ul className="a-catalog-list">{Object.entries(catalog.agents||{}).map(([name,agent])=><li key={name}><strong>{name}</strong><p>{agent.description||agent.meta?.description||''}</p></li>)}</ul></section></>}
  {draft.tab==='overview'&&<ArtifactRuntime sessionId={session.id} act={act}/>}
  {draft.tab==='overview'&&<PortabilityControls state={state} session={session} act={act}/>}
  {active&&<p className="a-caption">Changes and direct tool calls become available when this session and its workers are idle.</p>}
 </div></div>;
}
