import React,{useState} from 'react';

const parts=(value,timezone)=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(row=>[row.type,row.value]));
const localFields=(value,timezone)=>{const p=parts(value,timezone);return {startDate:`${p.year}-${p.month}-${p.day}`,localTime:`${p.hour}:${p.minute}`}};
export function ScheduleControls({session,act}){
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 const empty=()=>({prompt:'',kind:'monitor',recurrence:'daily',timezone:zone,...localFields(Date.now()+3600000,zone),intervalMinutes:60,weekdays:[0],missedRunPolicy:'latest',notificationPolicy:'changes'});
 const [draft,setDraft]=useState(empty),[editing,setEditing]=useState(null),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[evidence,setEvidence]=useState('');
 const edit=patch=>{setDraft(value=>({...value,...patch}));setReview(null)};
 const config=()=>({prompt:draft.prompt,kind:draft.kind,missedRunPolicy:draft.missedRunPolicy,notificationPolicy:draft.notificationPolicy,spec:{kind:draft.recurrence,timezone:draft.timezone,startDate:draft.startDate,localTime:draft.localTime,...(draft.recurrence==='interval'?{intervalSeconds:Number(draft.intervalMinutes)*60}:{}),...(draft.recurrence==='weekly'?{weekdays:draft.weekdays}:{})}});
 const run=async(action,args={})=>{setBusy(true);try{return await act(action,{sessionId:session.id,...args})}finally{setBusy(false)}};
 const load=record=>{setEditing(record);setReview(null);setDraft({prompt:record.prompt,kind:record.kind,recurrence:record.spec.kind,timezone:record.spec.timezone,...(record.spec.startAt?localFields(record.spec.startAt,record.spec.timezone):{startDate:record.spec.startDate,localTime:record.spec.localTime}),intervalMinutes:(record.spec.intervalSeconds||3600)/60,weekdays:record.spec.weekdays||[0],missedRunPolicy:record.missedRunPolicy,notificationPolicy:record.notificationPolicy})};
 const save=async()=>{const result=await run(editing?'schedule.update':'schedule.create',{...config(),...(editing?{id:editing.id}:{}),expectedRevision:editing?.revision||0,previewHash:review.previewHash});if(result?.accepted){setEditing(null);setReview(null);setDraft(empty())}};
 return <section className="a-settings-section" aria-label="Scheduled work" data-part="schedules"><h3>Scheduled work</h3><p>Continue this saved task later or monitor it on a schedule. Each run uses the task’s normal tool permissions. Stops and task corrections require schedule review.</p>
  <button className="a-soft" data-action="schedule.list" disabled={busy} onClick={()=>run('schedule.list')}>Refresh schedules</button>
  {(session.schedules||[]).map(record=><article className="a-selection-card" key={record.id} data-schedule-id={record.id}><p><strong>{record.prompt}</strong></p><p role="status">Schedule {record.status.replaceAll('_',' ')}</p>{record.nextDue&&record.status==='active'&&<p>Next: {new Date(record.nextDue*1000).toLocaleString(undefined,{timeZone:record.spec.timezone})} ({record.spec.timezone})</p>}{record.status==='needs_review'&&record.reviewReason&&<p role="alert">{record.reviewReason}</p>}<p className="a-caption">Notifications: {record.notificationPolicy==='changes'?'changes and failures':record.notificationPolicy==='always'?'every result and failure':'failures only'} · Missed runs: {record.missedRunPolicy==='skip'?'skip after one minute':'run only the latest occurrence'}</p><div className="a-dialog-actions">{record.status!=='cancelled'&&<><button className="a-soft" onClick={()=>load(record)}>Review schedule</button>{record.status==='active'&&<button className="a-soft" data-action="schedule.pause" disabled={busy} onClick={()=>run('schedule.pause',{id:record.id,expectedRevision:record.revision})}>Pause schedule</button>}<button className="a-soft" data-action="schedule.cancel" disabled={busy} onClick={()=>run('schedule.cancel',{id:record.id,expectedRevision:record.revision})}>Cancel schedule</button></>}</div>{record.runs?.length>0&&<details><summary>Recent runs ({record.runs.length})</summary>{record.runs.map(row=><div key={row.id} data-run-id={row.id}><p><strong>{row.phase}</strong> · {new Date(row.dueAt*1000).toLocaleString()}</p><p>{row.detail}</p>{row.notificationDecision&&<p className="a-caption">{row.notificationDecision.notify?'Notification requested':'Stayed quiet'} · evidence: {row.notificationDecision.source.replaceAll('_',' ')}</p>}{row.report&&<details><summary>Reported evidence</summary><p>{row.report.detail}</p>{'values' in row.report&&<pre className="a-state-view">{JSON.stringify(row.report.values,null,2)}</pre>}</details>}{row.phase==='unknown'&&<><label htmlFor={'schedule-evidence-'+record.id}>Reconciliation evidence</label><textarea id={'schedule-evidence-'+record.id} value={evidence} onChange={e=>setEvidence(e.target.value)}/><p className="a-caption">These actions record your finding and never send the old input again. Review the schedule separately to enable future runs.</p><div className="a-dialog-actions">{['abandoned','completed'].map(resolution=><button className="a-soft" key={resolution} disabled={busy||!evidence.trim()} data-action="schedule.reconcile" onClick={()=>run('schedule.reconcile',{runId:row.id,expectedRevision:row.revision,resolution,evidence:evidence.trim()})}>Mark run {resolution}</button>)}</div></>}</div>)}</details>}</article>)}
  <h4>{editing?'Review this schedule':'New schedule'}</h4>
  <label htmlFor="schedule-prompt">Saved instructions</label><textarea id="schedule-prompt" value={draft.prompt} onChange={e=>edit({prompt:e.target.value})}/>
  <div className="a-form-grid"><div><label htmlFor="schedule-kind">Purpose</label><select id="schedule-kind" value={draft.kind} onChange={e=>edit({kind:e.target.value})}><option value="monitor">Monitor changes</option><option value="task">Continue the task</option></select></div><div><label htmlFor="schedule-recurrence">Repeat</label><select id="schedule-recurrence" value={draft.recurrence} onChange={e=>edit({recurrence:e.target.value})}><option value="once">Once</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="interval">At an interval</option></select></div><div><label htmlFor="schedule-date">Start date</label><input id="schedule-date" type="date" value={draft.startDate} onChange={e=>edit({startDate:e.target.value})}/></div><div><label htmlFor="schedule-time">Local time</label><input id="schedule-time" type="time" value={draft.localTime} onChange={e=>edit({localTime:e.target.value})}/></div></div>
  <label htmlFor="schedule-zone">Timezone</label><input id="schedule-zone" value={draft.timezone} onChange={e=>edit({timezone:e.target.value})}/>
  {draft.recurrence==='interval'&&<><label htmlFor="schedule-interval">Repeat every (minutes)</label><input id="schedule-interval" type="number" min="1" value={draft.intervalMinutes} onChange={e=>edit({intervalMinutes:e.target.value})}/></>}
  {draft.recurrence==='weekly'&&<div>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((label,index)=><label className="a-inline-checkbox" key={label}><input type="checkbox" checked={draft.weekdays.includes(index)} onChange={e=>edit({weekdays:e.target.checked?[...draft.weekdays,index]:draft.weekdays.filter(day=>day!==index)})}/>{label}</label>)}</div>}
  <label htmlFor="schedule-missed">If the app misses a run</label><select id="schedule-missed" value={draft.missedRunPolicy} onChange={e=>edit({missedRunPolicy:e.target.value})}><option value="latest">Run only the latest missed occurrence</option><option value="skip">Skip occurrences more than a minute late</option></select>
  <label htmlFor="schedule-notify">Notify me</label><select id="schedule-notify" value={draft.notificationPolicy} onChange={e=>edit({notificationPolicy:e.target.value})}><option value="changes">For changes and failures</option><option value="always">After every result and failure</option><option value="failures_only">For failures only</option></select>
  <button className="a-soft" disabled={busy||!draft.prompt.trim()} data-action="schedule.preview" onClick={async()=>{const response=await run('schedule.preview',config());setReview(response?.result||null)}}>Preview schedule</button>
  {review&&<div className="a-selection-card" data-part="schedule-preview"><h4>Confirm scheduled work</h4><p>{review.binding.prompt}</p><ul>{review.occurrences.map(row=><li key={row.utc}>{new Date(row.dueAt*1000).toLocaleString(undefined,{timeZone:review.binding.spec.timezone})} ({review.binding.spec.timezone})</li>)}</ul><p className="a-caption">{review.daylightSaving}</p><p>Approval applies to this saved prompt and schedule. Normal tool permissions still apply during each run.</p><button className="a-primary" data-action={editing?'schedule.update':'schedule.create'} disabled={busy||!review.occurrences.length} onClick={save}>Save and activate schedule</button></div>}
 </section>
}
