import React from 'react';
import voiceCatalog from '../../amplifier_web/voice_options.json' with {type:'json'};
export function VoiceSettings({state,act}){
 const settings=state.settings||{},model=voiceCatalog.models.find(row=>row.id===settings.preferredVoice)||voiceCatalog.models[0];
 const voice=model.voices.find(row=>row.id===settings.voiceName)||model.voices[0];
 const [error,setError]=React.useState('');
 const change=async patch=>{setError('');try{const result=await act('settings.update',{patch});if(result?.accepted===false)throw Error(result.error||'Could not save voice settings.')}catch(error){setError(error.message)}};
 return <div className="a-voice-settings"><label htmlFor="preferred-voice">Voice model</label><select id="preferred-voice" data-action="settings.update" value={model.id} onChange={e=>{const next=voiceCatalog.models.find(row=>row.id===e.target.value);change({preferredVoice:next.id,voiceName:next.voices.some(row=>row.id===voice.id)?voice.id:'marin'})}}>{voiceCatalog.models.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><p className="a-caption">{model.description}</p>
 <label htmlFor="speaking-voice">Speaking voice</label><select id="speaking-voice" data-action="settings.update" value={voice.id} onChange={e=>change({voiceName:e.target.value})}>{model.voices.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><p className="a-voice-description">{voice.description}</p>
 {model.id==='gpt-realtime-2.1'&&<label className="a-inline-checkbox"><input type="checkbox" checked={settings.voiceInterruptions!==false} data-action="settings.update" onChange={e=>change({voiceInterruptions:e.target.checked})}/>Let me interrupt by speaking</label>}
 <p className="a-caption">Changes apply to your next call. Start a call using the voice button in a conversation. Your browser manages microphone access.</p>
 <details className="a-everyday-disclosure"><summary>About these voices</summary><div><p>Available voices depend on the model. Regional descriptions come from OpenAI; voices can speak other languages too.</p><a href={model.source} target="_blank" rel="noreferrer">Voice guide from OpenAI</a></div></details>{error&&<p role="alert" className="a-danger">{error}</p>}</div>;
}
export function InstallAppSettings(){return <><p><a href="/setup/terminal" target="_blank" rel="noopener noreferrer">Install the Terminal app on this computer</a> to connect to this Unified service. The setup page handles the client and its saved connection.</p><p>In Edge or Chrome, choose the install icon in the address bar or Install this site as an app in the browser menu. In Safari on Mac, use File → Add to Dock. On iPhone or iPad, use Share → Add to Home Screen.</p><p>Keep the Python service running on the host computer. Installation gives this interface its own window; the service still runs your conversations and tools.</p><p className="a-caption">Use localhost on this computer, or a trusted HTTPS address on other devices. Your saved chats and canvas artifacts stay on the host.</p></>;}
