import React from 'react';
import voiceCatalog from '../../amplifier_web/voice_options.json' with {type:'json'};
export function VoiceSettings({state,act}){
 const settings=state.settings||{},model=voiceCatalog.models.find(row=>row.id===settings.preferredVoice)||voiceCatalog.models[0];
 const voice=model.voices.find(row=>row.id===settings.voiceName)||model.voices[0],config=state.voiceConfiguration;
 const [error,setError]=React.useState(''),[key,setKey]=React.useState(''),[source,setSource]=React.useState(''),[saving,setSaving]=React.useState(false),[search,setSearch]=React.useState(''),[choosing,setChoosing]=React.useState(false),[sample,setSample]=React.useState(null),[loading,setLoading]=React.useState('');
 const chooser=React.useRef(null);
 React.useLayoutEffect(()=>{if(choosing){chooser.current?.focus();chooser.current?.scrollIntoView({block:'start'})}},[choosing]);
 const sampleUrl=React.useRef(null);
 const audio=React.useRef(null),alive=React.useRef(true),generation=React.useRef(0);
 React.useEffect(()=>{alive.current=true;act('voice.configuration').catch(e=>setError(e.message));return()=>{alive.current=false;generation.current++;audio.current?.pause();if(sampleUrl.current)URL.revokeObjectURL(sampleUrl.current)}},[]);
 const clearSample=()=>{audio.current?.pause();setSample(null);if(sampleUrl.current){URL.revokeObjectURL(sampleUrl.current);sampleUrl.current=null}};
 const mode=source||(config?.source==='private'?'private':config?.environmentAvailable?'environment':'private');
 const change=async patch=>{setError('');try{const result=await act('settings.update',{patch});if(result?.accepted===false)throw Error(result.error||'Could not save voice settings.')}catch(error){setError(error.message)}};
 async function saveKey(){setSaving(true);setError('');try{const result=await act('voice.configure',{source:mode,...(mode==='private'?{apiKey:key}:{})});if(result?.accepted===false)throw Error(result.error||'Could not save voice key.');setKey('')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function preview(row){if(loading)return;const version=++generation.current;setLoading(row.id);setError('');clearSample();try{const result=await act('voice.preview',{model:model.id,voice:row.id});if(result?.accepted===false||!result?.result?.audio)throw Error(result?.error||'The sample was unavailable. Try again.');if(alive.current&&version===generation.current){const bytes=Uint8Array.from(atob(result.result.audio),c=>c.charCodeAt(0));sampleUrl.current=URL.createObjectURL(new Blob([bytes],{type:result.result.mimeType}));setSample({...result.result,audio:undefined,url:sampleUrl.current,name:row.name})}}catch(e){if(alive.current&&version===generation.current)setError(e.message)}finally{if(alive.current&&version===generation.current)setLoading('')}}
 const select=row=>{clearSample();change({voiceName:row.id});setChoosing(false)};
 const shown=model.voices.filter(row=>(row.name+' '+row.description).toLowerCase().includes(search.toLowerCase()));
 const credentialForm=<div className="a-voice-key-form">
   <p>Voice uses an OpenAI API key, separate from a ChatGPT subscription.</p>
   {config?.environmentAvailable&&<label className="a-inline-checkbox"><input type="radio" name="voice-key-source" checked={mode==='environment'} onChange={()=>setSource('environment')}/>Use the key on this host (OPENAI_API_KEY)</label>}
   <label className="a-inline-checkbox"><input type="radio" name="voice-key-source" checked={mode==='private'||!config?.environmentAvailable} onChange={()=>setSource('private')}/>Use a separate key</label>
   {(mode==='private'||!config?.environmentAvailable)&&<><label htmlFor="voice-api-key">OpenAI API key</label><input id="voice-api-key" type="password" autoComplete="off" value={key} onChange={e=>{setSource('private');setKey(e.target.value)}} placeholder={config?.privateKeyAvailable?'Saved key · enter a new key to replace it':''}/></>}
   <div className="a-dialog-actions"><button className="a-primary" data-action="voice.configure" disabled={saving||((mode==='private'||!config?.environmentAvailable)&&!key.trim()&&!config?.privateKeyAvailable)} onClick={saveKey}>{saving?'Saving…':'Save voice connection'}</button></div>
 </div>;
 return <div className="a-voice-settings">
 <section className="a-voice-connection" aria-label="Voice connection"><strong>{config?.available?'Voice key configured':config?'Connect voice':'Checking voice connection…'}</strong>{config?.available?<><p className="a-caption">{config.source==='private'?'Using your separate voice API key.':'Using the OpenAI API key on this host.'}</p><details className="a-everyday-disclosure"><summary>Change voice connection</summary>{credentialForm}</details></>:credentialForm}</section>
 <label htmlFor="preferred-voice">Voice model</label><select id="preferred-voice" data-action="settings.update" disabled={!!loading} value={model.id} onChange={e=>{const next=voiceCatalog.models.find(row=>row.id===e.target.value);clearSample();setSearch('');change({preferredVoice:next.id,voiceName:next.voices.some(row=>row.id===voice.id)?voice.id:'marin'})}}>{voiceCatalog.models.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><p className="a-caption">{model.description}</p>
 <h4 className="a-voice-label">Speaking voice</h4>
 <div className="a-voice-current"><div><strong>{voice.name}</strong><p>{voice.description}</p></div><button className="a-soft" disabled={!!loading} aria-expanded={choosing} onClick={()=>setChoosing(!choosing)}>{choosing?'Close voice list':'Choose a voice'}</button><button className="a-soft" data-action="voice.preview" disabled={!config?.available||!!loading||state.voicePreviewBusy} onClick={()=>preview(voice)}>{loading===voice.id?'Preparing sample…':'Preview voice'}</button></div>
 {choosing&&<section className="a-voice-picker" aria-label="Choose a speaking voice"><h4 ref={chooser} tabIndex={-1}>Voices for {model.name}</h4><label htmlFor="voice-search">Find a voice</label><input id="voice-search" type="search" placeholder="Search names or descriptions" value={search} onChange={e=>setSearch(e.target.value)}/><div role="radiogroup" aria-label="Speaking voice">{shown.map(row=><div key={row.id} className="a-voice-option" data-selected={row.id===voice.id}><label><input type="radio" name="speaking-voice" checked={row.id===voice.id} disabled={!!loading} data-action="settings.update" onChange={()=>select(row)}/><span><strong>{row.name}</strong><small>{row.description}</small></span></label><button className="a-soft" aria-label={'Preview '+row.name} disabled={!config?.available||!!loading||state.voicePreviewBusy} data-action="voice.preview" onClick={()=>preview(row)}>{loading===row.id?'Preparing…':'Preview'}</button>{sample?.voice===row.id&&<audio ref={audio} controls autoPlay aria-label={sample.name+' sample'} src={sample.url} onError={()=>setError('This browser could not play the sample. Try the preview again.')}/>}</div>)}</div>{!shown.length&&<p>No voices match your search.</p>}</section>}
 {sample&&!choosing&&<div className="a-voice-sample"><p>{sample.name} · {model.name}</p><audio ref={audio} controls autoPlay src={sample.url} onError={()=>setError('This browser could not play the sample. Try the preview again.')}>Your browser does not support audio playback.</audio></div>}
 <p className="a-caption">Previews use a short AI-generated sample and your OpenAI API usage. Your microphone and conversations are not used.</p>
 {model.id==='gpt-realtime-2.1'&&<label className="a-inline-checkbox"><input type="checkbox" checked={settings.voiceInterruptions!==false} data-action="settings.update" onChange={e=>change({voiceInterruptions:e.target.checked})}/>Let me interrupt by speaking</label>}
 <p className="a-caption">Changes apply to your next call. Your browser manages microphone access.</p>
 <details className="a-everyday-disclosure"><summary>About these voices</summary><div><p>Available voices depend on the model. Regional descriptions come from OpenAI; voices can speak other languages too. OpenAI does not describe the tone of every voice. Preview those voices to compare how they sound.</p><a href={model.source} target="_blank" rel="noreferrer">Voice guide from OpenAI</a></div></details>{error&&<p role="alert" className="a-danger">{error}</p>}</div>;
}
export function InstallAppSettings(){return <><p><a href="/setup/terminal" target="_blank" rel="noopener noreferrer">Install the Terminal app on this computer</a> to connect to this Unified service. The setup page handles the client and its saved connection.</p><p>In Edge or Chrome, choose the install icon in the address bar or Install this site as an app in the browser menu. In Safari on Mac, use File → Add to Dock. On iPhone or iPad, use Share → Add to Home Screen.</p><p>Keep the Python service running on the host computer. Installation gives this interface its own window; the service still runs your conversations and tools.</p><p className="a-caption">Use localhost on this computer, or a trusted HTTPS address on other devices. Your saved chats and canvas artifacts stay on the host.</p></>;}
