import {AttentionBadge,AttentionReview} from './attention';
import React,{useRef,useState,useEffect} from 'react';
import {CheckCircle2,Info,XCircle,LoaderCircle,ChevronRight,Upload,FolderOpen,ArrowUp,ArrowDown,GripVertical,X,ArrowLeft} from 'lucide-react';
export function ResultNotice({phase,message,detail}){
 if(!message)return null;
 const working=['working','queued','pending','checking','staging','validating','activating'].includes(phase),failed=['error','failed'].includes(phase),Icon=working?LoaderCircle:failed?XCircle:phase==='neutral'?Info:CheckCircle2;
 return <div className={`a-check-result ${working||phase==='neutral'?'pending':failed?'error':'success'}`} role={failed?'alert':'status'} aria-live="polite"><Icon aria-hidden="true" className={working?'a-progress-spinner':undefined}/><div><strong>{message}</strong>{detail&&<small>{detail}</small>}</div></div>;
}
export function SettingsGroup({id,title,summary,state,act,children}){
 const pages={setup:['loaded-modules','providers','routing','defaults','conversation'],capabilities:['add-bundles','app-bundles','loaded-modules','registries','share-bundle'],maintenance:['updates','shared-history','history','permissions','notifications','automation','repair','reset']};
 const page=state.view?.settingsExpanded?.find(key=>!state.view?.settingsSection||pages[state.view.settingsSection]?.includes(key)),open=page===id,heading=useRef();
 useEffect(()=>{if(open){heading.current?.focus({preventScroll:true});heading.current?.closest('.a-dialog')?.scrollTo(0,0)}},[open]);
 if(page&&!open)return null;
 const navigate=()=>act('view.update',{patch:{settingsExpanded:open?[]:[id]}});
 return open?<section className="a-settings-page" key={id}><button type="button" className="a-link a-settings-back" data-action="view.update" onClick={navigate}><ArrowLeft/>Back to {({setup:'Setup',capabilities:'Capabilities',maintenance:'Maintenance'})[state.view?.settingsSection||'setup']}</button><h3 ref={heading} tabIndex={-1}>{title}</h3><AttentionReview state={state} act={act} page={id}/><div id={'settings-group-'+id} className="a-settings-page-body">{children}</div></section>:<section className="a-settings-group"><button type="button" className="a-settings-group-title" aria-label={title+(summary?' '+summary:'')} data-action="view.update" onClick={navigate}><span><strong>{title}</strong>{summary&&<small>{summary}</small>}</span><AttentionBadge state={state} page={id}/><ChevronRight aria-hidden="true"/></button></section>;
}

export function FileDrop({id,accept,disabled,action,onFile,label='Choose file',hint}){
 const input=useRef(),[over,setOver]=useState(false),[filename,setFilename]=useState(''),[error,setError]=useState('');
 async function receive(file){if(!file||disabled)return;setError('');setFilename(file.name);try{await onFile(file)}catch(error){setError(error.message)}}
 return <div className={`a-file-drop ${over?'drag-over':''}`} onDragOver={e=>{e.preventDefault();if(!disabled)setOver(true)}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);receive(e.dataTransfer.files?.[0])}}><Upload aria-hidden="true"/><div><button type="button" className="a-soft" disabled={disabled} data-action={action} onClick={()=>input.current?.click()}>{label}</button><small>{filename||hint||'Drop a file here, or browse to choose one.'}</small></div><input ref={input} id={id} className="a-file-input" type="file" accept={accept} disabled={disabled} data-action={action} aria-label={label} onChange={e=>{receive(e.target.files?.[0]);e.target.value=''}}/>{error&&<ResultNotice phase="error" message={error}/>}</div>;
}
export function droppedLocation(transfer){
 const text=(transfer.getData('text/uri-list')||transfer.getData('text/plain')||'').split('\n').find(line=>line.trim()&&!line.startsWith('#'))?.trim();
 if(!text)return null;
 if(text.startsWith('file://')){try{return decodeURIComponent(new URL(text).pathname)}catch{return null}}
 return text;
}
export function PathField({id,value,onChange,state,act,placeholder,action='view.update',directory=false,multiline=false}){
 const[over,setOver]=useState(false),[error,setError]=useState(''),[pathDraft,setPathDraft]=useState('');
 const picker=state.view?.locationPicker,open=picker?.controlId===id,listing=state.locationListing?.controlId===id?state.locationListing:null;
 useEffect(()=>{if(open)setPathDraft(picker.path??listing?.path??'')},[open,picker?.path,listing?.path]);
 const status=state.actionStatus?.['locations.list'],op=status?.target?.controlId===id?status:null;
 const browse=path=>{setPathDraft(path||'');setError('');act('view.update',{patch:{locationPicker:{controlId:id,path:path||''}}});return act('locations.list',{controlId:id,...(path?{path}:{}),directoriesOnly:directory})};
 const choose=path=>{onChange(multiline?[value,path].filter(Boolean).join('\n'):path);act('view.update',{patch:{locationPicker:null}})};
 const Input=multiline?'textarea':'input';
 return <div className={`a-path-field ${over?'drag-over':''}`} onDragOver={e=>{e.preventDefault();setOver(true)}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);const path=droppedLocation(e.dataTransfer);if(path){setError('');onChange(multiline?[value,path].filter(Boolean).join('\n'):path)}else setError('Your browser hides the full path of dropped files. Use Browse, or drop a copied file or folder path.')}}><div className="a-inline-form"><Input id={id} value={value} placeholder={placeholder} data-action={action} onChange={e=>onChange(e.target.value)}/><button type="button" className="a-soft" data-action="locations.list" onClick={()=>browse(!multiline&&value?.startsWith('/')?value:undefined)}><FolderOpen/>Browse</button></div>{error&&<ResultNotice phase="error" message={error}/>} {open&&<div className="a-location-picker"><div className="a-settings-row"><strong>{directory?'Choose a folder':'Choose a file or folder'}</strong><button type="button" className="a-icon" aria-label="Close location picker" data-action="view.update" onClick={()=>act('view.update',{patch:{locationPicker:null}})}><X/></button></div><label htmlFor={id+'-browse-path'}>Folder path</label><div className="a-inline-form"><input id={id+'-browse-path'} value={pathDraft} placeholder="Type a path, e.g. ~/Projects" data-action="view.update" onChange={e=>{setPathDraft(e.target.value);act('view.update',{patch:{locationPicker:{...picker,path:e.target.value}}})}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();browse(e.currentTarget.value)}}}/><button type="button" className="a-soft" data-action="locations.list" onClick={()=>browse(pathDraft)}>Go</button></div>{op?.phase==='error'?<ResultNotice phase="error" message={op.error}/>:op?.phase==='working'||op?.phase==='queued'?<ResultNotice phase="working" message="Loading locations…"/>:listing&&<><div className="a-settings-row"><button type="button" className="a-soft" data-action="locations.list" disabled={listing.parent===listing.path} onClick={()=>browse(listing.parent)}><ArrowUp/>Up</button><code className="a-wrap">{listing.path}</code></div><div className="a-location-list">{listing.entries.map(entry=><button type="button" className="a-location-entry" key={entry.path} data-action={entry.directory?'locations.list':action} onClick={()=>entry.directory?browse(entry.path):choose(entry.path)}>{entry.directory&&<FolderOpen/>}{entry.name}{entry.directory&&<ChevronRight/>}</button>)}{!listing.entries.length&&<p>No {directory?'folders':'files'} here.</p>}</div>{listing.truncated&&<p>Showing the first 300 items. Enter a more specific path above.</p>}<button type="button" className="a-primary" data-action={action} onClick={()=>choose(listing.path)}>Use this folder</button></>}</div>}</div>;
}
export function ReorderRow({id,group,label,index,count,onMove,disabled,children,className='',action='view.update'}){
 const[over,setOver]=useState(false);
 return <div className={`a-reorder-row ${className} ${over?'drag-over':''}`} onDragOver={e=>{if(!disabled&&e.dataTransfer.types.includes('application/x-amplifier-order')){e.preventDefault();e.dataTransfer.dropEffect='move';setOver(true)}}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);try{const item=JSON.parse(e.dataTransfer.getData('application/x-amplifier-order'));if(!disabled&&item.group===group&&item.id!==id)onMove(item.id,index)}catch{}}}><button type="button" className="a-icon a-drag-handle" draggable={!disabled} disabled={disabled} data-action={action} aria-label={`Reorder ${label}. Use arrow keys to move.`} title="Drag to reorder; or use arrow keys" onDragStart={e=>{e.dataTransfer.setData('application/x-amplifier-order',JSON.stringify({group,id}));e.dataTransfer.effectAllowed='move'}} onKeyDown={e=>{if(e.key==='ArrowUp'&&index>0){e.preventDefault();onMove(id,index-1)}if(e.key==='ArrowDown'&&index<count-1){e.preventDefault();onMove(id,index+1)}}}><GripVertical/></button><div className="a-reorder-content">{children}</div><div className="a-reorder-buttons"><button type="button" className="a-icon" disabled={disabled||index===0} aria-label={`Move ${label} up`} data-action={action} onClick={()=>onMove(id,index-1)}><ArrowUp/></button><button type="button" className="a-icon" disabled={disabled||index===count-1} aria-label={`Move ${label} down`} data-action={action} onClick={()=>onMove(id,index+1)}><ArrowDown/></button></div></div>;
}

export function BundlePicker({id,value,onChange,state,act,action='view.update'}){
 useEffect(()=>{act('bundles.list',{})},[]);
 const bundles=state.registeredBundles||[{name:'anchors',value:'anchors'}];
 return <div className="a-bundle-picker"><select aria-label="Registered root bundles" value={bundles.some(row=>row.value===value)?value:':custom:'} data-action={action} onChange={e=>{if(e.target.value!==':custom:')onChange(e.target.value)}}><option value=":custom:" disabled>Choose a registered bundle, or enter a source below</option>{bundles.map(row=><option value={row.value} key={row.value}>{row.name}</option>)}</select><PathField action={action} id={id} value={value} onChange={onChange} state={state} act={act} placeholder="Bundle name, git URL or file path"/></div>;
}
