import React,{useState} from 'react';

export function TaskContinuity({state,session,act}){
 const snapshot=state.runtimeControl?.[session.id]?.['task.get']||{},task=snapshot.task||session.task,continuity=snapshot.continuity||session.continuity;
 const [objective,setObjective]=useState(''),[constraints,setConstraints]=useState(''),[correction,setCorrection]=useState(''),[reason,setReason]=useState(''),[evidence,setEvidence]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');
 const run=async(action,args={})=>{setPending(true);setError('');try{await act(action,{sessionId:session.id,...(action==='task.get'?{}:{expectedRevision:task?.revision||0}),...args})}catch(e){setError(e.message||String(e))}finally{setPending(false)}};
 const open=task&&task.status!=='completed';
 return <section className="a-settings-section" data-part="task-continuity" aria-label="Saved task">
  <h3>Saved task</h3><p>Keep the objective, corrections, and evidence across restarts and long conversations. Saving a task does not send a message.</p>
  <button className="a-soft" disabled={pending} data-action="task.get" onClick={()=>run('task.get')}>Load saved task</button>
  {task&&<div className="a-selection-card"><p><strong>{task.objective}</strong></p><p role="status">Task {task.status} · revision {task.revision}{task.appliedRevision!==task.revision?' · applies at the next request':''}</p>{task.constraints?.length>0&&<ul>{task.constraints.map((text,i)=><li key={i}>{text}</li>)}</ul>}{task.status==='blocked'&&task.blockedReason&&<p>Waiting because: {task.blockedReason}</p>}{task.corrections?.length>0&&<details><summary>Saved corrections ({task.corrections.length})</summary><ul>{task.corrections.map((row,i)=><li key={i}>{row.text}</li>)}</ul></details>}{task.completionEvidence?.length>0&&<ul>{task.completionEvidence.map((text,i)=><li key={i}>{text}</li>)}</ul>}<details><summary>Linked questions, operations, and artifacts</summary>{['questionIds','operationIds','artifactRefs'].map(key=><p key={key}>{key==='questionIds'?'Questions':key==='operationIds'?'Operations':'Artifacts'}: {task[key]?.join(', ')||'None'}</p>)}</details></div>}
  {!open&&<><label htmlFor="task-objective">Task objective</label><textarea id="task-objective" value={objective} onChange={e=>setObjective(e.target.value)}/><label htmlFor="task-constraints">Constraints (one per line)</label><textarea id="task-constraints" value={constraints} onChange={e=>setConstraints(e.target.value)}/><button className="a-primary" data-action="task.create" disabled={pending||!objective.trim()} onClick={()=>run('task.create',{objective:objective.trim(),constraints:constraints.split('\n').map(s=>s.trim()).filter(Boolean)})}>Save task</button></>}
  {open&&<><label htmlFor="task-correction">Correction to retain</label><textarea id="task-correction" value={correction} onChange={e=>setCorrection(e.target.value)}/><button className="a-soft" data-action="task.update" disabled={pending||!correction.trim()} onClick={()=>run('task.update',{correction:correction.trim()})}>Save correction</button><div className="a-dialog-actions">{task.status==='active'?<button className="a-soft" data-action="task.pause" disabled={pending} onClick={()=>run('task.pause')}>Pause task</button>:<button className="a-primary" data-action="task.resume" disabled={pending} onClick={()=>run('task.resume')}>Resume task</button>}</div><p className="a-caption">Pause stops future automatic continuation. Current work can finish. Resume does not send a message or answer a pending question.</p><details><summary>Record a blocker or completion</summary><label htmlFor="task-blocker">What is blocking this task?</label><input id="task-blocker" value={reason} onChange={e=>setReason(e.target.value)}/><button className="a-soft" data-action="task.block" disabled={pending||!reason.trim()} onClick={()=>run('task.block',{reason:reason.trim()})}>Mark blocked</button><label htmlFor="task-evidence">Evidence that the objective is complete (one per line)</label><textarea id="task-evidence" value={evidence} onChange={e=>setEvidence(e.target.value)}/><button className="a-soft" data-action="task.complete" disabled={pending||!evidence.trim()} onClick={()=>run('task.complete',{condition:task.objective,evidence:evidence.split('\n').map(s=>s.trim()).filter(Boolean)})}>Complete task with evidence</button></details></>}
  {task&&snapshot.continuationSupported===false&&<p role="alert">This runtime cannot automatically continue saved tasks. Update its task support before resuming.</p>}
  {continuity&&<p className="a-caption">Conversation continuity: {continuity.supported?continuity.status:'not available in this context module'}{continuity.reason?` — ${continuity.reason}`:''}. The original transcript remains available.</p>}
  {error&&<p role="alert" className="a-danger">{error}</p>}
 </section>
}
