import React,{useState} from 'react';
export function WorktreeControls({session,act}){
 const [ref,setRef]=useState('HEAD'),[branch,setBranch]=useState(''),[carry,setCarry]=useState(false),[path,setPath]=useState(''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false);
 const run=async(action,args={})=>{setBusy(true);try{return await act(action,{sessionId:session.id,...args})}finally{setBusy(false)}};
 const inspected=session.worktreeInspection,working=session.workingDirectory||session.workspace;
 const handoff=id=>run('worktree.handoff',{id,expectedExecutionRevision:session.executionRevision||0});
 return <section className="a-settings-section" aria-label="Task worktrees" data-part="worktrees"><h3>Task execution folder</h3><p>Run this task in a separate Git checkout while keeping its saved conversation, voice history, artifacts and settings in their original home.</p><dl><dt>Saved history and settings home</dt><dd className="a-state-view">{session.workspace}</dd><dt>Execution host</dt><dd data-part="execution-host">{inspected?.executionHost?.label||session.executionHost?.label||'Inspect to identify this local host'}</dd><dt>Execution folder</dt><dd className="a-state-view" data-part="execution-directory">{working}</dd></dl>
 <button className="a-soft" disabled={busy} data-action="worktree.inspect" onClick={()=>run('worktree.inspect')}>Inspect repository</button>
 {working!==session.workspace&&<button className="a-soft" disabled={busy||session.configurationBusy} data-action="worktree.handoff" onClick={()=>handoff(null)}>Return execution to home</button>}
 {inspected?.repository&&<><p>{inspected.repository.branch||'Detached commit'} · {inspected.repository.dirty?'Uncommitted changes present':'Checkout clean'}</p><details><summary>Source changes</summary><pre className="a-state-view">{inspected.repository.status||'No changes'}</pre></details><h4>Create a checkout</h4><label htmlFor="worktree-ref">Starting Git ref or commit</label><input id="worktree-ref" value={ref} onChange={e=>setRef(e.target.value)}/><label htmlFor="worktree-branch">New branch (optional)</label><input id="worktree-branch" value={branch} onChange={e=>setBranch(e.target.value)}/><label className="a-inline-checkbox"><input type="checkbox" checked={carry} onChange={e=>setCarry(e.target.checked)}/>Include my uncommitted changes</label><p className="a-caption">{carry?'Copy staged, unstaged and untracked files with an inspectable manifest. Ignored files are excluded. Repositories with submodules need separate handling; the source stays intact.':'Start from the committed ref in a clean checkout. Your current uncommitted changes stay in the source.'}</p><button className="a-primary" disabled={busy||!ref.trim()} data-action="worktree.create" onClick={()=>run('worktree.create',{sourceRevision:inspected.repository.sourceRevision,ref:ref.trim(),...(branch.trim()?{branch:branch.trim()}:{}),mode:carry?'carry_dirty':'clean'})}>Create managed checkout</button></>}
 <details><summary>Attach an existing checkout</summary><label htmlFor="worktree-path">Existing worktree path</label><input id="worktree-path" value={path} onChange={e=>setPath(e.target.value)}/><button className="a-soft" disabled={busy||!path.trim()} data-action="worktree.attach" onClick={()=>run('worktree.attach',{path:path.trim()})}>Attach checkout</button><p className="a-caption">The folder must belong to this repository. Attaching does not start work or grant cleanup ownership.</p></details>
 {(session.worktrees||[]).map(row=><article className="a-selection-card" key={row.id} data-worktree-id={row.id}><p className="a-state-view">{row.path}</p><p role="status">Checkout {row.status}</p><p>Local host: {row.executionHost?.label||'Not recorded for this checkout'}</p>{row.error&&<p role="alert">{row.error}</p>}<p>{row.branch||'Detached commit'} · {row.mode==='carry_dirty'?'Changes copied':row.mode==='attached'?'Existing checkout':'Committed source'}</p><div className="a-dialog-actions"><button className="a-soft" disabled={busy} data-action="worktree.status" onClick={()=>run('worktree.status',{id:row.id})}>Inspect checkout and manifest</button>{row.status==='ready'&&<button className="a-primary" disabled={busy||session.configurationBusy||working===row.path} data-action="worktree.handoff" onClick={()=>handoff(row.id)}>Move execution here</button>}{row.owned&&row.status!=='removed'&&<button className="a-soft" disabled={busy||working===row.path||session.configurationBusy} data-action="worktree.remove" onClick={()=>run('worktree.remove',{id:row.id,expectedRevision:row.revision})}>Remove clean checkout</button>}</div></article>)}
 {session.worktreeStatus&&<details open><summary>Checkout inspection</summary><pre className="a-state-view">{JSON.stringify(session.worktreeStatus,null,2)}</pre></details>}
 {(session.worktreeHandoffs||[]).map(row=><article className="a-selection-card" key={row.id} data-handoff-id={row.id}><p role="status">Handoff {row.phase}</p><p>Local host: {row.executionHost?.label||'Not recorded for this receipt'}</p><p>{row.detail}</p>{row.phase==='unknown'&&<><label htmlFor={'handoff-evidence-'+row.id}>What did you verify?</label><textarea id={'handoff-evidence-'+row.id} value={evidence} onChange={e=>setEvidence(e.target.value)}/><p className="a-caption">Confirm saved writer release again and choose the execution folder. Neither choice sends a message or replays work.</p><div className="a-dialog-actions">{['source','target'].map(destination=><button className="a-soft" key={destination} disabled={busy||!evidence.trim()} data-action="worktree.reconcile" onClick={()=>run('worktree.reconcile',{id:row.id,expectedRevision:row.revision,destination,evidence:evidence.trim()})}>Use {destination} folder</button>)}</div></>}</article>)}
 </section>
}
