import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,copyFile,rm,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';
const {createPortabilityCapabilities,TransferConnection}=await import(process.env.PORTABILITY_MODULE??'../dist/index.js');
const python=process.env.PORTABILITY_PYTHON,nativePython=process.env.AMPLIFIER_ACP_PYTHON,hostModule=process.env.PORTABILITY_HOST_MODULE,adminModule=process.env.PORTABILITY_ADMIN_MODULE,fixture=process.env.PORTABILITY_NATIVE_FIXTURE;
const fence={fenceId:'transfer-test-fence',commandId:'transfer-test-command',purpose:'recovery',instanceId:'fixture-host',dataScope:'fixture-data'};
const proof={verified:true,...fence,outcome:'unchanged',receiptId:'fixture-proof'};
const denied=async()=>{throw Error('Uncalled mutation');};
const setup=String.raw`import importlib.util,json,sys,yaml
from pathlib import Path
p=Path(sys.argv[1]);home=p/'home';home.mkdir();provider=p/'provider';provider.mkdir();module=provider/'amplifier_module_provider_transfer_fixture';module.mkdir()
(module/'__init__.py').write_bytes(Path(sys.argv[2]).read_bytes());(provider/'pyproject.toml').write_text('[project]\nname="amplifier-module-provider-transfer-fixture"\nversion="0.1.0"\n')
context=Path(importlib.util.find_spec('amplifier_module_context_simple').origin).parent
config={'reasoning_effort':'low','readinessAudit':str(p/'probe.txt'),'normalAudit':str(p/'normal.txt')}
bundle=p/'bundle.yaml';bundle.write_text(yaml.safe_dump({'bundle':{'name':'transfer-fixture','version':'1.0.0'},'session':{'orchestrator':{'module':'loop-live'},'context':{'module':'context-simple','source':str(context)}},'providers':[{'module':'provider-transfer-fixture','source':str(provider),'config':config}]}))
(home/'settings.yaml').write_text(yaml.safe_dump({'bundle':{'active':'transfer-fixture','app':[]},'config':{'providers':[{'id':'fixture','module':'provider-transfer-fixture','source':str(provider),'config':config}]}}))
(p/'native.json').write_text(json.dumps({'home':str(home),'appHome':str(p/'app'),'bundle':str(bundle),'adminWorkspaceRoots':[str(p)],'transferAuthorityDirectory':str(p/'owner'),'transferWorkspaceRoots':[str(p)],'transferProbeCommand':[sys.executable,'-m','amplifier_acp.native.portability_probe']}))
`;
const git=(path,...args)=>execFileSync('git',['-c','core.hooksPath=/dev/null','-C',path,...args],{encoding:'utf8'}).trim();
const ctx={clientId:'fixture',origin:'ui'};
const act=(cap,operation,args={},session='ahp-root://',commandId=randomUUID())=>cap.action({version:1,topic:'portability',channel:session,operation:'portability.'+operation,args,commandId},ctx).then(v=>v.result);

test('configured peers without native retirement proof refuse coverage rather than claim idle',{skip:!python},async()=>{
 const root=await mkdtemp(join(tmpdir(),'portability-no-proof-'));await mkdir(join(root,'work'));const config=join(root,'owner.json');await writeFile(config,JSON.stringify({dataDir:join(root,'owner'),exchangeDir:join(root,'exchange'),stageDir:join(root,'work/stages'),workspaceRoots:[join(root,'work')]}));
 const cap=createPortabilityCapabilities({owner:{command:python,args:['-m','amplifier_unified_portability.server','--config',config]},inspectSession:denied,beginTransfer:denied,commitTransfer:denied,cancelTransfer:denied,adoptTransferredSession:denied,nativeTransfer:denied,exportTransferEvidence:denied,stageTransferEvidence:denied,activateTransferEvidence:denied});
 try{assert.equal(await cap.quiescenceParticipant.acquire(fence),null);assert.equal((await cap.inspectQuiescence()).intakeClosed,false);}finally{await cap.close();await rm(root,{recursive:true,force:true});}
});

test('actual native peers, installed host and Python owner preserve a signed transfer across held maintenance',{skip:!python||!nativePython||!hostModule||!adminModule||!fixture,timeout:180000},async()=>{
 const {createHost}=await import(hostModule),{AdminConnection}=await import(adminModule);
 const {AhpClient}=await import(new URL('../../../@microsoft/agent-host-protocol/dist/client/index.js',pathToFileURL(hostModule)).href),{WebSocketTransport}=await import(new URL('../../../@microsoft/agent-host-protocol/dist/ws/index.js',pathToFileURL(hostModule)).href);
 const directory=await realpath(await mkdtemp(join(tmpdir(),'portability-real-held-')));const sides=[];let evidenceEntered=false,releaseEvidence;const evidenceWait=new Promise(resolve=>releaseEvidence=resolve);
 async function side(name){const root=join(directory,name);await mkdir(root);const work=join(root,'workspace');await mkdir(work);execFileSync(nativePython,['-c',setup,root,fixture]);const ownerConfig=join(root,'owner.json');await writeFile(ownerConfig,JSON.stringify({dataDir:join(root,'owner'),exchangeDir:join(root,'exchange'),stageDir:join(root,'stages'),workspaceRoots:[root],label:name}));
  const launcher={command:nativePython,args:['-m','amplifier_acp','--config',join(root,'native.json')],cwd:root,env:{AMPLIFIER_SESSION_STATE_HOME:join(root,'writers')}};let idle=0,host;
  const native=new TransferConnection({...launcher,ownerId:'native-transfer:'+name,onMayBeIdle:()=>idle++}),admin=new AdminConnection({...launcher,resolveWorkspace:()=>root});
  const cap=createPortabilityCapabilities({owner:{command:python,args:['-m','amplifier_unified_portability.server','--config',ownerConfig]},nativeParticipants:[native.quiescenceParticipant],onMayBeIdle:()=>idle++,inspectSession:uri=>host.inspectSession(uri),beginTransfer:(uri,a)=>host.beginTransfer(uri,{...a,commandId:'portability:'+a.commandId+':begin'}),commitTransfer:(uri,a)=>host.commitTransfer(uri,{...a,commandId:'portability:'+a.commandId+':commit'}),cancelTransfer:(uri,a)=>host.cancelTransfer(uri,{...a,commandId:'portability:'+a.commandId+':cancel'}),adoptTransferredSession:a=>host.adoptTransferredSession({...a,commandId:'portability:'+a.commandId+':adopt'}),nativeTransfer:native.perform,exportTransferEvidence:async()=>{if(name==='a'){evidenceEntered=true;await evidenceWait;}return {evidence:[],omissions:[{kind:'fixture-owner-evidence',included:false}]};},stageTransferEvidence:async()=>({receipts:[]}),activateTransferEvidence:async()=>({receipts:[]})});
  const info=await act(cap,'inspect');host=await createHost({stateDirectory:join(root,'host'),engines:[{id:'native',...launcher}],allowedWorkspaceRoots:[root],transferIdentity:info.host.id,capabilities:cap,quiescence:{instanceId:name,dataScope:root,requiredOwners:['portability','native-admin'],coverage:{capabilities:{portability:'portability'}},participants:[cap.quiescenceParticipant,admin.quiescenceParticipant],verifyRelease:async input=>({verified:true,fenceId:input.fenceId,commandId:input.commandId,outcome:'unchanged',instanceId:name,dataScope:root,receiptId:'fixture-reviewed-quiescent'})}});
  const client=new AhpClient(await WebSocketTransport.connect(host.url));client.connect();await client.initialize({clientId:'fixture',protocolVersions:['0.9.0']});const value={root,work,host,client,cap,native,admin,info,get idle(){return idle;}};sides.push(value);return value;
 }
 try{
  const a=await side('a'),b=await side('b');git(a.work,'init','-q');git(a.work,'config','user.email','fixture@example.invalid');git(a.work,'config','user.name','Owned fixture');await writeFile(join(a.work,'retained.txt'),'retained source');git(a.work,'add','.');git(a.work,'commit','-qm','fixture');git(b.work,'clone',a.work,'.');
  execFileSync(python,['-c',"import json,sys;from pathlib import Path;from amplifier_worktrees.git import atomic;a,b=map(Path,sys.argv[1:3]);x,y=map(json.loads,sys.argv[3:]);atomic(a/'peers.json',{y['id']:y});atomic(b/'peers.json',{x['id']:x})",join(a.root,'owner'),join(b.root,'owner'),JSON.stringify(a.info.host),JSON.stringify(b.info.host)]);
  const uri='ahp-session:/'+randomUUID();await a.client.request('createSession',{channel:uri,provider:'native',workingDirectories:[pathToFileURL(a.work).href]});await a.host.nativeControl(uri,'provider.select',{provider:'fixture',model:'fixture-model',effort:'low'});await a.host.submitTurn(uri,{commandId:'original',clientId:'fixture',text:'Never replay this original input.'});assert.equal((await a.host.waitForTurn(uri,'original',30000)).status,'completed');
  const before=await a.host.inspectSession(uri);const metadata=JSON.parse(execFileSync(nativePython,['-c',"import json,sys;from pathlib import Path;p=Path(sys.argv[1]);n=next((p/'home/projects').glob('*/sessions/'+sys.argv[2]));m=json.loads((n/'metadata.json').read_text());print(json.dumps({'path':str(n),'bundle':m.get('bundle') or m.get('bundle_name')}))",a.root,before.nativeSessionId],{encoding:'utf8'}));const original=await readFile(join(metadata.path,'transcript.jsonl'));
  execFileSync(nativePython,['-c',"import sys,yaml;from pathlib import Path;p=Path(sys.argv[1]);v=yaml.safe_load(p.read_text());v['bundle']['active']=sys.argv[2];p.write_text(yaml.safe_dump(v))",join(b.root,'home/settings.yaml'),metadata.bundle]);
  const inspected=await act(a.cap,'inspect',{sessionId:uri},uri);const outgoing=act(a.cap,'export',{sessionId:uri,destination:b.info.host.id,sourceRevision:inspected.source.sourceRevision,expectedExecutionRevision:before.executionRevision,mode:'clean',reviewedContent:true},uri,'export');for(let n=0;n<2000&&!evidenceEntered;n++)await new Promise(resolve=>setTimeout(resolve,10));assert.equal(evidenceEntered,true);assert.equal(await a.cap.quiescenceParticipant.acquire(fence),null,'Evidence callback promises are still owned work');releaseEvidence();const out=await outgoing;assert.equal(out.phase,'prepared');
  const held=await a.host.admitQuiescence({commandId:'snapshot-maintenance',purpose:'recovery'});assert.equal(held.admitted,true);assert.equal((await a.native.inspectQuiescence()).intakeClosed,true);assert.equal((await a.admin.inspectLifecycle()).intakeClosed,true);
  assert.equal((await act(a.cap,'receipt',{id:out.id},uri)).phase,'prepared');const blocked=await a.cap.action({version:1,topic:'portability',channel:uri,operation:'portability.cancel',args:{sessionId:uri,id:out.id,expectedRevision:out.revision},commandId:'blocked'},ctx);assert.equal(blocked.accepted,false);
  await a.host.releaseQuiescence({fenceId:held.fenceId,commandId:held.commandId,outcome:'unchanged',evidence:{fixture:true}});
  const capsule=join(b.root,'exchange/capsule.json');await copyFile(out.package,capsule);const incoming=await act(b.cap,'stage',{path:capsule,repository:b.work,reviewedCapsuleHash:out.review.capsuleHash});assert.equal(incoming.phase,'ready');
  const ready=join(a.root,'exchange/ready.json');await copyFile(incoming.receiptPath,ready);const released=await act(a.cap,'release',{sessionId:uri,id:out.id,expectedRevision:out.revision,path:ready,reviewedCapsuleHash:out.review.capsuleHash},uri);assert.equal(released.phase,'released');
  const certificate=join(b.root,'exchange/release.json');await copyFile(released.receiptPath,certificate);const activated=await act(b.cap,'activate',{id:incoming.id,expectedRevision:incoming.revision,path:certificate});assert.equal(activated.adoption.uri,uri);assert.equal(b.host.diagnostics().activeAgents,0);assert.deepEqual(await readFile(join(metadata.path,'transcript.jsonl')),original);assert.ok(a.idle>0&&b.idle>0);
  const after=await b.host.inspectSession(uri);const target=execFileSync(nativePython,['-c',"import sys;from pathlib import Path;n=next((Path(sys.argv[1])/'home/projects').glob('*/sessions/'+sys.argv[2]));sys.stdout.buffer.write((n/'transcript.jsonl').read_bytes())",b.root,after.nativeSessionId]);assert.deepEqual(target,original);await assert.rejects(a.host.submitTurn(uri,{commandId:'no-replay',clientId:'fixture',text:'must refuse'}),/fenced|released|transfer/);
 }finally{releaseEvidence();for(const s of sides.toReversed()){await s.client.shutdown();await s.cap.close();await s.native.close();await s.admin.close();await s.host.close();}await rm(directory,{recursive:true,force:true});}
});
