import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';const {createCoordinationCapabilities}=await import(process.env.COORDINATION_NODE_MODULE??'../dist/index.js');
const python=process.env.COORDINATION_PYTHON,hostPackage=process.env.COORDINATION_HOST_PACKAGE,native=process.env.COORDINATION_NATIVE_EXECUTABLE,config=process.env.COORDINATION_NATIVE_CONFIG,workspacePath=process.env.COORDINATION_NATIVE_WORKSPACE;
test('installed public host and owner coordinate an actual resident Core/Foundation worker',{skip:!python||!hostPackage||!native||!config||!workspacePath},async()=>{
 const peer=join(dirname(hostPackage),'coordination-test-peer.mjs');await writeFile(peer,"export {createHost} from '@amplifier/unified-host';export {AhpClient} from '@microsoft/agent-host-protocol/client';export {WebSocketTransport} from '@microsoft/agent-host-protocol/ws';");const {createHost,AhpClient,WebSocketTransport}=await import(pathToFileURL(peer));
 const directory=await realpath(await mkdtemp(join(tmpdir(),'coordination-native-product-'))),workspace=await realpath(workspacePath),ownerConfig=join(directory,'owner.json');await writeFile(ownerConfig,JSON.stringify({dataDir:join(directory,'owner')}));let owner;
 const host=await createHost({stateDirectory:join(directory,'host'),allowedWorkspaceRoots:[workspace],engines:[{id:'amplifier',label:'Amplifier',command:native,args:['--config',config]}],nativeEvent:async(context,params)=>{if(params.event?.type==='workers.changed')owner?.changed(context.session);}});
 owner=createCoordinationCapabilities({owner:{command:python,cwd:directory,args:['-m','amplifier_unified_coordination.server','--config',ownerConfig]},listCoordinationSessions:args=>host.listCoordinationSessions(args),readCoordinationSession:(session,args)=>host.readCoordinationSession(session,args),readCoordinationWorkers:(session,args)=>host.readCoordinationWorkers(session,args),controlCoordinationWorker:(session,operation,args)=>host.nativeControlExisting(session,operation,args),controlCoordinationSession:async args=>args.operation==='followup'?host.submitTurn(args.session,{commandId:args.commandId,text:args.text,origin:args.origin,clientId:args.clientId}):host.interruptSession(args.session,{commandId:args.commandId,turnId:(await host.inspectSession(args.session)).activeTurnId,origin:args.origin,clientId:args.clientId}),observeSession:(session,listener)=>host.observeSession(session,listener)});
 const client=new AhpClient(await WebSocketTransport.connect(host.url));client.connect();const session='ahp-session:/'+randomUUID(),initial=randomUUID();const action=(operation,args,id=randomUUID())=>owner.action({version:1,topic:'coordination',channel:'ahp-root://',operation:'coordination.'+operation,args,commandId:id},{clientId:'fixture',origin:'ui'});
 const until=async(fn)=>{const deadline=Date.now()+15000;while(Date.now()<deadline){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,20));}throw Error('Native coordination condition timed out');};
 try{
  await client.initialize({clientId:'fixture',protocolVersions:['0.9.0']});await client.request('createSession',{channel:session,workingDirectories:[pathToFileURL(workspace).href]});await host.submitTurn(session,{commandId:initial,text:'spawn-persistent',clientId:'fixture'});
  const worker=await until(async()=>{const page=(await action('list',{sessionId:session})).result;return page.items.find(row=>row.kind==='worker'&&row.status==='idle'&&row.canFollowup);});assert.ok(worker.target.workerId);
  const first=(await action('wait',{targets:[worker.target]})).result.targets[0];assert.match(first.results.at(-1).text,/child-initial/);
  const follow=randomUUID(),request={...worker.target,text:'child-followup'};const sent=await action('followup',request,follow);assert.equal(sent.result.receipt.status,'accepted');await action('followup',request,follow);
  const report=(await action('wait',{targets:[{...worker.target,afterCursor:first.nextCursor}],waitMs:10000})).result.targets[0];assert.equal(report.results.filter(row=>row.text.includes('child-followup')).length,1);
  const stopped=await action('interrupt',worker.target);assert.equal(stopped.result.receipt.status,'accepted');const done=await host.waitForTurn(session,initial,30000);assert.equal(done.completed,true,JSON.stringify(done));
  const final=(await action('wait',{targets:[{...worker.target,afterCursor:report.nextCursor}]})).result.targets[0];assert.notEqual(final.status,'running');assert.equal(final.questionIds,null);
 }finally{await owner.close();await client.shutdown();await host.close();await rm(directory,{recursive:true,force:true});}
});
