import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,lstat,copyFile,open,rm,realpath} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash,generateKeyPairSync,sign} from 'node:crypto';
import {createServer} from 'node:http';
import {execFile,spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {promisify} from 'node:util';
import * as updates from '@amplifier/unified-distribution-update-owner';
import {createHTTPSGitFixture} from './https-git-fixture.mjs';
const execute=promisify(execFile),hash=v=>createHash('sha256').update(v).digest('hex');
const python=process.env.FULL_RECOVERY_PYTHON,operationsPython=process.env.OWNER_SNAPSHOT_PYTHON;
async function files(root){const result=[];async function walk(p=''){for(const name of await readdir(join(root,p))){const path=p?p+'/'+name:name,st=await lstat(join(root,path));if(st.isDirectory())await walk(path);else{assert.ok(st.isFile());result.push({path,bytes:st.size,mode:st.mode&0o777,sha256:hash(await readFile(join(root,path)))});}}}await walk();return result.sort((a,b)=>a.path.localeCompare(b.path));}
function connect(config,env){const child=spawn(python,['-I','-B','-m','amplifier_acp','--config',config],{env:{...process.env,...env},stdio:['pipe','pipe','pipe']});let id=0,stderr='';const pending=new Map();child.stderr.on('data',v=>stderr+=v);const ended=new Promise(resolve=>child.once('exit',code=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error(stderr));}pending.clear();resolve(code);}));const lines=createInterface({input:child.stdout});lines.on('line',line=>{const row=JSON.parse(line),p=pending.get(row.id);if(!p)return;pending.delete(row.id);clearTimeout(p.timer);row.error?p.reject(Error(JSON.stringify(row.error))):p.resolve(row.result);});return {request:(method,params)=>new Promise((resolve,reject)=>{const key=++id,timer=setTimeout(()=>{pending.delete(key);reject(Error('Native fixture timeout'));},60000);pending.set(key,{resolve,reject,timer});child.stdin.write(JSON.stringify({jsonrpc:'2.0',id:key,method,params})+'\n');}),close:async()=>{child.stdin.end();assert.equal(await ended,0,stderr);lines.close();}};}
test('actual signed 21-owner stopped capture and inactive restore retain native, message, media and original receipts',{skip:!python||!operationsPython||process.env.FULL_OWNER_ARCHIVE!=='1',timeout:240000},async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'full-owner-archive-'))),directory=join(root,'installation'),state=join(directory,'application'),workspace=join(root,'workspace'),home=join(root,'native-home'),appHome=join(root,'native-app'),web=join(root,'web');
 const git=await createHTTPSGitFixture(),assets=new Map();let installed,publisher;const observed=[];
 t.after(async()=>{if(installed){const r=await installed.supervisor.service.inspect();if(r.state==='running'){await installed.supervisor.service.stop({commandId:'cleanup',expected:r.identity});await installed.supervisor.service.waitFor('cleanup');}await installed.supervisor.close();}publisher?.closeAllConnections();if(publisher)await new Promise(r=>publisher.close(r));await git.close();console.error('Retained signed full-owner fixture:',root);});
 for(const p of [workspace,home,appHome,web,join(workspace,'.amplifier'),join(root,'native-events'),join(root,'native-checkpoints'),join(root,'native-sources')])await mkdir(p,{recursive:true});
 await writeFile(join(web,'index.html'),'<!doctype html><title>Disposable recovery qualification</title>');await writeFile(join(home,'settings.yaml'),'bundle:\n  app: []\n');
 const bundle=join(root,'bundle.yaml');await writeFile(bundle,'bundle:\n  name: cold-full-owner\n  version: 1.0.0\nproviders: []\n');
 const sid='01111111-1111-4111-8111-111111111111',saved=join(home,'projects',workspace.replaceAll('/','-'),'sessions',sid);await mkdir(saved,{recursive:true});
 const canonical={'metadata.json':JSON.stringify({session_id:sid,working_dir:workspace,status:'idle',name:'Preserved recovery fixture'}),'transcript.jsonl':JSON.stringify({role:'user',content:'Preserved voice text',metadata:{via:'call',message_id:'voice-message'}})+'\n','events.jsonl':'{"preserved":"canonical events"}\n'};for(const [name,body]of Object.entries(canonical))await writeFile(join(saved,name),body);
 const nativeFile=join(root,'native.json'),nativeEnv={PYTHONDONTWRITEBYTECODE:'1',AMPLIFIER_HOME:home,AMPLIFIER_WEB_HOME:appHome,AMPLIFIER_SESSION_STATE_HOME:join(root,'native-checkpoints'),AMPLIFIER_CONTEXT_INTELLIGENCE_BASE_PATH:join(root,'native-events'),AMPLIFIER_SOURCE_STORE:join(root,'native-sources')};
 const n={home,appHome,bundle,workerCommand:['/impossible/full-owner-worker'],adminWorkspaceRoots:[workspace],adminMaintenance:true,maintenanceFullNative:true,maintenanceExternalWriters:'stopped',maintenanceFullNativeRoots:{checkpoint:nativeEnv.AMPLIFIER_SESSION_STATE_HOME,events:nativeEnv.AMPLIFIER_CONTEXT_INTELLIGENCE_BASE_PATH,sources:nativeEnv.AMPLIFIER_SOURCE_STORE,bundle},transferAuthorityDirectory:join(state,'capabilities/portability'),transferWorkspaceRoots:[root]};await writeFile(nativeFile,JSON.stringify(n),{mode:0o600});
 const ownerPython=join(root,'owner-python');await writeFile(ownerPython,'#!/bin/sh\nexec '+"'"+python.replaceAll("'","'\\''")+"'"+' -I -B "$@"\n',{mode:0o700});
 const application={account:'full-recovery-fixture',webDirectory:web,defaultWorkspace:workspace,allowedWorkspaceRoots:[root],host:{managedSessionRoot:join(state,'managed')},manualIngress:{stateDirectory:join(state,'ingress')},engines:[{id:'amplifier',command:python,args:['-I','-B','-m','amplifier_acp','--config',nativeFile],env:nativeEnv}],nativeAdmin:{engine:'amplifier'},maintenance:{},recovery:{authorization:'local-account'},historyImport:{},historyCleanup:true,managedFiles:true,portability:{python:ownerPython,engines:['amplifier'],stageDir:join(state,'transfer-stages'),exchangeDir:join(state,'transfer-exchange')},...Object.fromEntries(['operations','notifications','diagnostics','coordination','recall','publishing','worktrees','feedback','workspaces','mcp','media'].map(k=>[k,{python:k==='operations'?operationsPython:ownerPython,env:{PYTHONDONTWRITEBYTECODE:'1'}}])),catalogProcess:{command:python,args:['-I','-B','-m','amplifier_session_catalog','serve','--db',join(state,'catalog.sqlite'),'--home',home,'--app-home',appHome,'--workspace',workspace,'--scan-interval','0','--workspace-check-interval','0'],env:{PYTHONDONTWRITEBYTECODE:'1'}}};
 const distribution=dirname(dirname(fileURLToPath(import.meta.url))),packed=JSON.parse((await execute('npm',['pack','--json','--pack-destination',root],{cwd:distribution,maxBuffer:1024*1024})).stdout)[0],candidate=join(root,'candidate');await mkdir(candidate);await execute('tar',['-xzf',join(root,packed.filename),'-C',candidate]);
 await copyFile(new URL('./full-owner-archive-fixture.mjs',import.meta.url),join(candidate,'package/src/full-owner-archive-fixture.mjs'));
 const {installProductionDistribution,createCoherentInstallationArchive,inspectInstallationArchive,restoreInstallationArchive,createNativeCoherentCaptureAdapter}=await import(pathToFileURL(join(candidate,'package/src/index.js')));
 const sourceFiles=await files(join(candidate,'package')),components=[];for(const f of sourceFiles.filter(r=>r.path==='package.json'||/\bnode_modules\/(?:@[^/]+\/)?[^/]+\/package.json$/.test(r.path))){const pkg=JSON.parse(await readFile(join(candidate,'package',f.path),'utf8'));components.push({name:pkg.name,version:pkg.version,root:f.path==='package.json'?'':dirname(f.path),repository:git.repository,ref:'main',revision:git.first});}
 const archive=join(root,'signed-fixture.tgz');await execute('tar',['-czf',archive,'-C',candidate,'package'],{env:{...process.env,COPYFILE_DISABLE:'1'}});const bytes=await readFile(archive);
 publisher=createServer((req,res)=>{const body=assets.get(req.url);if(!body)res.writeHead(404);res.end(body);});await new Promise(r=>publisher.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+publisher.address().port;
 const release={identity:{id:'full-recovery-fixture',version:'1.0.0',revision:git.first,digest:''},entrypoint:'src/full-owner-archive-fixture.mjs',platform:process.platform,arch:process.arch,files:sourceFiles,components,artifact:{url:origin+'/release.tgz',sha256:hash(bytes),bytes:bytes.length}};release.identity.digest=updates.releaseDigest(release);assets.set('/release.tgz',bytes);
 const {publicKey,privateKey}=generateKeyPairSync('ed25519'),keys={fixture:publicKey.export({type:'spki',format:'pem'})},payload=Buffer.from(JSON.stringify({schema:'distribution-channel-v1',expiresAt:Date.now()+3600000,recommendedId:release.identity.id,releases:[release]}));assets.set('/channel.json',Buffer.from(JSON.stringify({schema:'distribution-signed-channel-v1',keyId:'fixture',payload:payload.toString('base64'),signature:sign(null,payload,privateKey).toString('base64')})));
 installed=await installProductionDistribution({schema:'unified-installation-v1',directory,dataScope:'full-recovery-owned',serviceLifecycle:{enabled:true},release:{channelUrl:origin+'/channel.json',trustedKeys:keys,accessScope:'owned-fixture',allowedArtifactOrigins:[origin],allowLoopbackHttp:true},sourceTracking:{sources:[{repository:git.repository,ref:'main'}],env:git.env},application});
 const ready=JSON.parse(await readFile(join(root,'archive-ready.json'),'utf8'));assert.equal(ready.owners.length,21);assert.equal(ready.agents,0);assert.equal(ready.staged.status,'sealed');
 const status=await installed.supervisor.service.inspect(),expected=status.identity;await installed.supervisor.service.stopForMaintenance({commandId:'archive-stop',expected});const stopped=await installed.supervisor.service.waitFor('archive-stop');assert.equal(stopped.status,'stopped',JSON.stringify(stopped));assert.equal(stopped.maintenanceStop,true);assert.deepEqual([...stopped.qualifiedOwners].sort(),[...ready.owners].sort());await installed.supervisor.close();installed=undefined;
 const staging=join(root,'native-staged');await mkdir(staging);const outputFile=join(root,'complete.unified');
 const acquireWriterExclusion=async context=>{const path=join(root,'fixture-retirement.lock'),fd=await open(path,'wx',0o600);let held=true;return {evidence:{policy:'operator-reviewed-retirement',noncooperatingWriters:'not-independently-observed',reviewDigest:hash('unique fixture all controlled child/owners joined and stopped')},assertHeld:async()=>{assert.ok(held);await lstat(path);return {active:true,...context,leaseId:'owned-fixture-retirement'};},release:async()=>{held=false;await fd.close();await rm(path);return {released:true};}};};
 const adapter=createNativeCoherentCaptureAdapter({engineId:'amplifier',cwd:workspace,stagingDirectory:staging,connect:async()=>connect(nativeFile,nativeEnv)});
 const request={directory,compositionInventory:ready.inventory,inventoryDigest:ready.inventory.digest,expected,stoppedCommandId:'archive-stop',outputFile,privateContentReviewed:true,includeCredentials:true,credentialsReviewed:true,requireCompleteProduct:true};
 await assert.rejects(createCoherentInstallationArchive({...request,outputFile:join(root,'misbound.unified')},{acquireWriterExclusion,nativeCaptures:[{...adapter,engineId:'foreign'}]}),/plan_mismatch/);
 await assert.rejects(createCoherentInstallationArchive({...request,outputFile:join(root,'omitted.unified')},{acquireWriterExclusion,nativeCaptures:[]}),/plan_mismatch/);
 await assert.rejects(createCoherentInstallationArchive({...request,outputFile:join(root,'duplicate.unified')},{acquireWriterExclusion,nativeCaptures:[adapter,adapter]}),/scope_invalid/);
 const receipt=await createCoherentInstallationArchive(request,{acquireWriterExclusion,nativeCaptures:[adapter]});assert.equal(receipt.completeProduct,true);assert.equal(receipt.captureRelease.state,'released');
 const review=await inspectInstallationArchive(outputFile);assert.equal(review.manifest.proof.qualifiedOwners.length,21);
 const destination=join(root,'restored');const restored=await restoreInstallationArchive({archiveFile:outputFile,destination,...receipt,privateContentReviewed:true});assert.equal(restored.inactive,true);assert.equal(restored.workReplayed,false);
 const restoredApp=join(destination,'roots/application');assert.deepEqual(await readFile(join(restoredApp,'capabilities/media/receipts/historical.json')),await readFile(join(state,'capabilities/media/receipts/historical.json')));
 const snapshotDir=hash('original-seven-stores');for(const file of await readdir(join(state,'snapshots',snapshotDir,'images')))assert.deepEqual(await readFile(join(restoredApp,'snapshots',snapshotDir,'images',file)),await readFile(join(state,'snapshots',snapshotDir,'images',file)));
 for(const [name,body]of Object.entries(canonical))assert.equal(hash(await readFile(join(saved,name))),hash(body));
 const descriptor=review.manifest.inventory.nativeArtifacts[0],nativeArchive=join(destination,'native',descriptor.id),nativeHash=createHash('sha256');for await(const chunk of createReadStream(nativeArchive))nativeHash.update(chunk);assert.equal(nativeHash.digest('hex'),descriptor.sha256);
 const verified=JSON.parse((await execute(python,['-I','-B','-c',`import tarfile,hashlib,json,sys
expected=json.loads(sys.argv[2]);seen={}
with tarfile.open(sys.argv[1]) as archive:
 for item in archive:
  if item.isfile() and '/${sid}/' in item.name and item.name.rsplit('/',1)[-1] in expected:
   name=item.name.rsplit('/',1)[-1];seen[name]=hashlib.sha256(archive.extractfile(item).read()).hexdigest()
assert seen==expected,(seen,expected)
print(json.dumps(seen))`,nativeArchive,JSON.stringify(Object.fromEntries(Object.entries(canonical).map(([name,body])=>[name,hash(body)])))])).stdout);assert.equal(Object.keys(verified).length,3);
 const evidence={schema:'actual-full-owner-recovery-v1',root,owners:ready.owners,stopped,staged:ready.staged,receipt,restored,canonicalSha256:Object.fromEntries(Object.entries(canonical).map(([k,v])=>[k,hash(v)])),packageCount:components.length,packageFileCount:sourceFiles.length,nodeArchiveSha256:hash(bytes),workReplayed:false,limits:['Owned signed child fixture; not production platform-stop proof.','Python code is exact supplied wheels over read-only dependency bases, not a self-contained 23-repository code archive.','Immutable historical unknown media receipt retained; active or uncertain transcript/call cases are separately refused.']};await writeFile(join(root,'acceptance.json'),JSON.stringify(evidence,null,2));
});
