import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createManagedFilesCapabilities} from '../src/managed-files.js';
const sid='ahp-session:/one',hash='a'.repeat(64),review={sessionId:sid,reviewId:'review',reviewHash:hash,expectedHistoryRevision:'history-one'};
const ctx={account:'account',origin:'ui',actorId:'user:one',clientId:'browser'};
const binding={fenceId:'service',commandId:'update',purpose:'distribution-update',instanceId:'owned',dataScope:'owned'};
const call=(owner,operation,args={},commandId='command',context=ctx,channel='ahp-root://')=>owner.action({version:1,topic:'managed-files',channel,operation:'managedFiles.'+operation,args,commandId},context);
async function fixture(t,host,extra={}){const directory=await mkdtemp(join(tmpdir(),'managed-facade-'));t.after(()=>rm(directory,{recursive:true,force:true}));return ()=>createManagedFilesCapabilities({directory,host:()=>host,authorize:async context=>{if(context.account!=='account')throw Error('Denied');},...extra});}
test('strict caller DTOs never convey paths, allocation authority or actor identity',async t=>{
 const calls=[],create=await fixture(t,{previewManagedFiles:async(...args)=>{calls.push(args);return {reviewId:'review',reviewHash:hash};}}),o=create();
 try{await call(o,'preview',{sessionId:sid});assert.deepEqual(calls[0],[sid,{}, {actorId:'user:one',clientId:'browser'}]);for(const extra of [{path:'/files'},{allocationId:'fake'},{actorId:'spoof'},{allocation:{}}])await assert.rejects(call(o,'preview',{sessionId:sid,...extra}));await assert.rejects(call(o,'preview',{sessionId:sid},'denied',{...ctx,account:'other'}),/Denied/);assert.equal(calls.length,1);}finally{await o.close();}
});
test('native-origin selected channel and root UI share one action, agents cannot choose another session',async t=>{
 const calls=[],create=await fixture(t,{previewManagedFiles:async(...args)=>{calls.push(args);return {};}}),o=create();
 try{const agent={account:'account',origin:'agent',actorId:'agent:native',session:sid};await call(o,'preview',{sessionId:sid},'agent',agent,sid);assert.deepEqual(calls[0][2],{actorId:'agent:native'});await call(o,'preview',{sessionId:sid},'root-agent',agent);await assert.rejects(call(o,'preview',{sessionId:'ahp-session:/other'},'cross',agent),/own trusted session/);await assert.rejects(call(o,'preview',{sessionId:sid},'cross-channel',agent,'ahp-session:/other'),/own session channel/);await assert.rejects(call(o,'preview',{sessionId:sid},'missing',{...agent,session:undefined},sid));assert.equal(calls.length,2);}finally{await o.close();}
});
test('lost effect acknowledgement recovers exact namespaced child without repeated disposal through held intake',async t=>{
 let effects=0;const receipts=new Map(),seen=[];const host={disposeManagedFiles:async(s,args)=>{effects++;assert.equal(s,sid);assert.notEqual(args.commandId,'outer');receipts.set(args.commandId,{status:'completed',commandId:args.commandId,session:sid});throw Error('Lost ack');},managedFilesReceipt:async(s,c)=>{seen.push([s,c]);return receipts.get(c);}};
 const reconciled=[],create=await fixture(t,host,{protection:()=>({receipt:()=>({state:'unknown'}),reconcile:async c=>{reconciled.push(c);return {state:'released'};}})});let o=create();
 try{await assert.rejects(call(o,'dispose',review,'outer'),/Lost ack/);const child=[...receipts.keys()][0];assert.match(child,/^managed-files:[a-f0-9]{64}$/);await o.quiescenceParticipant.acquire(binding);await o.close();o=create();const read=await call(o,'receipt',{sessionId:sid,commandId:'outer'});assert.equal(read.result.ownerCommandId,child);assert.equal(read.result.commandId,'outer');assert.equal(read.result.receipt.status,'completed');const result=await call(o,'reconcile',{sessionId:sid,commandId:'outer'});assert.deepEqual(reconciled,[child]);assert.equal(result.result.protection.state,'released');assert.equal(result.result.replayed,false);await assert.rejects(call(o,'dispose',review,'new'),/intake is closed/);assert.equal(effects,1);assert.deepEqual(seen,[[sid,child],[sid,child]]);}finally{await o.close();}
});
test('cold topic reads are metadata-only and schemas are cloned; all forwarding joins owner lifetime',async t=>{
 let finish,calls=0,idle=0;const host={managedFilesReceipt:async()=>{calls++;await new Promise(resolve=>finish=resolve);return null;}};const create=await fixture(t,host,{onMayBeIdle:()=>idle++}),o=create();
 try{const snapshot=await o.read({topic:'managed-files',scope:'host',uri:'amplifier-capability://managed-files?scope=host'},ctx);assert.equal(snapshot.data.managedFiles.preservesCanonical,true);assert.equal(calls,0);const schemas=o.actionSchemas();schemas['managedFiles.dispose'].schema.properties.reviewHash={};assert.notDeepEqual(o.actionSchemas(),schemas);assert.equal(o.quiescenceParticipant.retentionHide.version,1);assert.equal(o.quiescenceParticipant.serviceStop.version,1);assert.equal(o.quiescenceParticipant.managedFiles,undefined);
  const pending=call(o,'receipt',{sessionId:sid,commandId:'original'});await new Promise(r=>setImmediate(r));assert.equal(await o.quiescenceParticipant.acquire(binding),null);let closed=false;const closing=o.close().then(()=>closed=true);await new Promise(r=>setImmediate(r));assert.equal(closed,false);finish();await pending;await closing;assert.equal(idle,1);
 }finally{finish?.();await o.close();}
});
