import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';
import {createManagedFilesProtection} from '../src/managed-files-protection.js';
const session='ahp-session:/selected';
const allocation={allocationId:'01234567-1234-1234-1234-123456789abc',executionDirectory:'/owned/managed/files',allocationHash:'a'.repeat(64),treeHash:'b'.repeat(64),entryCount:1,bytes:5};
const input={commandId:'dispose',session,descendants:[],operation:'dispose-owned-files',reviewHash:'c'.repeat(64),allocation};
test('independently installed resources owner protects historical cross-session files through real coordinator',{skip:!process.env.MANAGED_RESOURCES_MODULE},async()=>{
 const {createResourcesCapability}=await import(pathToFileURL(process.env.MANAGED_RESOURCES_MODULE).href);
 const directory=await mkdtemp(join(tmpdir(),'managed-installed-owner-'));
 const resource=createResourcesCapability({directory:join(directory,'resource'),inspectSession:async session=>({session,workingDirectory:directory})});let nativeReads=0;
 const p=createManagedFilesProtection({directory:join(directory,'protection'),instanceId:'owned',dataScope:'owned',participants:[resource.quiescenceParticipant('capability:attachments')],readEffectReceipt:async()=>{nativeReads++;throw Error('No native effect should have run');}});
 try{const context={session:'ahp-session:/other',workingDirectory:allocation.executionDirectory};const artifact=resource.store.save(context,{kind:'code',title:'Source',path:allocation.executionDirectory+'/code.py',workspacePath:allocation.executionDirectory},{content:'copied'});resource.store.save(context,{kind:'code',title:'Detached'},{content:'new'},{id:artifact.id,expectedRevision:1,force:true});resource.store.body=()=>{throw Error('Protection must not hydrate history bodies');};await assert.rejects(p.acquire(input),e=>e.data.executed===false&&e.data.protectionState==='refused');const receipt=p.receipt('dispose');assert.equal(receipt.owners[0].id,'capability:attachments');assert.deepEqual(receipt.owners[0].references.protected,[{session,reasons:['artifact-file-source']}]);assert.equal(nativeReads,0);assert.equal(resource.store.db.prepare('SELECT count(*) n FROM versions').get().n,2);const lease=await resource.quiescenceParticipant('capability:attachments').acquire({fenceId:'subsequent',commandId:'subsequent',purpose:'managed-files-disposal',instanceId:'owned',dataScope:'owned'});assert.ok(lease);await lease.release('unchanged',{kind:'admission-refused'});}finally{p.close();resource.close();await rm(directory,{recursive:true,force:true});}
});
