import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,realpath,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const {composeNaming}=await import(process.env.AMPLIFIER_NAMING_COMPOSITOR??'../src/naming.js');
const enabled=!!process.env.AMPLIFIER_NAMING_HOST&&!!process.env.AMPLIFIER_NATIVE_CAPABILITY_MODULE&&!!process.env.AMPLIFIER_NAMING_PYTHON;
async function waitFor(check){const end=Date.now()+5000;while(Date.now()<end){if(check())return;await new Promise(r=>setTimeout(r,5));}throw Error('Naming composition fixture timed out');}
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('actual packaged naming ports project accepted automatic metadata and preserve manual/Auto/generation races',{skip:!enabled},async()=>{
 const {createHost}=await import(pathToFileURL(process.env.AMPLIFIER_NAMING_HOST).href),{AdminConnection,createNativeCapabilities}=await import(pathToFileURL(process.env.AMPLIFIER_NATIVE_CAPABILITY_MODULE).href),{AhpClient}=await import('@microsoft/agent-host-protocol/client'),{WebSocketTransport}=await import('@microsoft/agent-host-protocol/ws');
 const root=await realpath(await mkdtemp(join(tmpdir(),'root-naming-union-'))),cwd=join(root,'workspace'),home=join(root,'native'),session='ahp-session:/owned',nativeSessionId='named';await mkdir(cwd);const directory=join(home,'projects',cwd.replaceAll('/','-'),'sessions',nativeSessionId);await mkdir(directory,{recursive:true});await writeFile(join(directory,'metadata.json'),JSON.stringify({session_id:nativeSessionId,name:'Fallback',name_source:'fallback',name_revision:0}));const transcript='{"role":"user","content":"Owned first-turn fixture"}\n';await writeFile(join(directory,'transcript.jsonl'),transcript);const config=join(root,'native.json');await writeFile(config,JSON.stringify({home,appHome:join(root,'app'),adminWorkspaceRoots:[cwd],workerCommand:['/must/not/start']}));
 const admin=new AdminConnection({command:process.env.AMPLIFIER_NAMING_PYTHON,args:['-I','-B','-m','amplifier_acp','--config',config],cwd,resolveWorkspace:()=>cwd});let host,client,naming;let generated=0,gate,entered;const cached=new Map();
 try{
  naming=await composeNaming({admin,engineId:'native',host:()=>host,inspectSession:s=>host.inspectSession(s),hostPortsSupported:true});assert.equal(naming.available,true);
  const time=new Date().toISOString();host=await createHost({stateDirectory:join(root,'host'),allowedWorkspaceRoots:[cwd],engines:[{id:'native',label:'Native',command:'/must/not/start-host-worker',sessionMetadata:naming.sessionMetadata}],catalog:{list:async()=>({items:[]}),get:async uri=>uri===session?{uri:session,engineId:'native',nativeSessionId,workingDirectory:cwd,title:'Fallback',createdAt:time,modifiedAt:time,status:'idle'}:undefined,upsert:async()=>{}},quiescence:{instanceId:'owned',dataScope:'owned',requiredOwners:['native-admin'],verifyRelease:async()=>{throw Error('No release authority is exercised by this fixture');},coverage:{},participants:[admin.quiescenceParticipant]}});
  client=new AhpClient(await WebSocketTransport.connect(host.url));client.connect();await client.initialize({clientId:'naming-ui',protocolVersions:['0.9.0'],initialSubscriptions:['ahp-root://']});await host.readSessionTitle(session);const sub=await client.subscribe(session),events=[];void(async()=>{for await(const e of sub.subscription)if(e.type==='action')events.push(e.params);})();
  const context={session,nativeSessionId,workingDirectory:cwd},notify=revision=>naming.event(context,{sessionId:nativeSessionId,event:{type:'session.naming',name:'untrusted stale event text',nameRevision:revision}});
  const read=()=>admin.performNaming({sessionId:nativeSessionId,cwd,operation:'read',args:{}});
  const accepted=await admin.performNaming({sessionId:nativeSessionId,cwd,operation:'commit',args:{commandId:'accepted-first-turn-fixture',candidate:{name:'Accepted automatic title',name_revision:0,name_policy_revision:0}}});assert.equal(accepted.applied,true);
  const locked=deferred(),unlock=deferred();const holder=host.commitSessionTitle(session,{commandId:'owned-event-delivery-lock'},async()=>{assert.equal(notify(1),true);locked.resolve();await unlock.promise;return {applied:false};});await locked.promise;assert.equal(naming.diagnostics().pending,1);assert.ok(host.inspectQuiescence().activeAdmissions>=2);assert.equal((await host.admitQuiescence({commandId:'no-retirement-while-projection',purpose:'distribution-update'})).admitted,false);unlock.resolve();await holder;await naming.drain();await waitFor(()=>events.some(e=>e.action.type==='session/titleChanged'&&e.action.title==='Accepted automatic title'));assert.equal(host.store.get(session).state.title,'Accepted automatic title');assert.equal(naming.diagnostics().failures,0);
  async function manual(title){const before=events.filter(e=>e.action.type==='session/titleChanged'&&e.origin?.clientId==='naming-ui'&&!e.rejectionReason).length;client.dispatch(session,{type:'session/titleChanged',title});await waitFor(()=>events.filter(e=>e.action.type==='session/titleChanged'&&e.origin?.clientId==='naming-ui'&&!e.rejectionReason).length>before);}
  await manual('Newer manual');assert.equal((await read()).naming.automatic,false);notify(0);notify(1);await naming.drain();assert.equal(host.store.get(session).state.title,'Newer manual');assert.equal(naming.diagnostics().failures,0);
  for(const bad of [{sessionId:'foreign',event:{type:'session.naming',name:'bad',nameRevision:2}},{sessionId:nativeSessionId,event:{type:'session.naming',name:'bad',nameRevision:-1}}])assert.equal(naming.event(context,bad),false);
  naming.event({...context,nativeSessionId:'foreign'},{sessionId:'foreign',event:{type:'session.naming',name:'bad',nameRevision:2}});await naming.drain();assert.equal(host.store.get(session).state.title,'Newer manual');assert.equal(generated,0);
  const provider=createNativeCapabilities({...naming.ports,nativeControl:async(_scope,operation,args)=>{assert.equal(operation,'session.naming.generate');if(cached.has(args.commandId))return cached.get(args.commandId);generated++;const before=await read(),candidate={name:'Explicit fixture suggestion',name_revision:before.naming.nameRevision,name_policy_revision:before.naming.policyRevision};cached.set(args.commandId,candidate);entered?.resolve();if(gate)await gate.promise;return candidate;}});await provider.negotiateNaming();assert.ok(provider.manifest.actions['session.naming']);
  const action=(commandId,args)=>provider.action({channel:session,topic:'runtime-control',operation:'session.naming',version:1,commandId,args},{clientId:'naming-ui',session:{uri:session}});
  const titleCount=events.filter(e=>e.action.type==='session/titleChanged').length,revision=(await host.readSessionTitle(session)).titleRevision;assert.equal((await action('auto-on',{automatic:true})).accepted,true);await waitFor(()=>events.some(e=>e.action._meta?.['amplifier.dev/sessionMetadata']?.naming?.automatic===true));assert.equal(events.filter(e=>e.action.type==='session/titleChanged').length,titleCount);assert.equal((await host.readSessionTitle(session)).titleRevision,revision);
  gate=deferred();entered=deferred();const pending=action('explicit-race',{regenerate:true});await entered.promise;await manual('Manual during suggestion');gate.resolve();assert.equal((await pending).accepted,false);assert.equal((await read()).title,'Manual during suggestion');gate=undefined;entered=undefined;assert.equal((await action('explicit-race',{regenerate:true})).accepted,false);assert.equal(generated,1);
  assert.equal((await action('explicit-next',{regenerate:true})).accepted,true);assert.equal((await read()).title,'Explicit fixture suggestion');assert.equal((await read()).naming.automatic,false);assert.equal(generated,2);
  assert.equal(host.diagnostics().activeAgents,0);assert.equal(await readFile(join(directory,'transcript.jsonl'),'utf8'),transcript);assert.equal((await naming.close()).pending,0);assert.equal(notify(99),false);
 }finally{gate?.resolve();if(naming)await naming.close();if(client)await client.shutdown();if(host)await host.close();await admin.close();await rm(root,{recursive:true,force:true});}
});

const factoryEnabled=enabled&&!!process.env.AMPLIFIER_NAMING_DISTRIBUTION;
test('actual createDistribution binds packaged passive naming and nativeEvent with cold owned state',{skip:!factoryEnabled},async()=>{
 const {createDistribution}=await import(pathToFileURL(process.env.AMPLIFIER_NAMING_DISTRIBUTION).href);
 const root=await realpath(await mkdtemp(join(tmpdir(),'distribution-naming-'))),cwd=join(root,'workspace'),home=join(root,'native'),session='ahp-session:/factory',nativeSessionId='factory';await mkdir(cwd);const directory=join(home,'projects',cwd.replaceAll('/','-'),'sessions',nativeSessionId);await mkdir(directory,{recursive:true});const metadata=join(directory,'metadata.json');await writeFile(metadata,JSON.stringify({session_id:nativeSessionId,name:'Factory fallback',name_source:'fallback',name_revision:0}));const transcript='{"role":"user","content":"Fixture only"}\n';await writeFile(join(directory,'transcript.jsonl'),transcript);const config=join(root,'native.json');await writeFile(config,JSON.stringify({home,appHome:join(root,'app'),adminWorkspaceRoots:[cwd],workerCommand:['/must/not/start']}));
 const time=new Date().toISOString(),record={uri:session,engineId:'native',nativeSessionId,workingDirectory:cwd,title:'Factory fallback',createdAt:time,modifiedAt:time,status:'idle'},catalog=join(root,'catalog.mjs');
 await writeFile(catalog,`import readline from 'node:readline';const record=${JSON.stringify(record)};for await(const line of readline.createInterface({input:process.stdin})){const request=JSON.parse(line);const result=request.method==='get'?record:request.method==='list'?{items:[]}:{};process.stdout.write(JSON.stringify({id:request.id,result})+'\\n');}`);
 let app;try{
  app=await createDistribution({account:'fixture',stateDirectory:join(root,'state'),defaultWorkspace:cwd,allowedWorkspaceRoots:[cwd],webDirectory:cwd,engines:[{id:'native',command:process.env.AMPLIFIER_NAMING_PYTHON,args:['-I','-B','-m','amplifier_acp','--config',config]}],nativeAdmin:{engine:'native'},catalogProcess:{command:process.execPath,args:[catalog]}},{authorize:async()=>({account:'fixture'})});
  assert.ok(app.capabilities.manifest.actions['session.naming']);assert.equal((await app.host.readSessionTitle(session)).title,'Factory fallback');assert.equal(app.host.diagnostics().activeAgents,0);
  // Accepted Native metadata is the fixture boundary; the event travels through
  // the real factory callback and only rereads passive canonical authority.
  await writeFile(metadata,JSON.stringify({session_id:nativeSessionId,name:'Factory automatic',name_source:'generated',name_revision:1}));
  await app.host.config.nativeEvent({session,nativeSessionId,workingDirectory:cwd},{sessionId:nativeSessionId,event:{type:'session.naming',name:'advisory',nameRevision:1}});
  await waitFor(()=>app.namingDiagnostics().pending===0);assert.equal(app.namingDiagnostics().failures,0);assert.equal(app.host.store.get(session).state.title,'Factory automatic');assert.equal(app.host.diagnostics().activeAgents,0);assert.equal(await readFile(join(directory,'transcript.jsonl'),'utf8'),transcript);
 }finally{await app?.close();await rm(root,{recursive:true,force:true});}
});
