import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID,createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {once} from 'node:events';import {WebSocket} from 'ws';
import {createDistribution} from '../src/index.js';
const python=process.env.AMPLIFIER_ACP_PYTHON,owners=process.env.UNIFIED_OWNERS_PYTHON,mcp=process.env.MCP_BROKER_PYTHON,provider=process.env.RECOVERY_NATIVE_PROVIDER;
test('assembled recovery holds every configured owner, retires native work and exports only reviewed bytes',{skip:!python||!owners||!mcp||!provider,timeout:120000},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'distribution-recovery-')),workspace=join(directory,'workspace'),web=join(directory,'web'),home=join(directory,'home');for(const path of [workspace,web,home])await mkdir(path);await writeFile(join(web,'index.html'),'<html><head></head><body>Fixture</body></html>');
 const context=execFileSync(python,['-I','-c','import importlib.util,pathlib;print(pathlib.Path(importlib.util.find_spec("amplifier_module_context_simple").origin).parent)'],{encoding:'utf8'}).trim();
 const bundle=join(directory,'fixture.yaml');await writeFile(bundle,`bundle:\n  name: recovery-distribution\n  version: 1.0.0\nsession:\n  orchestrator:\n    module: loop-live\n  context:\n    module: context-simple\n    source: ${context}\nproviders:\n  - module: provider-fixture\n    source: ${provider}\n`);await writeFile(join(home,'settings.yaml'),'bundle:\n  app: []\n');
 const config=join(directory,'native.json');await writeFile(config,JSON.stringify({home,appHome:join(directory,'native-app'),bundle,adminWorkspaceRoots:[workspace],adminMaintenance:true,transferAuthorityDirectory:join(directory,'state/capabilities/portability'),transferWorkspaceRoots:[workspace],maintenanceExternalWriters:'foundation-cooperative'}));let app,socket;
 try{
  app=await createDistribution({account:'recovery-fixture',stateDirectory:join(directory,'state'),defaultWorkspace:workspace,allowedWorkspaceRoots:[workspace],webDirectory:web,engines:[{id:'native',command:python,args:['-I','-m','amplifier_acp','--config',config]}],nativeAdmin:{engine:'native'},portability:{python:owners,engines:['native'],stageDir:join(workspace,'stages'),exchangeDir:join(workspace,'exchange')},recovery:{},quiescence:{instanceId:'assembly-original',dataScope:'assembly-private',timeoutMs:30000},operations:{python:owners},coordination:{python:owners},recall:{python:owners},publishing:{python:owners},worktrees:{python:owners},feedback:{python:owners},workspaces:{python:owners},mcp:{python:mcp},media:{python:owners},catalogProcess:{command:owners,args:['-I','-m','amplifier_session_catalog','serve','--db',join(directory,'catalog.sqlite'),'--home',home,'--app-home',join(directory,'native-app'),'--scan-interval','0','--workspace-check-interval','0']}},{authorizeRecovery:async caller=>{assert.equal(caller.account,'recovery-fixture');return {accountId:'recovery-fixture'};}});
  socket=new WebSocket(app.url.replace(/^http/,'ws')+'/ahp',{origin:app.url});await once(socket,'open');let next=0;const pending=new Map();socket.on('message',bytes=>{const row=JSON.parse(bytes),entry=pending.get(row.id);if(entry){pending.delete(row.id);clearTimeout(entry.timer);row.error?entry.reject(Error(row.error.message)):entry.resolve(row.result);}});
  const request=(method,params)=>new Promise((resolve,reject)=>{const id=++next,timer=setTimeout(()=>reject(Error('Timed out: '+method)),30000);pending.set(id,{resolve,reject,timer});socket.send(JSON.stringify({jsonrpc:'2.0',id,method,params}));});
  await request('initialize',{channel:'ahp-root://',clientId:'fixture',protocolVersions:['0.9.0'],initialSubscriptions:['ahp-root://']});const session='ahp-session:/'+randomUUID();await request('createSession',{channel:session,provider:'native',workingDirectories:[pathToFileURL(workspace).href]});
  assert.equal(app.host.diagnostics().activeAgents,1);
  const call=async(operation,args={})=>(await request('x-amplifier/capabilityAction',{version:1,topic:'recovery',channel:'ahp-root://',operation,args,commandId:randomUUID()})).result;
  const settled=async id=>{for(let n=0;n<1500;n++){const row=await call('recovery.job',{jobId:id});if(['prepared','succeeded','refused','unknown'].includes(row.state))return row;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Recovery did not settle');};
  const prepared=await settled((await call('recovery.prepare',{sessions:[session],parts:['session-history','session-state'],privateContentReviewed:true})).id);assert.equal(prepared.state,'prepared',JSON.stringify(prepared));assert.equal(app.host.diagnostics().activeAgents,0);assert.equal(app.host.inspectQuiescence().intakeClosed,false);
  const snapshot=await settled((await call('recovery.snapshot',{preparedJobId:prepared.id,previewHash:prepared.previewHash})).id);assert.equal(snapshot.state,'succeeded',JSON.stringify(snapshot));let offset=0;const chunks=[];
  while(offset<snapshot.result.bytes){const uri=new URL(snapshot.result.resourceUri);uri.searchParams.set('offset',String(offset));uri.searchParams.set('maxBytes','8192');const page=await request('resourceRead',{channel:'ahp-root://',uri:uri.href,encoding:'base64'}),bytes=Buffer.from(page.data,'base64');assert.ok(bytes.length);chunks.push(bytes);offset+=bytes.length;}
  assert.equal(createHash('sha256').update(Buffer.concat(chunks)).digest('hex'),snapshot.result.sha256);assert.equal(app.host.inspectQuiescence().intakeClosed,false);assert.equal(app.host.diagnostics().activeAgents,0);
  assert.ok(app.quiescence.requiredOwners.length>=13);assert.equal(app.quiescence.requiredOwners.length,app.quiescence.participants.length);
 }finally{socket?.terminate();await app?.close();await rm(directory,{recursive:true,force:true});}
});
