import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash,randomUUID} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {createServer,globalAgent} from 'node:https';
import {renderTerminalInstaller} from '../src/terminal-installer.js';
import {extractRuntime,installTerminal} from '../src/terminal-install-client.mjs';

const hash=x=>createHash('sha256').update(x).digest('hex');
const command=(bin,args)=>execFileSync(bin,args,{encoding:'utf8'}).trim();
const q=s=>"'"+s.replaceAll("'","'\\''")+"'";
const target={os:process.platform==='darwin'?'macos':'linux',arch:process.arch==='arm64'?'arm64':'x86_64',wheelTag:process.platform==='darwin'?'py3-none-macosx_11_0_'+(process.arch==='arm64'?'arm64':'x86_64'):'py3-none-linux_'+(process.arch==='arm64'?'aarch64':'x86_64'),osFloor:process.platform==='darwin'?'11.0':null};
function tar(rows){const chunks=[];for(const row of rows){const data=Buffer.from(row.data??''),b=Buffer.alloc(512);b.write(row.name,0,100);b.write((row.mode??0o700).toString(8).padStart(7,'0')+'\0',100,8);b.write('0000000\0',108,8);b.write('0000000\0',116,8);b.write(data.length.toString(8).padStart(11,'0')+'\0',124,12);b.write('00000000000\0',136,12);b.fill(32,148,156);b.write(row.type??'0',156,1);if(row.link)b.write(row.link,157,100);b.write('ustar\0',257,6);b.write('00',263,2);b.write([...b].reduce((a,v)=>a+v,0).toString(8).padStart(6,'0')+'\0 ',148,8);chunks.push(b,data,Buffer.alloc((512-data.length%512)%512));}return gzipSync(Buffer.concat([...chunks,Buffer.alloc(1024)]));}
const python=command('python3',['-I','-B','-c','import sys; print(sys.executable)']),pythonVersion=command(python,['-I','-B','-c','import sys; print(".".join(map(str,sys.version_info[:3])))']);
const nodeBytes=Buffer.from('#!/bin/sh\nexec '+q(process.execPath)+' "$@"\n');
function descriptor(bytes,name,version,origin='https://example.invalid'){return{version,url:origin+'/'+name+'.tar.gz',bytes:bytes.length,sha256:hash(bytes),archive:'tar.gz',archiveRoot:name,executable:'bin/'+name,target:{os:target.os,arch:target.arch},...(name==='node'?{executableSha256:hash(nodeBytes)}:{})};}
function release(bytes){const filename='amplifier_unified_client_tui-0.5.0rc2-'+target.wheelTag+'.whl';return{format:'amplifier-unified-client-tui.release',schemaVersion:1,package:{name:'amplifier-unified-client-tui',version:'0.5.0rc2'},source:{repository:'https://github.com/microsoft/amplifier-unified-client-tui',commit:'a'.repeat(40)},compatibility:{ahpVersions:['0.9.0'],sdkVersion:'0.9.0',pythonRequires:'>=3.11',nodeRequires:'>=22'},artifacts:[{filename,bytes:bytes.length,sha256:hash(bytes),target,qualification:{status:'qualified',evidenceFilename:filename.replace('.whl','.qualification.json'),evidenceSha256:'b'.repeat(64),installedIsolation:true,privacy:true,actualPTY:true,testedPython:pythonVersion,testedNode:process.versions.node,testedOS:'owned fixture',minimumGlibc:target.os==='linux'?'2.17':null}}]};}
function input(wheel=Buffer.from('fixture-wheel')){const r=release(wheel),node=tar([{name:'node/bin/node',data:nodeBytes}]),py=tar([{name:'python/bin/python',data:'#!/bin/sh\nexec '+q(python)+' "$@"\n'}]);return{preparation:{preparationId:randomUUID(),grant:'private-grant-sentinel',origin:'https://example.invalid',expiresAt:Math.floor(Date.now()/1000)+1800,artifactId:hash(wheel),name:'Owned terminal'},artifact:{release:r,filename:r.artifacts[0].filename,wheelBytes:wheel},runtimes:{node:descriptor(node,'node',process.versions.node),python:descriptor(py,'python',pythonVersion)}};}

test('pure renderer binds platform/runtime/package/bytes; private payload is shell-safe',()=>{const p=input();p.preparation.name="a'; $(touch NO)";const r=renderTerminalInstaller(p);assert.equal(r.sha256,hash(r.bytes));assert.equal(r.filename,'amplifier-terminal-'+p.preparation.preparationId+'.sh');assert(!r.bytes.includes('private-grant-sentinel'));assert(!r.bytes.includes("$(touch NO)"));assert(r.bytes.includes('AMPLIFIER_PROFILE'));const parsed=JSON.parse(Buffer.from(r.bytes.toString().match(/AMPLIFIER_PROFILE'\n([^\n]+)/)[1],'base64'));assert.equal(parsed.grant,p.preparation.grant);assert.equal(parsed.artifact.sha256,p.artifact.release.artifacts[0].sha256);execFileSync('/bin/bash',['-n'],{input:r.bytes,stdio:['pipe','pipe','pipe']});});

test('renderer refuses changed wheel, old package/protocol, insecure sources and mismatched runtimes',()=>{for(const mutate of [p=>p.artifact.wheelBytes[0]^=1,p=>p.artifact.release.package.name='amplifier-app-tui',p=>p.artifact.release.compatibility.sdkVersion='1',p=>p.preparation.origin='http://localhost',p=>p.runtimes.node.url='https://secret@example.invalid/node',p=>p.runtimes.node.executable='../node',p=>p.runtimes.node.version='20.0.0',p=>p.runtimes.python.version='3.10.0',p=>p.runtimes.node.target.arch='other',p=>p.preparation.preparationId='../escape',p=>p.preparation.caPem='-----BEGIN PRIVATE KEY-----']){const p=input();mutate(p);assert.throws(()=>renderTerminalInstaller(p),/Invalid qualified/);}});

test('streaming extraction supports internal links and refuses escaping, duplicate and special members',async()=>{const base=await fs.mkdtemp(join(tmpdir(),'terminal-tar-'));try{const archive=join(base,'a.tgz');await fs.writeFile(archive,tar([{name:'python/bin/python3',data:'ok'},{name:'python/bin/python',type:'2',link:'python3'},{name:'python/bin/other',type:'1',link:'python/bin/python3'}]));await extractRuntime(archive,join(base,'good'),'python');assert.equal(await fs.readFile(join(base,'good/bin/python'),'utf8'),'ok');for(const [index,rows] of [[{name:'python/../../escape',data:'no'}],[{name:'python/a',type:'2',link:'../../escape'}],[{name:'python/a',type:'3'}],[{name:'python/a',data:'one'},{name:'python/a',data:'two'}],[{name:'python/link',type:'2',link:'real'},{name:'python/link/data',data:'no'}]].entries()){await fs.writeFile(archive,tar(rows));await assert.rejects(extractRuntime(archive,join(base,'bad'+index),'python'));}assert(!await fs.stat(join(base,'escape')).catch(()=>false));}finally{await fs.rm(base,{recursive:true,force:true});}});

async function fixture(){const base=await fs.mkdtemp(join(tmpdir(),'terminal-stage-'));const key=join(base,'key.pem'),cert=join(base,'cert.pem');execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=127.0.0.1','-addext','subjectAltName=IP:127.0.0.1'],{stdio:'ignore'});const ca=await fs.readFile(cert);const prior=globalAgent.options.ca;globalAgent.options.ca=ca;
 const nodeArchive=tar([{name:'node/bin/node',data:nodeBytes}]);const py=tar([{name:'python/bin/python',data:'#!/bin/sh\nexec '+q(python)+' "$@"\n'}]);let mode='success',requests=0;const bodies=[];
 const server=createServer({key:await fs.readFile(key),cert:ca},async(req,res)=>{if(req.url==='/node.tar.gz'){res.writeHead(200);return res.end(nodeArchive);}if(req.url==='/python.tar.gz'){res.writeHead(200);return res.end(py);}if(req.url!=='/setup/terminal/redeem'){res.writeHead(404);return res.end();}requests++;let body='';for await(const chunk of req)body+=chunk;const args=JSON.parse(body);bodies.push(args);if(mode==='lost'){req.socket.destroy();return;}if(mode==='redirect'){res.writeHead(307,{Location:'/elsewhere'});return res.end();}if(mode==='consumed'){res.writeHead(409);return res.end(JSON.stringify({version:1,status:'consumed',credentialAvailable:false}));}const result={version:1,status:'registered',...args,origin,name:'Owned terminal',deviceId:'device-'+requests,token:'private-device-token-'+('t'.repeat(40)),createdAt:Math.floor(Date.now()/1000)};delete result.grant;res.writeHead(201,{'Content-Type':'application/json'});res.end(JSON.stringify(result));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='https://127.0.0.1:'+server.address().port;
 const work=join(base,'work');await fs.mkdir(work,{mode:0o700});const fakeNode=join(base,'node');await fs.writeFile(fakeNode,nodeBytes,{mode:0o700});
 function wheel(dependencies=false){const p=join(work,'client.whl');const script=`import zipfile,sys\np=sys.argv[1]\nwith zipfile.ZipFile(p,'w') as z:\n z.writestr('amplifier_tui/__init__.py','')\n z.writestr('amplifier_tui/launcher.py','from pathlib import Path\\ndef executable(): return Path(__file__).parent/\"_bin/amplifier-ratatui\"\\n')\n z.writestr('amplifier_tui/connected.py','import argparse\\nargparse.ArgumentParser().parse_args()\\n')\n z.writestr('amplifier_tui/_ahp/bridge.mjs','// fixture only\\n')\n b=zipfile.ZipInfo('amplifier_tui/_bin/amplifier-ratatui'); b.external_attr=0o100755<<16; z.writestr(b,'#!/bin/sh\\nexit 0\\n')\n z.writestr('amplifier_unified_client_tui-0.5.0rc2.dist-info/METADATA','Metadata-Version: 2.1\\nName: amplifier-unified-client-tui\\nVersion: 0.5.0rc2\\nRequires-Python: >=3.11\\n${dependencies?'Requires-Dist: not-allowed\\n':''}')\n z.writestr('amplifier_unified_client_tui-0.5.0rc2.dist-info/WHEEL','Wheel-Version: 1.0\\nGenerator: owned-fixture\\nRoot-Is-Purelib: true\\nTag: py3-none-any\\n')\n z.writestr('amplifier_unified_client_tui-0.5.0rc2.dist-info/RECORD','')\n`;command(python,['-I','-B','-c',script,p]);return fs.readFile(p);}
 let rendered;async function profile(dependencies=false){await fs.rm(join(work,'python.tar.gz'),{force:true});const bytes=await wheel(dependencies),i=input(bytes),r=i.artifact.release;i.preparation.origin=origin;i.preparation.caPem=ca.toString();i.runtimes.python=descriptor(py,'python',pythonVersion,origin);i.runtimes.node=descriptor(nodeArchive,'node',process.versions.node,origin);rendered=renderTerminalInstaller(i);return JSON.parse(Buffer.from(rendered.bytes.toString().match(/AMPLIFIER_PROFILE'\n([^\n]+)/)[1],'base64'));}
 return {base,work,cert,script:()=>rendered.bytes,root:join(base,'install'),fakeNode,profile,setMode:v=>{mode=v;},requests:()=>requests,bodies,close:async()=>{globalAgent.options.ca=prior;await new Promise(r=>server.close(r));await fs.rm(base,{recursive:true,force:true});}};
}

test('real isolated wheel staging validates before enrollment; saves private connection and preserves original command',async()=>{const f=await fixture();try{const p=await f.profile();const result=await installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode});assert.equal(result.status,'installed');assert.equal(result.connected,false);assert.throws(()=>execFileSync(result.launch,['--ser','https://elsewhere.invalid'],{stdio:'pipe'}));assert.equal(f.requests(),1);const request=f.bodies[0];assert.deepEqual(Object.keys(request).sort(),['artifactId','grant','preparationId','redemptionId']);const dir=join(f.root,'connections',result.deviceId);assert.equal((await fs.stat(join(dir,'token'))).mode&0o777,0o600);assert.equal((await fs.stat(dir)).mode&0o777,0o700);assert.equal((await fs.stat(join(dir,'launch'))).mode&0o777,0o700);const receipt=await fs.readFile(join(f.root,'preparations',p.preparationId+'.json'),'utf8');assert(!receipt.includes('private-device-token'));assert(!receipt.includes(p.grant));assert.equal(JSON.parse(receipt).redemptionId,request.redemptionId);await assert.rejects(installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode}),/original-setup-attempt/);assert.equal(f.requests(),1);assert(!String(await fs.readFile(result.launch)).includes('private-device-token'));}finally{await f.close();}});

test('required dependencies refuse before enrollment and do not replace the old default',async()=>{const f=await fixture();try{const p=await f.profile(true);await assert.rejects(installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode}),/client-validation-failed/);assert.equal(f.requests(),0);assert.equal(JSON.parse(await fs.readFile(join(f.root,'preparations',p.preparationId+'.json'))).phase,'staging-refused');assert.deepEqual(await fs.readdir(join(f.root,'versions')),[]);assert(!await fs.stat(join(f.root,'default.json')).catch(()=>false));}finally{await f.close();}});

test('lost redemption response retains exact attempt and staged files without retry or default replacement',async()=>{const f=await fixture();try{const p=await f.profile();f.setMode('lost');await assert.rejects(installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode}),/enrollment-response-unconfirmed/);const before=JSON.parse(await fs.readFile(join(f.root,'preparations',p.preparationId+'.json')));assert.equal(before.phase,'enrollment-unknown');assert.equal(before.redemptionId,f.bodies[0].redemptionId);assert(await fs.stat(before.candidate));await assert.rejects(installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode}),/original-setup-attempt/);assert.equal(f.requests(),1);assert(!await fs.stat(join(f.root,'default.json')).catch(()=>false));}finally{await f.close();}});

test('credential redirect and consumed response never follow or issue another request',async()=>{for(const mode of ['redirect','consumed']){const f=await fixture();try{const p=await f.profile();f.setMode(mode);await assert.rejects(installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode}),mode==='redirect'?/credential-redirect-refused/:/setup-already-consumed/);assert.equal(f.requests(),1);const receipt=JSON.parse(await fs.readFile(join(f.root,'preparations',p.preparationId+'.json')));assert.equal(receipt.phase,mode==='consumed'?'consumed-without-credential':'enrollment-unknown');assert(!await fs.stat(join(f.root,'default.json')).catch(()=>false));}finally{await f.close();}}});

test('later failed setup preserves prior connection/default bytes, and unrelated launch command is retained',async()=>{const f=await fixture();try{const p=await f.profile();const first=await installTerminal(p,{work:f.work,root:f.root,nodeExecutable:f.fakeNode});const original=await fs.readFile(join(f.root,'default.json')),token=await fs.readFile(join(f.root,'connections',first.deviceId,'token'));await fs.writeFile(join(f.root,'launch'),'#!/bin/sh\necho unrelated-owned-command\n');const unrelated=await fs.readFile(join(f.root,'launch'));const failed=await f.profile(true);await assert.rejects(installTerminal(failed,{work:f.work,root:f.root,nodeExecutable:f.fakeNode}),/client-validation-failed/);assert.deepEqual(await fs.readFile(join(f.root,'default.json')),original);assert.deepEqual(await fs.readFile(join(f.root,'connections',first.deviceId,'token')),token);assert.deepEqual(await fs.readFile(join(f.root,'launch')),unrelated);const second=await f.profile();const installed=await installTerminal(second,{work:f.work,root:f.root,nodeExecutable:f.fakeNode});assert.equal(installed.launch,await fs.realpath(join(f.root,'connections',installed.deviceId,'launch')));assert.deepEqual(await fs.readFile(join(f.root,'launch')),unrelated);assert.deepEqual(await fs.readFile(join(f.root,'connections',first.deviceId,'token')),token);}finally{await f.close();}});

test('whole rendered setup executes via verified TLS with no prior client installation and no enrollment replay',async()=>{const f=await fixture();try{const p=await f.profile(),script=join(f.base,'setup.sh');await fs.writeFile(script,f.script(),{mode:0o600});const env={PATH:process.env.PATH,HOME:f.base,TMPDIR:f.base,CURL_CA_BUNDLE:f.cert,NODE_EXTRA_CA_CERTS:f.cert,AMPLIFIER_TERMINAL_HOME:f.root};const result=await promisify(execFile)('/bin/bash',[script],{env,timeout:60000,maxBuffer:1024*1024});assert(result.stdout.includes('Installed locally.'));assert(!result.stdout.includes('private-device-token'));assert(!result.stderr.includes('private-device-token'));assert.equal(f.requests(),1);await assert.rejects(promisify(execFile)('/bin/bash',[script],{env,timeout:60000,maxBuffer:1024*1024}),error=>error.stderr.includes('original-setup-attempt-already-recorded'));assert.equal(f.requests(),1);assert.equal(JSON.parse(await fs.readFile(join(f.root,'preparations',p.preparationId+'.json'))).phase,'installed');}finally{await f.close();}});
