import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm,realpath} from 'node:fs/promises';import {existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';
const {createRecoveryCapabilities}=await import(process.env.RECOVERY_PACKAGE_MODULE??'../dist/index.js');
const hostPath=process.env.RECOVERY_HOST_MODULE,adminPath=process.env.RECOVERY_ADMIN_MODULE,python=process.env.RECOVERY_NATIVE_PYTHON;
const wait=async fn=>{for(let n=0;n<2000;n++){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,5));}throw Error('Cache job did not settle')};
const stopped={version:1,cacheInventory:{version:1,cold:true,paged:true,sourceRetirement:false,clearKinds:['python-bytecode'],requiresRecoveryAdminLease:true}};
test('cache actions require the exact negotiated owner marker and reject paths or broad cache deletion',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'cache-contract-')),options={directory,nativeAuthority:'fixture',nativeAdmin:async()=>{throw Error('Must not call native')},authorize:async()=>({accountId:'one'}),resolveSession:async()=>{throw Error('Must not start a session')},quiescence:{}};
 let cap=createRecoveryCapabilities(options);
 try{assert.equal(cap.manifest.actions['recovery.cache.clear'],undefined);assert.equal(cap.quiescenceAccess['recovery.cache.page'],undefined);await cap.close();cap=createRecoveryCapabilities({...options,nativeMaintenance:stopped});assert.ok(cap.manifest.actions['recovery.cache.clear']);
 await assert.rejects(cap.action({version:1,topic:'recovery',channel:'ahp-root://',operation:'recovery.cache.scan',commandId:'unsafe',args:{path:'/other/cache'}},{clientId:'one',origin:'ui'}),/not permitted/);
 assert.equal(cap.actionSchemas()['recovery.cache.preview'].schema.properties.ids.maxItems,50);
 }finally{await cap.close();await rm(directory,{recursive:true,force:true})}
});
async function fixture(){
 const {createHost}=await import(hostPath),{AdminConnection}=await import(adminPath),directory=await realpath(await mkdtemp(join(tmpdir(),'cache-owner-native-'))),home=join(directory,'home'),workspace=join(directory,'workspace'),app=join(directory,'app');await mkdir(home);await mkdir(workspace);
 const cache=join(app,'foundation/cache/fixture');await mkdir(cache,{recursive:true});const source=join(cache,'sample.py');await writeFile(source,'VALUE = 42\n');
 const git=(...args)=>execFileSync('git',args,{cwd:cache,encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();git('init','-b','main');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');git('add','sample.py');git('commit','-m','fixture');const revision=git('rev-parse','HEAD');git('remote','add','origin','https://example.invalid/cache-fixture.git');git('update-ref','refs/remotes/origin/main',revision);git('branch','--set-upstream-to','origin/main','main');
 await writeFile(join(cache,'.amplifier_cache_meta.json'),JSON.stringify({git_url:'https://fixture:PRIVATE_FIXTURE@example.invalid/cache-fixture.git?token=fixture',ref:'main',commit:revision}));
 const compile=()=>execFileSync(python,['-I','-c','import py_compile,sys;print(py_compile.compile(sys.argv[1],doraise=True))',source],{encoding:'utf8'}).trim(),pyc=compile();
 const history=join(home,'projects/old/sessions/native');await mkdir(history,{recursive:true});await writeFile(join(history,'events.jsonl'),'CANONICAL FIXTURE HISTORY\n');
 const config=join(directory,'native.json');await writeFile(config,JSON.stringify({home,appHome:app,adminWorkspaceRoots:[workspace],adminMaintenance:true,maintenanceExternalWriters:'stopped',workerCommand:['/no/runtime-for-cache-maintenance']}));
 const admin=new AdminConnection({command:python,args:['-I','-m','amplifier_acp','--config',config],cwd:workspace,env:{AMPLIFIER_SOURCE_STORE:join(directory,'sources')},resolveWorkspace:()=>workspace}),calls=[];let host,owner,loseOperation,unknownOperation,holdOperation;
 const options={directory:join(directory,'owner'),nativeAuthority:'fixture',nativeMaintenance:await admin.maintenanceCapabilities(),authorize:async ctx=>({accountId:ctx.clientId}),resolveSession:async()=>{throw Error('No selected session or runtime required')},nativeAdmin:async(op,args,ctx)=>{calls.push([op,structuredClone(args)]);if(op===unknownOperation)throw Error('Uncertain transport; do not replay');if(op===holdOperation?.operation)await holdOperation.promise;const value=await admin.perform(op,args,ctx);if(op===loseOperation){loseOperation=undefined;throw Error('Acknowledgement lost after durable native completion')};return value;},quiescence:{admitQuiescence:args=>host.admitQuiescence(args),inspectQuiescence:()=>host.inspectQuiescence(),quiescenceReceipt:id=>host.quiescenceReceipt(id),withQuiescenceMaintenance:(args,fn)=>host.withQuiescenceMaintenance(args,()=>admin.withMaintenanceFence(args,fn)),releaseQuiescence:args=>host.releaseQuiescence(args)}};
 owner=createRecoveryCapabilities(options);host=await createHost({stateDirectory:join(directory,'host'),allowedWorkspaceRoots:[workspace],engines:[{id:'never',command:'/never/start'}],capabilities:owner,quiescence:{instanceId:'cache-instance',dataScope:'cache-owned',requiredOwners:['recovery',admin.quiescenceParticipant.id],coverage:{capabilities:{recovery:'recovery'}},participants:[owner.quiescenceParticipant,admin.quiescenceParticipant],verifyRelease:async args=>{const proof=owner.readReleaseEvidence(args);assert.ok(proof);return {verified:true,fenceId:args.fenceId,commandId:args.commandId,outcome:'unchanged',instanceId:'cache-instance',dataScope:'cache-owned',receiptId:proof.receiptId}}}});
 const act=(operation,args={},commandId=randomUUID(),clientId='account')=>owner.action({version:1,topic:'recovery',channel:'ahp-root://',operation,args,commandId},{clientId,origin:'ui'}).then(v=>v.result);
 const settled=id=>wait(async()=>{const row=await act('recovery.job',{jobId:id});return ['succeeded','prepared','refused','unknown'].includes(row.state)?row:false;});
 const scan=async()=>settled((await act('recovery.cache.scan')).id);
 const review=async s=>{const page=await act('recovery.cache.page',{jobId:s.id,revision:s.result.revision,limit:50});const ids=page.items.filter(row=>row.clearable).map(row=>row.id);assert.equal(ids.length,1);return settled((await act('recovery.cache.preview',{scanJobId:s.id,revision:s.result.revision,ids,reviewed:true})).id);};
 return {directory,source,pyc,compile,history,admin,host,owner,calls,act,settled,scan,review,lose:op=>loseOperation=op,unknown:op=>unknownOperation=op,hold:operation=>{let release;const promise=new Promise(r=>release=r);holdOperation={operation,promise};return release},close:async()=>{await owner.close();await host.close();await admin.close();await rm(directory,{recursive:true,force:true})}};
}
const nativeOptions={skip:!hostPath||!adminPath||!python,timeout:90000};
test('installed native cache path is cold/paged, all-owner held, immutable and exact after lost clear acknowledgement',nativeOptions,async()=>{
 const f=await fixture();try{
 const scan=await f.scan();assert.equal(scan.state,'succeeded');assert.equal(scan.result.coverage.canonicalHistoryScanned,false);assert.equal(f.host.diagnostics().activeAgents,0);
 const first=await f.act('recovery.cache.page',{jobId:scan.id,revision:scan.result.revision,limit:1});assert.equal(first.items.length,1);assert.ok(first.nextCursor);const rest=await f.act('recovery.cache.page',{jobId:scan.id,revision:scan.result.revision,cursor:first.nextCursor,limit:50});assert.ok(rest.items.length);assert.ok(!JSON.stringify([first,rest]).includes('PRIVATE_FIXTURE'));
 await assert.rejects(f.act('recovery.cache.page',{jobId:scan.id,revision:scan.result.revision},randomUUID(),'other'),/unavailable/);
 const review=await f.review(scan);assert.equal(review.state,'prepared');const detail=await f.act('recovery.preview',{jobId:review.id});assert.equal(detail.coverage,'verified-native-owned-bytecode-only');assert.equal(detail.sourceDirectoriesRemoved,0);
 f.lose('maintenance.cache.clear');const command='clear-original',admitted=await f.act('recovery.cache.clear',{preparedJobId:review.id,previewHash:review.previewHash},command);assert.equal(admitted.state,'queued');const unknown=await f.settled(admitted.id);assert.equal(unknown.state,'unknown');assert.equal(f.host.inspectQuiescence().intakeClosed,true);assert.equal(existsSync(f.pyc),false);
 f.compile();const recovered=await f.act('recovery.reconcile',{jobId:unknown.id});assert.equal(recovered.state,'succeeded');assert.equal(f.host.inspectQuiescence().intakeClosed,false);assert.equal(existsSync(f.pyc),true);assert.equal((await f.act('recovery.command',{commandId:command})).id,admitted.id);assert.equal(f.calls.filter(([op])=>op==='maintenance.cache.clear').length,1);
 assert.equal(await readFile(f.source,'utf8'),'VALUE = 42\n');assert.equal(await readFile(join(f.history,'events.jsonl'),'utf8'),'CANONICAL FIXTURE HISTORY\n');assert.equal((await f.admin.inspectLifecycle()).workerStarted,false);
 }finally{await f.close()}
});
test('stale cache review is a known no-effect refusal and releases all-owner intake',nativeOptions,async()=>{
 const f=await fixture();try{const review=await f.review(await f.scan());await writeFile(f.source,'VALUE = 99\n');const result=await f.settled((await f.act('recovery.cache.clear',{preparedJobId:review.id,previewHash:review.previewHash})).id);assert.equal(result.state,'refused');assert.equal(existsSync(f.pyc),true);assert.equal(f.host.inspectQuiescence().intakeClosed,false);assert.equal(f.calls.filter(([op])=>op==='maintenance.cache.clear').length,1);}finally{await f.close()}
});
test('unknown cache outcomes remain fenced without redispatch; owner close joins the admitted scan',nativeOptions,async()=>{
 const f=await fixture();try{const release=f.hold('maintenance.cache.scan'),job=await f.act('recovery.cache.scan');await wait(()=>f.calls.some(([op])=>op==='maintenance.cache.scan'));assert.equal(f.host.inspectQuiescence().intakeClosed,true);let closed=false;const closing=f.owner.close().then(()=>closed=true);await new Promise(r=>setTimeout(r,10));assert.equal(closed,false);release();await closing;assert.equal(f.calls.filter(([op])=>op==='maintenance.cache.scan').length,1);}finally{await f.close()}
 const g=await fixture();try{const review=await g.review(await g.scan());g.unknown('maintenance.cache.clear');const job=await g.settled((await g.act('recovery.cache.clear',{preparedJobId:review.id,previewHash:review.previewHash})).id);assert.equal(job.state,'unknown');const read=await g.act('recovery.reconcile',{jobId:job.id});assert.equal(read.state,'unknown');assert.equal(g.host.inspectQuiescence().intakeClosed,true);assert.equal(g.calls.filter(([op])=>op==='maintenance.cache.clear').length,1);assert.equal(existsSync(g.pyc),true);}finally{await g.close()}
});
