const allocation={allocationId:'12345678-1234-1234-1234-123456789abc',executionDirectory:'/owned/managed/files',allocationHash:'a'.repeat(64),treeHash:'b'.repeat(64),entryCount:1,bytes:5};
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createRecoveryCapabilities} from '../dist/index.js';
test('recovery retention hold cannot exempt its own queued work and retains unknown proof across reopen',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'recovery-retention-'));let nativeCalls=0;
 const opts={directory,nativeAuthority:'fixture',nativeAdmin:async()=>{nativeCalls++;throw Error('Native must not start')},authorize:async()=>({accountId:'owner'}),resolveSession:async()=>({nativeSessionId:'native',historyCwd:directory,nativeAuthority:'fixture'}),quiescence:{admitQuiescence:async()=>({admitted:false,executed:false,intakeClosed:false})}};
 let owner=createRecoveryCapabilities(opts);const c={fenceId:'f',commandId:'hide',purpose:'managed-files-disposal',instanceId:'i',dataScope:'d'},sessions=Array.from({length:101},(_,i)=>'ahp-session:/'+i);
 try{const p=owner.quiescenceParticipant,lease=await p.acquire(c);assert.equal(p.managedFiles.version,1);assert.deepEqual(await lease.inspectManagedFilesReferences({allocation,sessions}),{coverage:'complete',protected:[],omissions:[]});
 const result=await owner.action({version:1,topic:'recovery',channel:'ahp-root://',operation:'recovery.prepare',commandId:'blocked',args:{sessions:['ahp-session:/0'],parts:['session-history'],privateContentReviewed:true}},{clientId:'owner',origin:'ui'});assert.equal(result.accepted,false);assert.equal(result.result.executed,false);
 await assert.rejects(lease.inspectManagedFilesReferences({allocation:{...allocation,treeHash:'c'.repeat(64)},sessions:['ahp-session:/one']}));await lease.release('unknown');await assert.rejects(lease.inspectManagedFilesReferences({allocation,sessions}));await assert.rejects(lease.release('unchanged',{kind:'admission-refused'}));await owner.close();owner=createRecoveryCapabilities(opts);assert.equal(await owner.quiescenceParticipant.acquire(c),null);
 const proof={verified:true,...c,outcome:'unchanged',receiptId:'exact'};await owner.quiescenceParticipant.reconcileRelease({...c,outcome:'unchanged',proof});await owner.quiescenceParticipant.reconcileRelease({...c,outcome:'unchanged',proof});
 const admitted=await owner.action({version:1,topic:'recovery',channel:'ahp-root://',operation:'recovery.prepare',commandId:'queued',args:{sessions:['ahp-session:/0'],parts:['session-history'],privateContentReviewed:true}},{clientId:'owner',origin:'ui'});assert.equal(admitted.result.state,'queued');assert.equal(await owner.quiescenceParticipant.acquire({...c,fenceId:'other',commandId:admitted.result.commandId}),null);assert.equal(nativeCalls,0);
 }finally{await owner.close();await rm(directory,{recursive:true,force:true})}
});
