import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {spawn,execFileSync} from 'node:child_process';import {createInterface} from 'node:readline';import {randomUUID,createHash} from 'node:crypto';
const {createRecoveryCapabilities}=await import(process.env.RECOVERY_PACKAGE_MODULE??'../dist/index.js');
const hostModule=process.env.RECOVERY_HOST_MODULE,python=process.env.RECOVERY_NATIVE_PYTHON,provider=process.env.RECOVERY_NATIVE_PROVIDER;
const hash=b=>createHash('sha256').update(b).digest('hex');
class Admin {
 constructor(config,env){this.counter=0;this.pending=new Map();this.process=spawn(python,['-m','amplifier_acp','--config',config],{stdio:'pipe',env:{...process.env,...env}});this.process.stderr.on('data',()=>{});createInterface({input:this.process.stdout}).on('line',line=>{const row=JSON.parse(line),pending=this.pending.get(row.id);if(!pending)return;this.pending.delete(row.id);clearTimeout(pending.timer);row.error?pending.reject(Object.assign(Error(row.error.message),{data:row.error.data})):pending.resolve(row.result);});this.process.on('exit',()=>{for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Admin exited; no replay'));}this.pending.clear();});}
 request(method,params){const id=++this.counter;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('Admin response lost; no replay'));},60000);this.pending.set(id,{resolve,reject,timer});this.process.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});}
 async close(){this.process.stdin.end();await new Promise(resolve=>this.process.once('exit',resolve));}
}
const wait=async fn=>{for(let n=0;n<1000;n++){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,10));}throw Error('Native recovery did not settle');};
async function files(root){const output={};async function visit(path,prefix=''){for(const row of await readdir(path,{withFileTypes:true})){if(row.isDirectory())await visit(join(path,row.name),prefix+row.name+'/');else if(row.isFile())output[prefix+row.name]=hash(await readFile(join(path,row.name)));}}await visit(root);return output;}
for(const sharedAdmin of [false,true])test(`installed native admin and host retire actual Core session, preserve canonical files, snapshot and exact reset undo${sharedAdmin?' under held admin lifecycle':''}`,{skip:!hostModule||!python||!provider||sharedAdmin&&!process.env.RECOVERY_ADMIN_MODULE,timeout:120000},async()=>{
 const {createHost}=await import(hostModule),require=createRequire(pathToFileURL(hostModule));
 const {AhpClient}=await import(new URL('../../../@microsoft/agent-host-protocol/dist/client/index.js',pathToFileURL(hostModule)).href),{WebSocketTransport}=await import(new URL('../../../@microsoft/agent-host-protocol/dist/ws/index.js',pathToFileURL(hostModule)).href);
 const directory=await realpath(await mkdtemp(join(tmpdir(),'recovery-native-'))),home=join(directory,'home'),workspace=join(directory,'workspace'),app=join(directory,'app');await mkdir(home);await mkdir(workspace);
 const nativeEnv={AMPLIFIER_SESSION_STATE_HOME:join(directory,'checkpoint'),AMPLIFIER_CONTEXT_INTELLIGENCE_BASE_PATH:join(directory,'events'),AMPLIFIER_SOURCE_STORE:join(directory,'sources')},destinations=join(directory,'restore-destinations');await mkdir(destinations);
 const contextModule=execFileSync(python,['-c','import importlib.util,pathlib;print(pathlib.Path(importlib.util.find_spec("amplifier_module_context_simple").origin).parent)'],{encoding:'utf8'}).trim();
 const bundle=join(directory,'fixture.yaml');await writeFile(bundle,`bundle:\n  name: recovery-offline\n  version: 1.0.0+amplifier-unified.snapshot.1\nsession:\n  orchestrator:\n    module: loop-live\n  context:\n    module: context-simple\n    source: ${contextModule}\nproviders:\n  - module: provider-fixture\n    source: ${provider}\n    config: {}\n`);await writeFile(join(home,'settings.yaml'),'bundle:\n  app: []\n');
 const config=join(directory,'native.json'),adminConfig=join(directory,'admin.json');const settings={home,appHome:app,bundle,adminWorkspaceRoots:[workspace],adminMaintenance:true,maintenanceExternalWriters:'stopped',...(sharedAdmin?{maintenanceFullNative:true,maintenanceFullNativeRoots:{checkpoint:nativeEnv.AMPLIFIER_SESSION_STATE_HOME,events:nativeEnv.AMPLIFIER_CONTEXT_INTELLIGENCE_BASE_PATH,sources:nativeEnv.AMPLIFIER_SOURCE_STORE,bundle},maintenanceRestoreRoots:{owned:destinations}}:{})};await writeFile(config,JSON.stringify(settings));await writeFile(adminConfig,JSON.stringify({...settings,workerCommand:['/impossible/passive-admin-worker']}));
 const {AdminConnection}=sharedAdmin?await import(process.env.RECOVERY_ADMIN_MODULE):{};
 const admin=sharedAdmin?new AdminConnection({command:python,args:['-m','amplifier_acp','--config',adminConfig],cwd:workspace,env:nativeEnv,resolveWorkspace:()=>workspace}):new Admin(adminConfig,nativeEnv);let host,owner,client,loseRestoreAck=false;const calls=[],nativeErrors=[];
 try{
  if(sharedAdmin){assert.equal((await admin.inspectLifecycle()).workerStarted,false);}else{const initialized=await admin.request('initialize',{protocolVersion:1,clientCapabilities:{_meta:{'amplifier.dev/native':{version:1}}}});assert.equal(initialized.agentCapabilities._meta['amplifier.dev/native'].admin.maintenance.selectedOnly,true);}
  const nativeMaintenance=sharedAdmin?await admin.maintenanceCapabilities():undefined;
  owner=createRecoveryCapabilities({nativeMaintenance,restoreDestinationChoices:sharedAdmin?[{id:'owned',label:'Owned inactive destination'}]:[],directory:join(directory,'recovery'),nativeAuthority:'native-fixture',nativeAdmin:async(operation,args,ctx)=>{calls.push(operation);let result;try{result=await (sharedAdmin?admin.perform(operation,args,ctx):admin.request('_amplifier/admin',{cwd:workspace,operation,args}));}catch(error){nativeErrors.push({operation,message:error.message,data:error.data});throw error;}if(loseRestoreAck&&operation==='maintenance.restore.apply'){loseRestoreAck=false;throw Error('Fixture lost restore acknowledgement after native finalized');}return result;},authorize:async ctx=>{assert.equal(ctx.clientId,'owner');return {accountId:'fixture-account'};},resolveSession:async uri=>{const value=await host.inspectSession(uri);return {nativeSessionId:value.nativeSessionId,historyCwd:value.historyHome,nativeAuthority:'native-fixture'};},quiescence:{admitQuiescence:x=>host.admitQuiescence(x),inspectQuiescence:()=>host.inspectQuiescence(),quiescenceReceipt:x=>host.quiescenceReceipt(x),releaseQuiescence:x=>host.releaseQuiescence(x),withQuiescenceMaintenance:(x,fn)=>host.withQuiescenceMaintenance(x,()=>sharedAdmin?admin.withMaintenanceFence(x,fn):fn())}});
  host=await createHost({stateDirectory:join(directory,'host'),allowedWorkspaceRoots:[workspace],engines:[{id:'native',command:python,args:['-m','amplifier_acp','--config',config],env:nativeEnv}],capabilities:owner,resourceProviders:[{scheme:'amplifier-recovery',read:(params,context)=>owner.resourceRead(params,context)}],quiescence:{instanceId:'actual-test',dataScope:'actual-private',requiredOwners:['recovery',...(sharedAdmin?['native-admin']:[])],coverage:{capabilities:{recovery:'recovery'}},participants:[owner.quiescenceParticipant,...(sharedAdmin?[admin.quiescenceParticipant]:[])],verifyRelease:async input=>{const receipt=owner.readReleaseEvidence(input);assert.ok(receipt);assert.equal(receipt.instanceId,'actual-test');assert.equal(receipt.dataScope,'actual-private');return {verified:true,fenceId:input.fenceId,commandId:input.commandId,outcome:'unchanged',instanceId:'actual-test',dataScope:'actual-private',receiptId:receipt.receiptId};}}});
  client=new AhpClient(await WebSocketTransport.connect(host.url));client.connect();await client.initialize({clientId:'owner',protocolVersions:['0.9.0']});const session='ahp-session:/'+randomUUID();await client.request('createSession',{channel:session,provider:'native',workingDirectories:[pathToFileURL(workspace).href]});
  const initialTurn='offline-evidence-'+randomUUID();assert.equal((await host.submitTurn(session,{commandId:initialTurn,text:'snapshot evidence',clientId:'owner'})).accepted,true);assert.equal((await host.waitForTurn(session,initialTurn,30000)).status,'completed');await wait(async()=>{const state=await host.inspectSession(session);return state.status==='idle'&&!state.activeTurnId;});
  assert.equal(host.diagnostics().activeAgents,1);const info=await host.inspectSession(session),nativeSessionDir=join(app,'sessions',info.nativeSessionId);
  const call=async(operation,args={})=>(await client.request('x-amplifier/capabilityAction',{version:1,topic:'recovery',channel:'ahp-root://',operation,args,commandId:randomUUID()})).result;
  const settled=id=>wait(async()=>{const row=await call('recovery.job',{jobId:id});return ['prepared','succeeded','refused','unknown'].includes(row.state)?row:false;});
  let prepared;
  // A completed prompt may still own a final checkpoint/name task. Each explicit
  // new preview is allowed only after a conclusive no-effect quiescence refusal;
  // unknown work is never retried. This exercises the actual retirement gate.
  for(let attempt=0;attempt<100;attempt++){
   prepared=await settled((await call('recovery.prepare',{sessions:[session],parts:['session-history','session-state','native-settings'],privateContentReviewed:true})).id);
   if(prepared.state==='prepared')break;
   assert.equal(prepared.state,'refused',JSON.stringify(prepared));assert.equal(prepared.reason,'quiescence-refused');assert.equal(host.inspectQuiescence().intakeClosed,false);await new Promise(resolve=>setTimeout(resolve,10));
  }
  assert.equal(prepared.state,'prepared',JSON.stringify(prepared));assert.equal(host.diagnostics().activeAgents,0);assert.equal(host.inspectQuiescence().intakeClosed,false);
  const canonical=await files(join(home,'projects'));
  const snapshot=await settled((await call('recovery.snapshot',{preparedJobId:prepared.id,previewHash:prepared.previewHash})).id);assert.equal(snapshot.state,'succeeded',JSON.stringify(snapshot));
  let chunks=[],offset=0;while(offset<snapshot.result.bytes){const uri=new URL(snapshot.result.resourceUri);uri.searchParams.set('offset',String(offset));uri.searchParams.set('maxBytes','8192');const page=await client.request('resourceRead',{channel:'ahp-root://',uri:uri.href,encoding:'base64'});const bytes=Buffer.from(page.data,'base64');assert.ok(bytes.length>0);chunks.push(bytes);offset+=bytes.length;}const raw=Buffer.concat(chunks);assert.equal(hash(raw),snapshot.result.sha256);
  const archive=join(directory,'download.tar');await writeFile(archive,raw);const manifest=JSON.parse(execFileSync(python,['-c','import json,tarfile,sys;print(json.dumps(json.load(tarfile.open(sys.argv[1]).extractfile("manifest.json"))))',archive],{encoding:'utf8'}));assert.equal(manifest.previewHash,prepared.previewHash);assert.ok(manifest.inventory.files.some(row=>row.path.endsWith('metadata.json')));
  // Explicit native-only configuration plan, reviewed through bounded pages.
  await mkdir(join(home,'routing'));for(let i=0;i<70;i++)await writeFile(join(home,'routing',`fixture-${String(i).padStart(3,'0')}.yaml`),`model: offline-${i}\n`);
  await mkdir(join(workspace,'.amplifier'),{recursive:true});await writeFile(join(workspace,'.amplifier','settings.local.yaml'),'fixture: workspace\n');await writeFile(join(workspace,'unselected.txt'),'must remain outside archive');
  const archiveReview=await settled((await call('recovery.archive.prepare',{sessions:[session],workspaceConfigurationFor:[session],parts:['session-history','shared-configuration','workspace-configuration'],privateContentReviewed:true})).id);assert.equal(archiveReview.state,'prepared',JSON.stringify(archiveReview));
  const manifestPage=await call('recovery.preview',{jobId:archiveReview.id,limit:5});assert.equal(manifestPage.items.length,5);assert.ok(manifestPage.nextCursor);assert.ok(manifestPage.totalEntries>70);assert.ok(!JSON.stringify(manifestPage).includes(directory));
  const nextPage=await call('recovery.preview',{jobId:archiveReview.id,cursor:manifestPage.nextCursor,limit:5});assert.equal(nextPage.items.length,5);assert.notEqual(nextPage.items[0].path,manifestPage.items[0].path);
  const selectedArchive=await settled((await call('recovery.snapshot',{preparedJobId:archiveReview.id,previewHash:archiveReview.previewHash})).id);assert.equal(selectedArchive.state,'succeeded',JSON.stringify(selectedArchive));
  const selectedChunks=[];let selectedOffset=0;while(selectedOffset<selectedArchive.result.bytes){const uri=new URL(selectedArchive.result.resourceUri);uri.searchParams.set('offset',String(selectedOffset));uri.searchParams.set('maxBytes','8192');const page=await client.request('resourceRead',{channel:'ahp-root://',uri:uri.href,encoding:'base64'});const bytes=Buffer.from(page.data,'base64');assert.ok(bytes.length);selectedChunks.push(bytes);selectedOffset+=bytes.length;}const selectedBytes=Buffer.concat(selectedChunks);assert.equal(hash(selectedBytes),selectedArchive.result.sha256);
  const selectedPath=join(directory,'selected.tar');await writeFile(selectedPath,selectedBytes);const selectedManifest=JSON.parse(execFileSync(python,['-c','import json,tarfile,sys;print(json.dumps(json.load(tarfile.open(sys.argv[1]).extractfile("manifest.json"))))',selectedPath],{encoding:'utf8'}));assert.equal(selectedManifest.summary.previewHash,archiveReview.previewHash);assert.ok(selectedManifest.entries.some(row=>row.path==='shared-configuration/routing/fixture-069.yaml'));assert.ok(!selectedManifest.entries.some(row=>row.path.includes('unselected.txt')));assert.deepEqual(await files(join(home,'projects')),canonical);
  // Explicit fixture-only setup, after all native workers have been retired.
  await writeFile(join(nativeSessionDir,'configuration.json'),'{"ownedFixture":"retain original"}');const prior=await readFile(join(nativeSessionDir,'configuration.json'));
  const review=await settled((await call('recovery.reset.prepare',{sessionId:session,scope:'session-configuration',privateContentReviewed:true})).id);assert.equal(review.state,'prepared');
  const reset=await settled((await call('recovery.reset.apply',{preparedJobId:review.id,previewHash:review.previewHash})).id);assert.equal(reset.state,'succeeded',JSON.stringify(reset));assert.equal(reset.result.canonicalFilesChanged,0);await assert.rejects(readFile(join(nativeSessionDir,'configuration.json')),/ENOENT/);assert.deepEqual(await files(join(home,'projects')),canonical);
  const undoReview=await settled((await call('recovery.reset.prepare',{sessionId:session,scope:'session-configuration',privateContentReviewed:true})).id);
  const restored=await settled((await call('recovery.reset.restore',{preparedJobId:undoReview.id,previewHash:undoReview.previewHash,resetJobId:reset.id,expectedPostResetHash:reset.result.postResetHash})).id);assert.equal(restored.state,'succeeded',JSON.stringify(restored));assert.deepEqual(await readFile(join(nativeSessionDir,'configuration.json')),prior);assert.deepEqual(await files(join(home,'projects')),canonical);assert.equal(host.diagnostics().activeAgents,0);assert.equal(host.inspectQuiescence().intakeClosed,false);
  if(sharedAdmin)assert.equal((await admin.inspectLifecycle()).intakeClosed,false);
  assert.equal(calls.filter(op=>op==='maintenance.snapshot').length,2);assert.equal(calls.filter(op=>op==='maintenance.reset.apply').length,1);assert.equal(calls.filter(op=>op==='maintenance.reset.restore').length,1);
  if(sharedAdmin){
   const offered=await call('recovery.list');assert.equal(offered.capabilities.restoreAvailable,true);assert.ok(offered.capabilities.archiveParts.includes('native-maintenance-records'));assert.deepEqual(offered.capabilities.restoreDestinations,[{id:'owned',label:'Owned inactive destination'}]);assert.equal(offered.fullProductBackup,false);
   const full=await settled((await call('recovery.archive.prepare',{sessions:[],parts:['full-native-authority'],privateContentReviewed:true})).id);assert.equal(full.state,'prepared',JSON.stringify({job:full,nativeErrors}));assert.equal(full.coverage,'full-configured-native-authority');
   const fullPage=await call('recovery.preview',{jobId:full.id,limit:3});assert.equal(fullPage.items.length,3);assert.ok(fullPage.nextCursor);assert.equal(fullPage.ownerCoverage.completeNativeBackup,true);assert.equal(fullPage.ownerCoverage.completeProductBackup,false);assert.ok(!JSON.stringify(fullPage).includes(directory));
   const captured=await settled((await call('recovery.snapshot',{preparedJobId:full.id,previewHash:full.previewHash})).id);assert.equal(captured.state,'succeeded',JSON.stringify(captured));assert.equal(captured.result.format,'amplifier-native-authority');
   const restore=await settled((await call('recovery.restore.prepare',{snapshotJobId:captured.id,sha256:captured.result.sha256,destination:{rootId:'owned',name:'reviewed-copy'},privateContentReviewed:true})).id);assert.equal(restore.state,'prepared',JSON.stringify(restore));
   const restorePage=await call('recovery.preview',{jobId:restore.id,limit:3});assert.equal(restorePage.items.length,3);assert.equal(restorePage.restore.startsWorker,false);assert.equal(restorePage.restore.overwritesExisting,false);assert.equal(restorePage.ownerCoverage.completeProductBackup,false);
   loseRestoreAck=true;const copying=await call('recovery.restore.apply',{preparedJobId:restore.id,previewHash:restore.previewHash});const uncertain=await settled(copying.id);assert.equal(uncertain.state,'unknown',JSON.stringify(uncertain));assert.equal(host.inspectQuiescence().intakeClosed,true);
   const inspected=await call('recovery.reconcile',{jobId:uncertain.id});assert.equal(inspected.state,'succeeded',JSON.stringify(inspected));assert.equal(host.inspectQuiescence().intakeClosed,false);assert.equal(calls.filter(op=>op==='maintenance.restore.apply').length,1);assert.equal(calls.filter(op=>op==='maintenance.restore.reconcile').length,0);assert.equal(host.diagnostics().activeAgents,0);
   assert.deepEqual(await files(join(home,'projects')),canonical);const restoredCanonical=await files(join(destinations,'reviewed-copy/native-home/projects'));assert.deepEqual(restoredCanonical,Object.fromEntries(Object.entries(canonical).filter(([path])=>!path.endsWith('/live-jobs/owner.lock'))));assert.ok(!Object.keys(restoredCanonical).some(path=>path.endsWith('/live-jobs/owner.lock')));assert.ok((await readFile(join(destinations,'reviewed-copy/native-launcher.json'))).length);
   await assert.rejects(readFile(join(destinations,'reviewed-copy/native-home/.amplifier-acp-restore-pending.json')),/ENOENT/);assert.equal((await admin.inspectLifecycle()).intakeClosed,false);
  }

 }finally{if(client)await client.shutdown();if(owner)await owner.close();if(host)await host.close();await admin.close();await rm(directory,{recursive:true,force:true});}
});
