import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {spawn,execFileSync} from 'node:child_process';import {createInterface} from 'node:readline';import {randomUUID,createHash} from 'node:crypto';
const {createRecoveryCapabilities}=await import(process.env.RECOVERY_PACKAGE_MODULE??'../dist/index.js');
const hostModule=process.env.RECOVERY_HOST_MODULE,python=process.env.RECOVERY_NATIVE_PYTHON,provider=process.env.RECOVERY_NATIVE_PROVIDER;
const hash=b=>createHash('sha256').update(b).digest('hex');
class Admin {
 constructor(config){this.counter=0;this.pending=new Map();this.process=spawn(python,['-m','amplifier_acp','--config',config],{stdio:'pipe'});this.process.stderr.on('data',()=>{});createInterface({input:this.process.stdout}).on('line',line=>{const row=JSON.parse(line),pending=this.pending.get(row.id);if(!pending)return;this.pending.delete(row.id);clearTimeout(pending.timer);row.error?pending.reject(Object.assign(Error(row.error.message),{data:row.error.data})):pending.resolve(row.result);});this.process.on('exit',()=>{for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Admin exited; no replay'));}this.pending.clear();});}
 request(method,params){const id=++this.counter;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('Admin response lost; no replay'));},60000);this.pending.set(id,{resolve,reject,timer});this.process.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});}
 async close(){this.process.stdin.end();await new Promise(resolve=>this.process.once('exit',resolve));}
}
const wait=async fn=>{for(let n=0;n<1000;n++){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,10));}throw Error('Native recovery did not settle');};
async function files(root){const output={};async function visit(path,prefix=''){for(const row of await readdir(path,{withFileTypes:true})){if(row.isDirectory())await visit(join(path,row.name),prefix+row.name+'/');else if(row.isFile())output[prefix+row.name]=hash(await readFile(join(path,row.name)));}}await visit(root);return output;}
test('installed native admin and host retire actual Core session, preserve canonical files, snapshot and exact reset undo',{skip:!hostModule||!python||!provider,timeout:120000},async()=>{
 const {createHost}=await import(hostModule),require=createRequire(pathToFileURL(hostModule));
 const {AhpClient}=await import(new URL('../../../@microsoft/agent-host-protocol/dist/client/index.js',pathToFileURL(hostModule)).href),{WebSocketTransport}=await import(new URL('../../../@microsoft/agent-host-protocol/dist/ws/index.js',pathToFileURL(hostModule)).href);
 const directory=await mkdtemp(join(tmpdir(),'recovery-native-')),home=join(directory,'home'),workspace=join(directory,'workspace'),app=join(directory,'app');await mkdir(home);await mkdir(workspace);
 const contextModule=execFileSync(python,['-c','import importlib.util,pathlib;print(pathlib.Path(importlib.util.find_spec("amplifier_module_context_simple").origin).parent)'],{encoding:'utf8'}).trim();
 const bundle=join(directory,'fixture.yaml');await writeFile(bundle,`bundle:\n  name: recovery-offline\n  version: 1.0.0+amplifier-unified.snapshot.1\nsession:\n  orchestrator:\n    module: loop-live\n  context:\n    module: context-simple\n    source: ${contextModule}\nproviders:\n  - module: provider-fixture\n    source: ${provider}\n    config: {}\n`);await writeFile(join(home,'settings.yaml'),'bundle:\n  app: []\n');
 const config=join(directory,'native.json'),adminConfig=join(directory,'admin.json');const settings={home,appHome:app,bundle,adminWorkspaceRoots:[workspace],adminMaintenance:true,maintenanceExternalWriters:'foundation-cooperative'};await writeFile(config,JSON.stringify(settings));await writeFile(adminConfig,JSON.stringify({...settings,workerCommand:['/impossible/passive-admin-worker']}));
 const admin=new Admin(adminConfig);let host,owner,client;const calls=[];
 try{
  const initialized=await admin.request('initialize',{protocolVersion:1,clientCapabilities:{_meta:{'amplifier.dev/native':{version:1}}}});assert.equal(initialized.agentCapabilities._meta['amplifier.dev/native'].admin.maintenance.selectedOnly,true);
  owner=createRecoveryCapabilities({directory:join(directory,'recovery'),nativeAuthority:'native-fixture',nativeAdmin:async(operation,args)=>{calls.push(operation);return admin.request('_amplifier/admin',{cwd:workspace,operation,args});},authorize:async ctx=>{assert.equal(ctx.clientId,'owner');return {accountId:'fixture-account'};},resolveSession:async uri=>{const value=await host.inspectSession(uri);return {nativeSessionId:value.nativeSessionId,historyCwd:value.historyHome,nativeAuthority:'native-fixture'};},quiescence:{admitQuiescence:x=>host.admitQuiescence(x),inspectQuiescence:()=>host.inspectQuiescence(),quiescenceReceipt:x=>host.quiescenceReceipt(x),releaseQuiescence:x=>host.releaseQuiescence(x),withQuiescenceMaintenance:(x,fn)=>host.withQuiescenceMaintenance(x,fn)}});
  host=await createHost({stateDirectory:join(directory,'host'),allowedWorkspaceRoots:[workspace],engines:[{id:'native',command:python,args:['-m','amplifier_acp','--config',config]}],capabilities:owner,resourceProviders:[{scheme:'amplifier-recovery',read:(params,context)=>owner.resourceRead(params,context)}],quiescence:{instanceId:'actual-test',dataScope:'actual-private',requiredOwners:['recovery'],coverage:{capabilities:{recovery:'recovery'}},participants:[owner.quiescenceParticipant],verifyRelease:async input=>{const receipt=owner.readReleaseEvidence(input);assert.ok(receipt);assert.equal(receipt.instanceId,'actual-test');assert.equal(receipt.dataScope,'actual-private');return {verified:true,fenceId:input.fenceId,commandId:input.commandId,outcome:'unchanged',instanceId:'actual-test',dataScope:'actual-private',receiptId:receipt.receiptId};}}});
  client=new AhpClient(await WebSocketTransport.connect(host.url));client.connect();await client.initialize({clientId:'owner',protocolVersions:['0.9.0']});const session='ahp-session:/'+randomUUID();await client.request('createSession',{channel:session,provider:'native',workingDirectories:[pathToFileURL(workspace).href]});
  assert.equal(host.diagnostics().activeAgents,1);const info=await host.inspectSession(session),nativeSessionDir=join(app,'sessions',info.nativeSessionId);
  const call=async(operation,args={})=>(await client.request('x-amplifier/capabilityAction',{version:1,topic:'recovery',channel:'ahp-root://',operation,args,commandId:randomUUID()})).result;
  const settled=id=>wait(async()=>{const row=await call('recovery.job',{jobId:id});return ['prepared','succeeded','refused','unknown'].includes(row.state)?row:false;});
  const prepared=await settled((await call('recovery.prepare',{sessions:[session],parts:['session-history','session-state','native-settings'],privateContentReviewed:true})).id);assert.equal(prepared.state,'prepared',JSON.stringify(prepared));assert.equal(host.diagnostics().activeAgents,0);assert.equal(host.inspectQuiescence().intakeClosed,false);
  const canonical=await files(join(home,'projects'));
  const snapshot=await settled((await call('recovery.snapshot',{preparedJobId:prepared.id,previewHash:prepared.previewHash})).id);assert.equal(snapshot.state,'succeeded',JSON.stringify(snapshot));
  let chunks=[],offset=0;while(offset<snapshot.result.bytes){const uri=new URL(snapshot.result.resourceUri);uri.searchParams.set('offset',String(offset));uri.searchParams.set('maxBytes','8192');const page=await client.request('resourceRead',{channel:'ahp-root://',uri:uri.href,encoding:'base64'});const bytes=Buffer.from(page.data,'base64');assert.ok(bytes.length>0);chunks.push(bytes);offset+=bytes.length;}const raw=Buffer.concat(chunks);assert.equal(hash(raw),snapshot.result.sha256);
  const archive=join(directory,'download.tar');await writeFile(archive,raw);const manifest=JSON.parse(execFileSync(python,['-c','import json,tarfile,sys;print(json.dumps(json.load(tarfile.open(sys.argv[1]).extractfile("manifest.json"))))',archive],{encoding:'utf8'}));assert.equal(manifest.previewHash,prepared.previewHash);assert.ok(manifest.inventory.files.some(row=>row.path.endsWith('metadata.json')));
  // Explicit fixture-only setup, after all native workers have been retired.
  await writeFile(join(nativeSessionDir,'configuration.json'),'{"ownedFixture":"retain original"}');const prior=await readFile(join(nativeSessionDir,'configuration.json'));
  const review=await settled((await call('recovery.reset.prepare',{sessionId:session,scope:'session-configuration',privateContentReviewed:true})).id);assert.equal(review.state,'prepared');
  const reset=await settled((await call('recovery.reset.apply',{preparedJobId:review.id,previewHash:review.previewHash})).id);assert.equal(reset.state,'succeeded',JSON.stringify(reset));assert.equal(reset.result.canonicalFilesChanged,0);await assert.rejects(readFile(join(nativeSessionDir,'configuration.json')),/ENOENT/);assert.deepEqual(await files(join(home,'projects')),canonical);
  const undoReview=await settled((await call('recovery.reset.prepare',{sessionId:session,scope:'session-configuration',privateContentReviewed:true})).id);
  const restored=await settled((await call('recovery.reset.restore',{preparedJobId:undoReview.id,previewHash:undoReview.previewHash,resetJobId:reset.id,expectedPostResetHash:reset.result.postResetHash})).id);assert.equal(restored.state,'succeeded',JSON.stringify(restored));assert.deepEqual(await readFile(join(nativeSessionDir,'configuration.json')),prior);assert.deepEqual(await files(join(home,'projects')),canonical);assert.equal(host.diagnostics().activeAgents,0);assert.equal(host.inspectQuiescence().intakeClosed,false);
  assert.equal(calls.filter(op=>op==='maintenance.snapshot').length,1);assert.equal(calls.filter(op=>op==='maintenance.reset.apply').length,1);assert.equal(calls.filter(op=>op==='maintenance.reset.restore').length,1);
 }finally{if(client)await client.shutdown();if(owner)await owner.close();if(host)await host.close();await admin.close();await rm(directory,{recursive:true,force:true});}
});
