import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createRecoveryCapabilities} from '../dist/index.js';
test('recovery retention hold cannot exempt its own queued work and retains unknown proof across reopen',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'recovery-retention-'));let nativeCalls=0;
 const opts={directory,nativeAuthority:'fixture',nativeAdmin:async()=>{nativeCalls++;throw Error('Native must not start')},authorize:async()=>({accountId:'owner'}),resolveSession:async()=>({nativeSessionId:'native',historyCwd:directory,nativeAuthority:'fixture'}),quiescence:{admitQuiescence:async()=>({admitted:false,executed:false,intakeClosed:false})}};
 let owner=createRecoveryCapabilities(opts);const c={fenceId:'f',commandId:'hide',purpose:'retention-hide',instanceId:'i',dataScope:'d'},sessions=Array.from({length:101},(_,i)=>'ahp-session:/'+i);
 try{const p=owner.quiescenceParticipant,lease=await p.acquire(c);assert.equal(p.retentionHide.version,1);assert.deepEqual(await lease.inspectRetentionReferences({sessions}),{coverage:'complete',protected:[],omissions:[]});
 const result=await owner.action({version:1,topic:'recovery',channel:'ahp-root://',operation:'recovery.prepare',commandId:'blocked',args:{sessions:['ahp-session:/0'],parts:['session-history'],privateContentReviewed:true}},{clientId:'owner',origin:'ui'});assert.equal(result.accepted,false);assert.equal(result.result.executed,false);
 await lease.release('unknown');await assert.rejects(lease.inspectRetentionReferences({sessions}));await assert.rejects(lease.release('unchanged',{kind:'admission-refused'}));await owner.close();owner=createRecoveryCapabilities(opts);assert.equal(await owner.quiescenceParticipant.acquire(c),null);
 const proof={verified:true,...c,outcome:'unchanged',receiptId:'exact'};await owner.quiescenceParticipant.reconcileRelease({...c,outcome:'unchanged',proof});await owner.quiescenceParticipant.reconcileRelease({...c,outcome:'unchanged',proof});
 const admitted=await owner.action({version:1,topic:'recovery',channel:'ahp-root://',operation:'recovery.prepare',commandId:'queued',args:{sessions:['ahp-session:/0'],parts:['session-history'],privateContentReviewed:true}},{clientId:'owner',origin:'ui'});assert.equal(admitted.result.state,'queued');assert.equal(await owner.quiescenceParticipant.acquire({...c,fenceId:'other',commandId:admitted.result.commandId}),null);assert.equal(nativeCalls,0);
 }finally{await owner.close();await rm(directory,{recursive:true,force:true})}
});
